// Generated by GD++, do not edit.

#pragma once

#include "modules/register_module_types.h"

void initialize_gdpp_module(ModuleInitializationLevel p_level);
void uninitialize_gdpp_module(ModuleInitializationLevel p_level);
