// Generated by GD++, do not edit.

#include "register_types.h"
{{range .}}
void gdpp_register_package_{{.}}();{{end}}

void initialize_gdpp_module(ModuleInitializationLevel p_level) {
	if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
		return;
	}
{{- range .}}
	gdpp_register_package_{{.}}();
{{- end}}
}

void uninitialize_gdpp_module(ModuleInitializationLevel p_level) {}
