// Generated by GD++, do not edit.

#include <type_traits>

#include "core/object/class_db.h"
{{range .Includes}}
#include {{.}}{{end}}

namespace godot {}
using namespace godot;

// In an anonymous namespace, since every package has its own.
namespace {
{{template "register_classes" .}}
} // namespace

void gdpp_register_package_{{.Index}}() {
{{- range .Classes}}
	gdpp_register_class<{{.}}>();
{{- end}}
}
