// Generated by GD++, do not edit.

// godot-cpp's UtilityFunctions, in engine builds: the engine's VariantUtilityFunctions, with its functions that
// take any number of arguments turned into variadic templates, like godot-cpp has them.

#pragma once

#include "core/variant/variant_utility.h"

namespace godot {

struct UtilityFunctions : ::VariantUtilityFunctions {
private:
	template <typename R, typename... Args>
	static R gdpp_call(R (*p_function)(const Variant **, int, Callable::CallError &), const Args &...p_args) {
		const Variant values[] = { Variant(p_args)... };
		const Variant *pointers[sizeof...(Args)];
		for (size_t i = 0; i < sizeof...(Args); i++) {
			pointers[i] = &values[i];
		}
		Callable::CallError error;
		return p_function(pointers, sizeof...(Args), error);
	}

public:
#define GDPP_VARARG(m_name)                                                            \
	template <typename... Args>                                                        \
	static auto m_name(const Variant &p_arg, const Args &...p_args) {                   \
		return gdpp_call(&::VariantUtilityFunctions::m_name, p_arg, p_args...);         \
	}
	GDPP_VARARG(max)
	GDPP_VARARG(min)
	GDPP_VARARG(str)
	GDPP_VARARG(print)
	GDPP_VARARG(print_rich)
	GDPP_VARARG(printerr)
	GDPP_VARARG(printt)
	GDPP_VARARG(prints)
	GDPP_VARARG(printraw)
	GDPP_VARARG(print_verbose)
	GDPP_VARARG(push_error)
	GDPP_VARARG(push_warning)
#undef GDPP_VARARG
};

} // namespace godot
