// GD++ runtime for syntax 0: helpers for the C++ that GD++ generates. Generated by GD++, do not edit.

#ifndef GDPP_SYNTAX_0_HPP
#define GDPP_SYNTAX_0_HPP

#include <atomic>
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <functional>
#include <mutex>
#include <thread>
#include <type_traits>
#include <utility>
#include <vector>

#if defined(MACOS_ENABLED) && defined(HOT_RELOAD_ENABLED)
#include <pthread.h>
#endif

#include <godot_cpp/classes/engine.hpp>
#include <godot_cpp/classes/global_constants.hpp>
#include <godot_cpp/classes/node.hpp>
#include <godot_cpp/classes/packed_scene.hpp>
#include <godot_cpp/classes/project_settings.hpp>
#include <godot_cpp/classes/ref.hpp>
#include <godot_cpp/classes/ref_counted.hpp>
#include <godot_cpp/classes/resource.hpp>
#include <godot_cpp/classes/resource_loader.hpp>
#include <godot_cpp/classes/scene_tree.hpp>
#include <godot_cpp/classes/window.hpp>
#include <godot_cpp/classes/worker_thread_pool.hpp>
#include <godot_cpp/core/binder_common.hpp>
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/core/gdvirtual.gen.inc>
#include <godot_cpp/core/method_ptrcall.hpp>
#include <godot_cpp/core/type_info.hpp>
#include <godot_cpp/variant/callable_custom.hpp>
#include <godot_cpp/variant/typed_array.hpp>
#include <godot_cpp/variant/typed_dictionary.hpp>
#include <godot_cpp/variant/utility_functions.hpp>
#include <godot_cpp/variant/variant.hpp>
#ifdef DEBUG_ENABLED
#include <algorithm>

#include <godot_cpp/classes/performance.hpp>
#endif

// The C++ type of Godot's float.
typedef double float64_t;

// Godot's global scope functions, e.g. gd::print("Hello!").
using gd = godot::UtilityFunctions;

// GDPP_STRING_NAME("name") is the StringName name, created on first use and reused after, like the engine's SNAME.
// Calls by name use it, so they don't intern the name, which locks a global mutex, on every call. Unlike SNAME, it
// isn't a static StringName: those keep pointing to the literal, which hot reload unloads with the library.
#define GDPP_STRING_NAME(m_name) ([]() -> const godot::StringName & { static const godot::StringName name(m_name); return name; })()

namespace gdpp {

using namespace godot;

// Emitted is the result of a signal's emit function. It's [[nodiscard]], so emitting a signal must be spelled
// `emit my_signal(42);`, which reads differently from a function call.
struct [[nodiscard]] Emitted {
	// The result of emit_signal: OK, or why the emission failed.
	Error error;
};

// info returns the PropertyInfo of a value of type T named p_name, as bindings expose it.
template <typename T>
PropertyInfo info(const StringName &p_name, uint32_t p_usage = PROPERTY_USAGE_DEFAULT,
		PropertyHint p_hint = PROPERTY_HINT_NONE, const String &p_hint_string = "") {
	PropertyInfo result = GetTypeInfo<T>::get_class_info();
	result.name = p_name;
	result.usage = p_usage | (result.usage & (PROPERTY_USAGE_NIL_IS_VARIANT | PROPERTY_USAGE_CLASS_IS_ENUM | PROPERTY_USAGE_CLASS_IS_BITFIELD));
	if constexpr (std::is_pointer_v<T>) {
		if constexpr (std::is_base_of_v<Node, std::remove_pointer_t<T>>) {
			result.hint = PROPERTY_HINT_NODE_TYPE;
		}
	}
	if (p_hint != PROPERTY_HINT_NONE) {
		result.hint = p_hint;
		result.hint_string = p_hint_string;
	}
	return result;
}

// add_property_category starts a category named p_name in the inspector, like GDScript's @export_category. Godot has
// no function for it, so it's a property without setter and getter, which godot-cpp's ClassDB doesn't allow.
inline void add_property_category(const StringName &p_class, const String &p_name) {
	PropertyInfo info(Variant::NIL, p_name, PROPERTY_HINT_NONE, "", PROPERTY_USAGE_CATEGORY);
	StringName none;
	GDExtensionPropertyInfo gdext_info = { GDEXTENSION_VARIANT_TYPE_NIL, info.name._native_ptr(), info.class_name._native_ptr(),
		info.hint, info.hint_string._native_ptr(), info.usage };
	gdextension_interface::classdb_register_extension_class_property(gdextension_interface::library, p_class._native_ptr(),
			&gdext_info, none._native_ptr(), none._native_ptr());
}

// rpc_config sets the RPC configuration of p_method on p_node, as @rpc declares it.
template <typename T>
void rpc_config(T *p_node, const StringName &p_method, int64_t p_mode, int64_t p_transfer_mode, bool p_call_local, int64_t p_channel) {
	static_assert(std::is_base_of_v<Node, T>, "@rpc can only be used in classes that extend Node.");
	Dictionary config;
	config["rpc_mode"] = p_mode;
	config["transfer_mode"] = p_transfer_mode;
	config["call_local"] = p_call_local;
	config["channel"] = p_channel;
	p_node->rpc_config(p_method, config);
}

// call_thread_safe calls p_method on p_node with call_thread_safe, as @thread_safe does.
template <typename T, typename... Args>
void call_thread_safe(T *p_node, const StringName &p_method, const Args &...p_args) {
	static_assert(std::is_base_of_v<Node, T>, "@thread_safe can only be used in classes that extend Node.");
	p_node->call_thread_safe(p_method, p_args...);
}

template <typename T>
class ExtPtr;
template <typename T>
class ExtRef;
template <typename T>
class Async;
template <typename T>
class Weak;

// strong_t<T> is what a Weak<T> converts to: a Ref<T> for a refcounted class T, and a T * otherwise.
template <typename T>
using strong_t = std::conditional_t<std::is_base_of_v<RefCounted, T>, Ref<T>, T *>;

// object_class<T>::type is the class of the object that T points to, for a pointer, Ref, extern, Async or Weak, and void
// for other types.
template <typename T>
struct object_class {
	// The class, or void.
	using type = void;
};
template <typename T>
struct object_class<T *> {
	using type = T;
};
template <typename T>
struct object_class<Ref<T>> {
	using type = T;
};
template <typename T>
struct object_class<ExtPtr<T>> {
	using type = typename T::Base;
};
template <typename T>
struct object_class<ExtRef<T>> {
	using type = typename T::Base;
};
template <typename T>
struct object_class<Async<T>> {
	using type = RefCounted;
};
template <typename T>
struct object_class<Weak<T>> {
	using type = T;
};

// object_ptr returns the raw pointer to the object that p_value points to: here, the pointer itself.
template <typename T>
T *object_ptr(T *p_value) { return p_value; }
// object_ptr of a Ref: the object it references.
template <typename T>
T *object_ptr(const Ref<T> &p_value) { return p_value.ptr(); }
// object_ptr of an ExtPtr: its object, as the extern's base class.
template <typename T>
auto object_ptr(const ExtPtr<T> &p_value) { return p_value.base(); }
// object_ptr of an ExtRef: its object, as the extern's base class.
template <typename T>
auto object_ptr(const ExtRef<T> &p_value) { return p_value.base().ptr(); }
// object_ptr of an Async: its task object.
template <typename T>
RefCounted *object_ptr(const Async<T> &p_value) { return p_value.object().ptr(); }

// cast converts p_value to T, picking the conversion at compile time:
//   - from a Variant, as Godot's bindings do, with enums as ints,
//   - to a Variant, with enums as ints,
//   - between pointers, Refs, externs, Asyncs and Weaks: up casts are static, other casts check the object's class, and give
//     null if it doesn't match; externs only check their base class,
//   - anything else with static_cast, e.g. numbers and enums.
template <typename T, typename U>
T cast(const U &p_value) {
	using To = typename object_class<T>::type;
	using From = typename object_class<U>::type;
	if constexpr (std::is_same_v<T, U>) {
		return p_value;
	} else if constexpr (std::is_same_v<U, Variant>) {
		if constexpr (std::is_enum_v<T>) {
			return static_cast<T>(p_value.operator int64_t());
		} else {
			return VariantCaster<T>::cast(p_value);
		}
	} else if constexpr (std::is_same_v<T, Variant>) {
		if constexpr (std::is_enum_v<U>) {
			return static_cast<int64_t>(p_value);
		} else {
			return Variant(p_value);
		}
	} else if constexpr (std::is_base_of_v<Object, To> && std::is_base_of_v<Object, From>) {
		// Braces, unlike T(...), don't cast a const pointer to a mutable one.
		if constexpr (std::is_base_of_v<To, From>) {
			return T{ object_ptr(p_value) };
		} else {
			return T{ Object::cast_to<std::remove_cv_t<To>>(object_ptr(p_value)) };
		}
	} else {
		return static_cast<T>(p_value);
	}
}
// cast of a Weak converts what it converts to, i.e. its object, or null once it's gone.
template <typename T, typename U>
T cast(const Weak<U> &p_value) { return cast<T>(strong_t<U>(p_value.ptr())); }

// ExtPtr<T> points to an object of the extern T, whose base class isn't refcounted. Its members are called by
// name: ptr->foo() is ptr.base()->call("foo"). Only its members need T to be complete, so a field of type ExtPtr<T>
// only needs T to be declared.
template <typename T>
class ExtPtr {
public:
	// A null ExtPtr.
	ExtPtr() = default;
	// A null ExtPtr, from nullptr.
	ExtPtr(std::nullptr_t) {}
	// Points to p_object, which must be an object of the extern: it isn't checked.
	template <typename U = T>
	ExtPtr(typename U::Base *p_object) :
			object_(p_object) {}
	// Converts from an extern that extends T.
	template <typename U, std::enable_if_t<std::is_base_of_v<T, U>, int> = 0>
	ExtPtr(const ExtPtr<U> &p_other) :
			object_(p_other.object_) {}

	// base returns the object as a pointer to the extern's base class.
	auto base() const { return static_cast<typename T::Base *>(object_); }
	// True if it isn't null.
	explicit operator bool() const { return object_ != nullptr; }
	// True if both point to the same object.
	bool operator==(const ExtPtr &p_other) const { return object_ == p_other.object_; }
	// The object, as a Variant.
	operator Variant() const { return Variant(object_); }

	// Arrow is what -> returns: it holds the T that calls the object's members by name.
	struct Arrow {
		T wrapper;
		T *operator->() { return &wrapper; }
	};
	// ptr->foo() calls foo on the object, by name.
	Arrow operator->() const { return Arrow{ T(base()) }; }

private:
	template <typename>
	friend class ExtPtr;
	Object *object_ = nullptr;
};

// ExtRef<T> references an object of the extern T, whose base class is refcounted. Its members are called by
// name: ref->foo() is ref.base()->call("foo"). Like ExtPtr<T>, only its members need T to be complete.
template <typename T>
class ExtRef {
public:
	// A null ExtRef.
	ExtRef() = default;
	// A null ExtRef, from nullptr.
	ExtRef(std::nullptr_t) {}

	// References p_object, which must be an object of the extern: it isn't checked.
	template <typename U = T>
	ExtRef(const Ref<typename U::Base> &p_object) :
			object_(p_object.ptr()) {}
	// References p_object, like the Ref, keeping it alive.
	template <typename U = T>
	ExtRef(typename U::Base *p_object) :
			object_(p_object) {}
	// Converts from an extern that extends T.
	template <typename U, std::enable_if_t<std::is_base_of_v<T, U>, int> = 0>
	ExtRef(const ExtRef<U> &p_other) :
			object_(p_other.object_) {}

	// base returns the object as a Ref of the extern's base class.
	auto base() const { return Ref<typename T::Base>(static_cast<typename T::Base *>(object_.ptr())); }
	// True if it isn't null.
	explicit operator bool() const { return object_.is_valid(); }
	// True if both reference the same object.
	bool operator==(const ExtRef &p_other) const { return object_ == p_other.object_; }
	// The object, as a Variant.
	operator Variant() const { return Variant(object_); }

	// Arrow is what -> returns: it holds the T that calls the object's members by name.
	struct Arrow {
		T wrapper;
		T *operator->() { return &wrapper; }
	};
	// ref->foo() calls foo on the object, by name.
	Arrow operator->() const { return Arrow{ T(static_cast<typename T::Base *>(object_.ptr())) }; }


private:
	template <typename>
	friend class ExtRef;
	Ref<RefCounted> object_;
};

// Ext<T> is how code holds an object of the extern T: an ExtRef<T> if its base class is refcounted, else an ExtPtr<T>.
template <typename T>
using Ext = std::conditional_t<std::is_base_of_v<RefCounted, typename T::Base>, ExtRef<T>, ExtPtr<T>>;

// ExtCreate<T> is how create, destroy and queue_destroy treat the objects of the extern T with @scene or @pool:
// create calls the static method gdpp_create of T's class, and with pool, destroy and queue_destroy call the methods
// gdpp_destroy and gdpp_queue_destroy of the object.
template <typename T>
struct ExtCreate {
	// Whether the extern has @pool: destroy and queue_destroy return its objects to their pool.
	bool pool;
};

// has_ext_create<T> is true for the extern T with @scene or @pool, but not for externs that extend it.
template <typename T, typename = void>
struct has_ext_create : std::false_type {};
template <typename T>
struct has_ext_create<T, std::void_t<decltype(T::gdpp_ext_create)>> : std::is_same<std::remove_cv_t<decltype(T::gdpp_ext_create)>, ExtCreate<T>> {};

// has_ext_pool<T>() is true for the extern T with @pool.
template <typename T>
constexpr bool has_ext_pool() {
	if constexpr (has_ext_create<T>::value) {
		return T::gdpp_ext_create.pool;
	} else {
		return false;
	}
}

// create_ext creates an object of the extern T: an instance of the ClassDB class or global script class that T
// names. For an extern with @scene or @pool, it's what the class's static method gdpp_create gives, which may be null,
// e.g. from a full pool.
template <typename T>
Ext<T> create_ext() {
	const StringName &name = GDPP_STRING_NAME(T::gdpp_name);
	if constexpr (has_ext_create<T>::value) {
		const StringName &method = GDPP_STRING_NAME("gdpp_create");
		Ext<T> result = Object::cast_to<typename T::Base>(ClassDB::class_call_static(name, method).operator Object *());
		ERR_FAIL_COND_V_MSG(!result && !ClassDB::class_has_method(name, method), nullptr,
				String("Failed to create an object of the extern ") + T::gdpp_name + ": its class has no static method gdpp_create.");
		return result;
	}
	Variant object;
	if (ClassDB::class_exists(name)) {
		object = ClassDB::instantiate(name);
	} else {
		TypedArray<Dictionary> classes = ProjectSettings::get_singleton()->get_global_class_list();
		for (int64_t i = 0; i < classes.size(); i++) {
			Dictionary c = classes[i];
			if (StringName(c["class"]) == name) {
				object = ResourceLoader::get_singleton()->load(c["path"])->call("new");
				break;
			}
		}
	}
	// A refcounted object is freed with the last reference to it, so the ExtRef must take it before object goes.
	Ext<T> result = Object::cast_to<typename T::Base>(object.operator Object *());
	ERR_FAIL_COND_V_MSG(!result, nullptr, String("Failed to create an object of the extern ") + T::gdpp_name + ".");
	return result;
}

// assert_message is the error printed by a failed assertion. It has no location, since Godot shows that below it.
inline String assert_message(const char *p_condition) {
	return vformat("Failed GD++ assertion: `%s`.", p_condition);
}

// returns_void reports whether p_signature, a function's GDPP_SIGNATURE, has the return type void, or none, like a
// GCC lambda's. A deduced lambda's, `auto` on Clang, counts as void too.
constexpr bool returns_void(const char *p_signature) {
	auto starts = [](const char *s, const char *w) {
		for (; *w; s++, w++) {
			if (*s != *w) {
				return false;
			}
		}
		return true;
	};
	for (const char *w : { "static ", "virtual ", "inline ", "constexpr ", "__cdecl ", "__thiscall ", "__stdcall ", "__vectorcall " }) {
		if (starts(p_signature, w)) {
			while (*w++) {
				p_signature++;
			}
			return returns_void(p_signature);
		}
	}
	if (starts(p_signature, "auto ") || (starts(p_signature, "void ") && p_signature[5] != '*' && p_signature[5] != '&')) {
		return true;
	}
	// A return type ends with a space before the name, outside of template arguments.
	for (int depth = 0; *p_signature && (*p_signature != '(' || depth > 0); p_signature++) {
		depth += *p_signature == '<' ? 1 : *p_signature == '>' ? -1 : 0;
		if (*p_signature == ' ' && depth == 0) {
			return false;
		}
	}
	return true;
}

// returns_reference reports whether p_signature, a function's GDPP_SIGNATURE, has a return type that's an lvalue
// reference: the last space before the name has a single '&' next to it.
constexpr bool returns_reference(const char *p_signature) {
	const char *space = nullptr;
	for (int depth = 0; *p_signature && (*p_signature != '(' || depth > 0); p_signature++) {
		depth += *p_signature == '<' ? 1 : *p_signature == '>' ? -1 : 0;
		if (*p_signature == ' ' && depth == 0) {
			space = p_signature;
		}
	}
	return space && ((space[-1] == '&' && space[-2] != '&') || (space[1] == '&' && space[2] != '&'));
}

// Default is what a failed assertion returns from a function that returns a value: it converts to any type T as T().
struct Default {
	// Converts to T().
	template <typename T>
	operator T() const { return T(); }
};

// DefaultRef is what a failed assertion returns from a function that returns a reference: it converts to any T & as
// a T() that lives on, since the caller may still use it. Default can't do both, since its conversions would be ambiguous.
struct DefaultRef {
	// Converts to a T() that lives on.
	template <typename T>

	operator T &() const {
		static T fallback{};
		return fallback;
	}
};

// assert_return is what a failed assertion returns, with V true in void functions, and R in those that return a
// reference.
template <bool V, bool R>
auto assert_return() {
	if constexpr (V) {
		return;
	} else if constexpr (R) {
		return DefaultRef{};
	} else {
		return Default{};
	}
}

// GDPP_ASYNC_CLASS is the name of the package's class of tasks, e.g. FooAsync: its prefix and Async. The package
// registers it, and the build defines this macro.
#ifndef GDPP_ASYNC_CLASS
#define GDPP_ASYNC_CLASS GdppAsync
#endif
#define GDPP_STRINGIFY(m_name) GDPP_STRINGIFY_(m_name)
#define GDPP_STRINGIFY_(m_name) #m_name
// async_class is the name of the package's class of tasks, as a string, e.g. "FooAsync".
inline constexpr const char *async_class = GDPP_STRINGIFY(GDPP_ASYNC_CLASS);

// GDPP_QUIT_TIMEOUT_USEC is how long the package's tasks may still run after the game started quitting, before
// the game exits anyway: its quit_timeout setting. The build defines it.
#ifndef GDPP_QUIT_TIMEOUT_USEC
#define GDPP_QUIT_TIMEOUT_USEC 1000000
#endif

#if defined(MACOS_ENABLED) && defined(HOT_RELOAD_ENABLED)
// ThreadSlot is a T per thread, made on first use. It uses a pthread key, since on macOS thread_local keeps the
// library from being unloaded, which breaks hot reload. It frees the Ts when the library is unloaded, not when their
// threads exit: Godot's threads outlive the library, so a key destructor would call unloaded code.
template <typename T>
class ThreadSlot {
public:
	// Makes the pthread key.
	ThreadSlot() { pthread_key_create(&key, nullptr); }
	// Deletes the key, and frees the Ts of all threads.
	~ThreadSlot() {
		pthread_key_delete(key);
		for (T *value : values) {
			delete value;
		}
	}

	// get returns this thread's T, which it makes, value-initialized, on first use.
	T &get() {
		if (void *value = pthread_getspecific(key)) {
			return *static_cast<T *>(value);
		}
		T *value = new T();
		pthread_setspecific(key, value);
		std::lock_guard<std::mutex> lock(mutex);
		values.push_back(value);
		return *value;
	}

private:
	pthread_key_t key;
	std::mutex mutex;
	std::vector<T *> values;
};

// GDPP_THREAD_LOCAL defines m_name(), which returns this thread's m_type, value-initialized on first use.
#define GDPP_THREAD_LOCAL(m_type, m_name)        \
	inline ThreadSlot<m_type> m_name##_slot;     \
	inline m_type &m_name() {                    \
		return m_name##_slot.get();              \
	}
#else
#define GDPP_THREAD_LOCAL(m_type, m_name)        \
	inline m_type &m_name() {                    \
		static thread_local m_type value{};      \
		return value;                            \
	}
#endif

// The state of the package's tasks.
// quitting is whether the game has started quitting.
inline std::atomic<bool> quitting = false;
// watching_quit is whether watch_quit was scheduled.
inline std::atomic<bool> watching_quit = false;
// quit_deadline_usec is when the quit timeout runs out, in now_usec() time.
inline std::atomic<int64_t> quit_deadline_usec = 0;
// running_tasks counts the package's tasks whose jobs are running.
inline std::atomic<int64_t> running_tasks = 0;
// current_cancel() is the cancel flag of this thread's task.
GDPP_THREAD_LOCAL(const std::atomic<bool> *, current_cancel)

// The package's hooks into the engine that call its library's code, e.g. signal connections, which uninitialize
// removes: after a hot reload, the engine would call the unloaded code.
// unhooks_mutex guards unhooks.
inline std::mutex unhooks_mutex;
// unhooks are the functions that remove the hooks, which on_unload adds.
inline std::vector<std::function<void()>> unhooks;

// on_unload makes uninitialize call p_unhook.
inline void on_unload(std::function<void()> p_unhook) {
	std::lock_guard<std::mutex> lock(unhooks_mutex);
	unhooks.push_back(std::move(p_unhook));
}

// connect_until_unload connects p_signal of p_object to p_callable, until the library is unloaded.
inline void connect_until_unload(Object *p_object, const StringName &p_signal, const Callable &p_callable) {
	p_object->connect(p_signal, p_callable);
	on_unload([id = p_object->get_instance_id(), p_signal, p_callable] {
		Object *object = ObjectDB::get_instance(id);
		if (object && object->is_connected(p_signal, p_callable)) {
			object->disconnect(p_signal, p_callable);
		}
	});
}

// Scene<T> is the type of the @scene class T's _gdpp_scene: the res:// path of its scene.
template <typename T>
struct Scene {
	// The res:// path of the scene.
	const char *path;
};


// has_scene<T> is true for the @scene class T, but not for classes that extend it.
template <typename T, typename = void>
struct has_scene : std::false_type {};
template <typename T>
struct has_scene<T, std::void_t<decltype(T::_gdpp_scene)>> : std::is_same<std::remove_cv_t<decltype(T::_gdpp_scene)>, Scene<T>> {};

// SceneCache<T> keeps the scene of the @scene class T, once loaded.
template <typename T>
struct SceneCache {
	// Guards scene and hooked.
	static inline std::mutex mutex;
	// The scene, or null until it's loaded.
	static inline Ref<PackedScene> scene;
	// Whether on_unload evicts the scene.
	static inline bool hooked = false;
};

// evict_scene drops the scene of the @scene class T, so that scene<T> loads it again. It's thread-safe.
template <typename T>
void evict_scene() {
	Ref<PackedScene> evicted; // Freed outside the lock.
	std::lock_guard<std::mutex> lock(SceneCache<T>::mutex);
	evicted = SceneCache<T>::scene;
	SceneCache<T>::scene.unref();
}

// scene returns the scene of the @scene class T, which it loads once and keeps until evict_scene<T> or the library is
// unloaded, or null if it fails to load. It's thread-safe.
template <typename T>
Ref<PackedScene> scene() {
	using C = SceneCache<T>;
	{
		std::lock_guard<std::mutex> lock(C::mutex);
		if (C::scene.is_valid()) {
			return C::scene;
		}
	}
	Ref<PackedScene> s = ResourceLoader::get_singleton()->load(T::_gdpp_scene.path);
	ERR_FAIL_COND_V_MSG(s.is_null(), nullptr, vformat("Failed to load the scene %s of %s.", T::_gdpp_scene.path, T::get_class_static()));
	bool hook = false;
	{
		// Of threads that load it at once, the first keeps its scene.
		std::lock_guard<std::mutex> lock(C::mutex);
		if (C::scene.is_null()) {
			C::scene = s;
		}
		s = C::scene;
		hook = !std::exchange(C::hooked, true);
	}
	// Outside the lock: uninitialize runs the hook, which takes it, while it holds the lock that on_unload takes.
	if (hook) {
		on_unload([] {
			evict_scene<T>();
			std::lock_guard<std::mutex> lock(C::mutex);
			C::hooked = false;
		});
	}
	return s;
}

// make creates an object of the class T: for a @scene class, an instance of its scene, whose root must be a T, or
// null if it isn't; for other classes, memnew(T).
template <typename T>
T *make() {
	if constexpr (has_scene<T>::value) {
		Ref<PackedScene> s = scene<T>();
		Node *root = s.is_valid() ? s->instantiate() : nullptr;
		T *object = Object::cast_to<T>(root);
		if (root && !object) {
			ERR_PRINT(vformat("The root of the scene %s is a %s, not a %s.", T::_gdpp_scene.path, root->get_class(), T::get_class_static()));
			memdelete(root);
		}
		return object;
	} else {
		return memnew(T);
	}
}

// PoolSlot is how an object of a @pool class is in its pool: owned tells whether the pool made it, and cell is where
// it rests in the pool, or null otherwise.
template <typename T>
struct PoolSlot {
	// Whether the pool made it, and hasn't dropped it since.
	bool owned = false;
	// Whether destroy gave it back: it rests in the pool, or is on its way there.
	bool given = false;
	// Whether it got ready once: its @onready values and _ready without @recycle don't run again.
	bool readied = false;
	// Where it rests in the pool, or null.
	T **cell = nullptr;
	// Where it is in the pool's list of the objects it made, if owned.
	int64_t index = 0;
	// How many times it was given back, so Weak<T> knows a reused object.
	std::atomic<uint64_t> generation = 0;
};

// PoolMode is what a Pool does when all the objects of its size are in use, and create needs another.
enum class PoolMode {
	// Makes no more objects: create gives null.
	FIXED,
	// Makes more objects, with an error in debug builds each time it grows past the size times a power of 2.
	GROW,
};

// reserving() is whether this thread's Pool::reserve is making an object, whose constructor then skips its @recycle
// parts, and clears it.
GDPP_THREAD_LOCAL(bool, reserving)

// Pool<T> keeps the objects of the @pool class T that destroy gave back, for create to reuse. It makes size objects,
// and then more only with GROW. reserve makes objects ahead of time, and clear drops them all. take, give and forget
// are thread-safe and O(1); reserve and clear must be called from the main thread. The resting objects are in a list
// of chunks of fixed size, so that a pool that grows never moves them, and taking and giving back only touch the last
// chunk. Chunks are kept once made.
template <typename T>
class Pool {
public:
	// A pool of p_size objects, which does p_mode when they're all in use.
	Pool(int64_t p_size, PoolMode p_mode) :
			size_(p_size), mode_(p_mode), warn_at_(p_size) {}
	// Frees the pool's chunks, not the objects: trim frees those when the library is unloaded.
	~Pool() {
		for (Chunk *chunk = first_.next; chunk;) {
			delete std::exchange(chunk, chunk->next);
		}
	}

	// take returns a resting object, after running its @recycle ctor, or a new object, or null when full.
	T *take() {
		T *object = nullptr;
		{
			std::lock_guard<std::mutex> lock(mutex_);
			hook();
			if (!(object = pop()) && !admit()) {
				return nullptr;
			}
		}
		if (!object) {
			return adopt(false);
		}
		object->_gdpp_recycle_ctor();
		object->request_ready(); // So that it gets ready again when it next enters the tree, like a new node.
		return object;
	}

	// give keeps p_object, after running its @recycle dtor and removing it from the tree. Giving it back again, before
	// it's reused, does nothing.
	void give(T *p_object) {
		{
			std::lock_guard<std::mutex> lock(mutex_);
			if (p_object->_gdpp_pool_slot.given) {
				return;
			}
			p_object->_gdpp_pool_slot.given = true;
			p_object->_gdpp_pool_slot.generation++;
		}
		p_object->_gdpp_recycle_dtor();
		if (Node *parent = p_object->get_parent()) {
			parent->remove_child(p_object);
		}
		{
			std::lock_guard<std::mutex> lock(mutex_);
			if (p_object->_gdpp_pool_slot.owned) {
				push(p_object);
				return;
			}
		}
		p_object->queue_free(); // clear dropped it meanwhile, so it's deleted, like objects the pool didn't make.
	}

	// forget drops p_object, which is being freed, if the pool owns it. A resting one's cell gets the last resting
	// object.
	void forget(T *p_object) {
		std::lock_guard<std::mutex> lock(mutex_);
		PoolSlot<T> &slot = p_object->_gdpp_pool_slot;
		if (!slot.owned) {
			return;
		}
		alive_--;
		owned_[slot.index] = owned_.back();
		owned_[slot.index]->_gdpp_pool_slot.index = slot.index;
		owned_.pop_back();
		if (T **cell = slot.cell) {
			if (T *last = pop(); last != p_object) {
				*cell = last;
				last->_gdpp_pool_slot.cell = cell;
			}
		}
	}

	// reserve makes or frees resting objects, so that the pool has p_count objects, resting or in use. A new object
	// rests unused: it skips its @recycle parts until take hands it out. With p_mode, "fixed" or "grow", it first
	// makes p_count the size, and p_mode the mode. It never frees objects in use.
	void reserve(int64_t p_count, const String &p_mode) {
		ERR_FAIL_COND_MSG(p_count < 0, vformat("A GD++ object pool can't reserve %d objects.", p_count));
		ERR_FAIL_COND_MSG(!p_mode.is_empty() && p_mode != "fixed" && p_mode != "grow", vformat("A GD++ object pool's mode is \"fixed\" or \"grow\", not \"%s\".", p_mode));
		{
			std::lock_guard<std::mutex> lock(mutex_);
			hook();
			if (!p_mode.is_empty()) {
				size_ = warn_at_ = p_count;
				mode_ = p_mode == "grow" ? PoolMode::GROW : PoolMode::FIXED;
			}
		}
		while (room(p_count)) {
			reserving() = true;
			T *object = adopt(true);
			reserving() = false; // If make failed before the constructor cleared it.
			if (!object) {
				break;
			}
		}
		trim(p_count);
	}

	// clear drops all the objects the pool made: it frees the resting ones right away, and those in use at the end of
	// the frame, or with p_keep_in_use, lets those in use leave the pool, and live on.
	void clear(bool p_keep_in_use) {
		std::vector<T *> objects;
		{
			std::lock_guard<std::mutex> lock(mutex_);
			objects.swap(owned_);
			alive_ -= int64_t(objects.size()); // Objects that take or reserve is making still count.
			warn_at_ = size_;
			last_ = &first_;
			count_ = 0;
			for (T *object : objects) {
				object->_gdpp_pool_slot.owned = false;
			}
		}
		for (T *object : objects) {
			if (std::exchange(object->_gdpp_pool_slot.cell, nullptr)) {
				memdelete(object);
			} else if (!p_keep_in_use) {
				object->queue_free();
			}
		}
	}

private:
	static constexpr int64_t CHUNK_SIZE = 64;
	struct Chunk {
		T *items[CHUNK_SIZE];
		Chunk *prev = nullptr;
		Chunk *next = nullptr;
	};

	// hook makes the library's unloading free the resting objects, and in debug builds adds the pool's monitors. The
	// caller holds the lock.
	void hook() {
		if (!hooked_) {
			hooked_ = true;
			on_unload([this] { trim(0); });
#ifdef DEBUG_ENABLED
			callable_mp_static(&Pool::monitor).call_deferred(); // On the main thread, which owns the monitors.
#endif
		}
	}

#ifdef DEBUG_ENABLED
	// monitor adds the pool's monitors to the debugger, until the library is unloaded: how many objects the pool made
	// that aren't freed, how many of them are in the scene tree, and how many are orphan nodes, out of it. They count
	// only when the debugger asks.
	static void monitor() {
		String name = String("GD++ Object Pools/") + T::get_class_static();
		for (const auto &[id, count] : { std::pair{ name + " (total)", &Pool::total }, std::pair{ name + " (active)", &Pool::active },
					 std::pair{ name + " (orphan)", &Pool::orphan } }) {
			if (!Performance::get_singleton()->has_custom_monitor(id)) {
				Performance::get_singleton()->add_custom_monitor(id, callable_mp_static(count));
				on_unload([id] {
					if (Performance::get_singleton()->has_custom_monitor(id)) {
						Performance::get_singleton()->remove_custom_monitor(id);
					}
				});
			}
		}
	}

	// total returns how many objects the pool of T made that aren't freed, resting or in use.
	static int64_t total() {
		std::lock_guard<std::mutex> lock(T::_gdpp_pool.mutex_);
		return T::_gdpp_pool.alive_;
	}

	// active returns how many objects the pool of T made are in the scene tree.
	static int64_t active() {
		std::lock_guard<std::mutex> lock(T::_gdpp_pool.mutex_);
		return T::_gdpp_pool.in_tree();
	}

	// orphan returns how many objects the pool of T made are orphan nodes, out of the scene tree: the resting ones,
	// and those in use out of the tree.
	static int64_t orphan() {
		std::lock_guard<std::mutex> lock(T::_gdpp_pool.mutex_);
		return T::_gdpp_pool.alive_ - T::_gdpp_pool.in_tree();
	}

	// in_tree returns how many objects the pool made are in the scene tree. The caller holds the lock.
	int64_t in_tree() const {
		return std::count_if(owned_.begin(), owned_.end(), [](T *p_object) { return p_object->is_inside_tree(); });
	}
#endif

	// admit reports whether the pool may make one more object, and counts it if so. The caller holds the lock.
	bool admit() {
		if (alive_ >= size_ && mode_ == PoolMode::FIXED) {
			return false;
		}
		alive_++;
#ifdef DEBUG_ENABLED
		if (size_ > 0 && alive_ > warn_at_) {
			ERR_PRINT(vformat("GD++ object pool for class `%s` grew past %d objects.", T::get_class_static(), warn_at_));
			warn_at_ *= 2;
		}
#endif
		return true;
	}

	// room reports whether reserve must make another object to reach p_count, and counts it if so. It prints an error
	// when the pool's size stops it.
	bool room(int64_t p_count) {
		std::lock_guard<std::mutex> lock(mutex_);
		if (alive_ >= p_count) {
			return false;
		}
		if (!admit()) {
			ERR_PRINT(vformat("GD++ object pool for class `%s` can't reserve %d objects, since its size is %d.", T::get_class_static(), p_count, size_));
			return false;
		}
		return true;
	}

	// adopt makes a new object, which admit counted, and adds it to the objects the pool made, resting if p_rest. It
	// returns null if the object can't be made.
	T *adopt(bool p_rest) {
		T *object = make<T>();
		std::lock_guard<std::mutex> lock(mutex_);
		if (!object) {
			alive_--;
			return nullptr;
		}
		PoolSlot<T> &slot = object->_gdpp_pool_slot;
		slot.owned = true;
		slot.index = int64_t(owned_.size());
		owned_.push_back(object);
		if (p_rest) {
			slot.given = true;
			push(object);
		}
		return object;
	}

	// pop removes the last resting object and returns it, or null if there's none.
	T *pop() {
		if (count_ == 0) {
			if (!last_->prev) {
				return nullptr;
			}
			last_ = last_->prev;
			count_ = CHUNK_SIZE;
		}
		T *object = last_->items[--count_];
		object->_gdpp_pool_slot.cell = nullptr;
		object->_gdpp_pool_slot.given = false;
		return object;
	}

	// push adds p_object to the resting objects.
	void push(T *p_object) {
		if (count_ == CHUNK_SIZE) {
			if (!last_->next) {
				last_->next = new Chunk;
				last_->next->prev = last_;
			}
			last_ = last_->next;
			count_ = 0;
		}
		T **cell = &last_->items[count_++];
		*cell = p_object;
		p_object->_gdpp_pool_slot.cell = cell;
	}

	// trim frees resting objects until the pool has p_count objects, or none rests. Each one's destructor forgets it.
	void trim(int64_t p_count) {
		while (T *object = excess(p_count)) {
			memdelete(object);
		}
	}

	// excess takes the last resting object out of the pool, for trim to free, if the pool has more than p_count
	// objects, or returns null.
	T *excess(int64_t p_count) {
		std::lock_guard<std::mutex> lock(mutex_);
		if (alive_ <= p_count) {
			return nullptr;
		}
		T *object = pop();
		if (object) {
			object->_gdpp_pool_slot.given = true; // So that its destructor skips the @recycle dtor, which already ran.
		}
		return object;
	}

	std::mutex mutex_;
	int64_t size_;
	PoolMode mode_;
	int64_t warn_at_; // With GROW, the number of objects past which it next prints an error.
	bool hooked_ = false; // Whether trim runs on unload.
	int64_t alive_ = 0; // The objects it made that aren't freed, resting or in use.
	std::vector<T *> owned_; // The objects it made that aren't freed, resting or in use.
	Chunk first_;
	Chunk *last_ = &first_; // The chunk of the last resting object, or the first chunk if there's none.
	int64_t count_ = 0; // The resting objects in last_.
};

// has_pool<T> is true for the @pool class T, but not for classes that extend it.
template <typename T, typename = void>
struct has_pool : std::false_type {};
template <typename T>
struct has_pool<T, std::void_t<decltype(T::_gdpp_pool)>> : std::is_same<decltype(T::_gdpp_pool), Pool<T>> {};

// is_extern<T> is true for externs.
template <typename T, typename = void>
struct is_extern : std::false_type {};
template <typename T>
struct is_extern<T, std::void_t<decltype(T::gdpp_name)>> : std::true_type {};

// always_false<T> is false for any T, for a static_assert that only fails when a template is used.
template <typename>
inline constexpr bool always_false = false;

// Abstract<T> is the type of the @abstract class T's _gdpp_abstract.
template <typename T>
struct Abstract {};

// has_abstract<T> is true for the @abstract class T, but not for classes that extend it.
template <typename T, typename = void>
struct has_abstract : std::false_type {};
template <typename T>
struct has_abstract<T, std::void_t<decltype(T::_gdpp_abstract)>> : std::is_same<std::remove_cv_t<decltype(T::_gdpp_abstract)>, Abstract<T>> {};

// create creates an object of the class T, which `create T` calls: it takes one from T's pool for a @pool class, and
// returns an Ext<T> for an extern, a Ref<T> for a refcounted class, and a T * otherwise, an instance of T's scene for
// a @scene class.
template <typename T>
auto create() {
	static_assert(!has_abstract<T>::value, "Abstract classes can't be created. Create a subclass instead.");
	if constexpr (has_pool<T>::value) {
		return T::_gdpp_pool.take();
	} else if constexpr (is_extern<T>::value) {
		return create_ext<T>();
	} else if constexpr (std::is_base_of_v<RefCounted, T>) {
		return Ref<T>(memnew(T));
	} else {
		return make<T>();
	}
}

// destroy deletes an object, see below.
template <typename T>
void destroy(T *p_object);
// destroy deletes an object of an extern, see below.
template <typename T>
void destroy(ExtPtr<T> p_object);

// Weak<T> is the C++ type of Weak[T]: a reference to an object of the class T that doesn't keep it alive, and knows
// when it's gone. It holds the object's ID, so it's safe to keep after the object is freed, and to share between
// threads. It converts to a strong_t<T>, or anything that converts from one: a Ref<T>, which keeps the object alive, or
// a T *, which doesn't. Both are null once the object is freed, and for a @pool class, also once it's given back to its
// pool, even though the object lives on there. Where a conversion is ambiguous, ptr() and ref() give the same. Weaks
// equal when they refer to the same object, or are both null.
template <typename T>
class Weak {
public:
	// A null Weak.
	Weak() = default;
	// Refers to p_object, or is null if it's null.
	Weak(const T *p_object) {
		if (p_object) {
			id_ = p_object->get_instance_id();
			if constexpr (has_pool<T>::value) {
				generation_ = p_object->_gdpp_pool_slot.generation;
			}
		}
	}
	// Refers to the object of p_object, or is null if it's null.
	template <typename U>
	Weak(const Ref<U> &p_object) :
			Weak(p_object.ptr()) {}

	// ptr returns the object, or null once it's gone. It doesn't keep a refcounted object alive: use ref for that.
	T *ptr() const {
		T *object = Object::cast_to<T>(ObjectDB::get_instance(id_));
		if constexpr (has_pool<T>::value) {
			if (object && object->_gdpp_pool_slot.generation != generation_) {
				return nullptr;
			}
		}
		return object;
	}
	// ref returns the object of a refcounted class, which it keeps alive, or null once it's gone.
	Ref<T> ref() const {
		static_assert(std::is_base_of_v<RefCounted, T>, "Only a Weak of a refcounted class has ref(). Use ptr().");
		return Ref<T>(ptr());
	}

	// The template parameter U delays strong_t<T> until T is complete, so that a class can hold a Weak of itself.
	template <typename R, typename U = T, std::enable_if_t<!std::is_same_v<R, bool> && std::is_convertible_v<strong_t<U>, R>, int> = 0>
	operator R() const { return strong_t<U>(ptr()); }
	// True while the object is there.
	explicit operator bool() const { return object_ptr(strong_t<T>(ptr())) != nullptr; }

	// Templates, so that comparing with a pointer or a Ref matches them exactly, rather than the built-in ==.
	template <typename P>
	friend bool operator==(const Weak &p_a, const P &p_b) {
		Weak b(p_b);
		return p_a.id_ == b.id_ && p_a.generation_ == b.generation_;
	}
	// The same, with the Weak on the right.
	template <typename P, std::enable_if_t<!std::is_same_v<P, Weak>, int> = 0>
	friend bool operator==(const P &p_a, const Weak &p_b) { return p_b == p_a; }

private:
	uint64_t id_ = 0;
	uint64_t generation_ = 0;
};

// main_thread is the main thread, which owns the scene tree, and loads the library.
inline const std::thread::id main_thread = std::this_thread::get_id();

// on_main_thread reports whether the calling thread is the main thread.
inline bool on_main_thread() {
	return std::this_thread::get_id() == main_thread;
}

// destroy_now does what destroy does, on the calling thread, which must be allowed to change the scene tree.
template <typename T>
void destroy_now(T *p_object) {
	if (!p_object) {
		return;
	}
	if constexpr (has_pool<T>::value) {
		if (p_object->_gdpp_pool_slot.owned) {
			T::_gdpp_pool.give(p_object);
			return;
		}
	}
	memdelete(p_object);
}
// destroy_now of an extern deletes its object.
template <typename T>
void destroy_now(ExtPtr<T> p_object) {
	if (p_object) {
		memdelete(p_object.base());
	}
}

// destroy_later destroys the object of ID p_id, unless it's gone, once the main thread gets to it. P is a pointer to
// it. For a @pool class, it also leaves the object alone if it was given back to its pool since its generation
// p_generation.
template <typename P>
void destroy_later(uint64_t p_id, uint64_t p_generation) {
	if constexpr (std::is_pointer_v<P>) {
		using T = std::remove_pointer_t<P>;
		T *object = Object::cast_to<T>(ObjectDB::get_instance(p_id));
		if constexpr (has_pool<T>::value) {
			if (object && object->_gdpp_pool_slot.generation != p_generation) {
				return;
			}
		}
		destroy_now(object);
	} else {
		destroy_now(P(Object::cast_to<std::remove_pointer_t<decltype(std::declval<P>().base())>>(ObjectDB::get_instance(p_id))));
	}
}

// destroy_deferred schedules destroy_later for p_object, of type P.
template <typename P>
void destroy_deferred(P p_object) {
	uint64_t generation = 0;
	if constexpr (has_pool<std::remove_pointer_t<P>>::value) {
		generation = p_object->_gdpp_pool_slot.generation;
	}
	callable_mp_static(&destroy_later<P>).call_deferred(uint64_t(object_ptr(p_object)->get_instance_id()), generation);
}

// defer_destroy reports whether destroy must leave p_object, of type P, to the main thread: this is another thread,
// and it's a node in the scene tree, which only the main thread may change. Then it schedules destroy_later there.
template <typename P>
bool defer_destroy(P p_object) {
	if (on_main_thread()) {
		return false;
	}
	Node *node = Object::cast_to<Node>(object_ptr(p_object));
	if (!node || !node->is_inside_tree()) {
		return false;
	}
	destroy_deferred(p_object);
	return true;
}

// destroy deletes an object, which `destroy x` calls: it gives an object that a pool made back to the pool, and
// deletes others. It does nothing for null. It's thread-safe: on other threads than the main one, it leaves nodes in
// the scene tree to the main thread, which destroys them at the end of the frame. Refcounted objects free themselves,
// so it doesn't take them. Destroying an object twice is a bug, except for an object that a pool made, which it keeps.
// For an extern with @pool, it calls the object's method gdpp_destroy, which does all this in the object's own package.
template <typename T>
void destroy(T *p_object) {
	if constexpr (std::is_base_of_v<Object, T>) {
		if (p_object && defer_destroy(p_object)) {
			return;
		}
	}
	destroy_now(p_object);
}
// destroy of an extern: for one with @pool, it calls the object's method gdpp_destroy, else it deletes the object like
// above.
template <typename T>
void destroy(ExtPtr<T> p_object) {
	if constexpr (has_ext_pool<T>()) {
		if (p_object) {
			p_object.base()->call(GDPP_STRING_NAME("gdpp_destroy")); // Thread-safe, like destroy.
		}
	} else if (p_object && !defer_destroy(p_object)) {
		destroy_now(p_object);
	}
}

// queue_destroy destroys a node at the end of the frame, on the main thread, like queue_free, which `queue_destroy x`
// calls. For a @pool class, it returns the node to its pool then, unless it was returned or freed before, even if the
// pool has reused it since. For other classes, it's queue_free, which also does nothing for a node freed before. It only
// works on nodes, from any thread, and does nothing for null. For an extern with @pool, it calls the object's method
// gdpp_queue_destroy.
template <typename T>
void queue_destroy(T *p_object) {
	static_assert(std::is_base_of_v<Node, T>, "queue_destroy only works on nodes. Use destroy for other objects.");
	if (!p_object) {
		return;
	}
	if constexpr (has_pool<T>::value) {
		destroy_deferred(p_object);
	} else {
		p_object->queue_free();
	}
}
// queue_destroy of an extern: for one with @pool, it calls the object's method gdpp_queue_destroy, else queue_free.
template <typename T>
void queue_destroy(ExtPtr<T> p_object) {
	static_assert(std::is_base_of_v<Node, typename T::Base>, "queue_destroy only works on nodes. Use destroy for other objects.");
	if (!p_object) {
		return;
	}
	if constexpr (has_ext_pool<T>()) {
		p_object.base()->call(GDPP_STRING_NAME("gdpp_queue_destroy"));
	} else {
		p_object.base()->queue_free();
	}
}
// queue_destroy of a Ref doesn't compile: refcounted objects free themselves.
template <typename T>
void queue_destroy(const Ref<T> &) {
	static_assert(always_false<T>, "Refcounted objects free themselves when their last reference goes away.");
}
// queue_destroy of an ExtRef doesn't compile: refcounted objects free themselves.
template <typename T>
void queue_destroy(const ExtRef<T> &) {
	static_assert(always_false<T>, "Refcounted objects free themselves when their last reference goes away.");
}
// destroy of a Ref doesn't compile: refcounted objects free themselves.
template <typename T>
void destroy(const Ref<T> &) {
	static_assert(always_false<T>, "Refcounted objects free themselves when their last reference goes away.");
}
// destroy of an ExtRef doesn't compile: refcounted objects free themselves.
template <typename T>
void destroy(const ExtRef<T> &) {
	static_assert(always_false<T>, "Refcounted objects free themselves when their last reference goes away.");
}

// now_usec returns the steady clock's time in microseconds.
inline int64_t now_usec() {

	return std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::steady_clock::now().time_since_epoch()).count();
}

// is_cancelled reports whether the task running on this thread should stop: its Async was cancelled, or the game is
// quitting. Outside of tasks, it reports whether the game is quitting. It's cheap, so long bodies can check it often.
inline bool is_cancelled() {
	return quitting.load(std::memory_order_relaxed) || (current_cancel() && current_cancel()->load(std::memory_order_relaxed));
}

// begin_quit starts the quit timeout, once.
inline void begin_quit() {
	if (!quitting.exchange(true)) {
		quit_deadline_usec = now_usec() + GDPP_QUIT_TIMEOUT_USEC;
	}
}

// watch_quit makes the root window call begin_quit when it leaves the tree, which is when the game starts quitting,
// before any node is freed. It runs on the main thread.
inline void watch_quit() {
	SceneTree *tree = Object::cast_to<SceneTree>(Engine::get_singleton()->get_main_loop());
	if (tree && tree->get_root()) {
		connect_until_unload(tree->get_root(), "tree_exiting", callable_mp_static(&begin_quit));
	}
}

// await_quit waits until p_done returns true. While the game quits, in games, it ends the game when the quit
// timeout runs out, since a running task can't be stopped otherwise. The editor waits for as long as it takes.
template <typename F>
void await_quit(F p_done) {
	bool game = !Engine::get_singleton()->is_editor_hint();
	while (!p_done()) {
		if (game && now_usec() >= quit_deadline_usec.load()) {
			std::fprintf(stderr, "GD++: %lld tasks were still running when the quit timeout ran out, so the game exits now.\n",
					static_cast<long long>(running_tasks.load()));
			std::fflush(stderr);
			std::_Exit(0);
		}
		std::this_thread::sleep_for(std::chrono::milliseconds(1));
	}
}

// finish_tasks waits for the package's running tasks, before its library is unloaded, within the quit timeout.
inline void finish_tasks() {
	begin_quit();
	await_quit([] { return running_tasks.load() == 0; });
}

// uninitialize prepares the package's library to be unloaded: it waits for the package's running tasks, and removes
// its hooks. The package's generated registration code calls it.
inline void uninitialize() {
	finish_tasks();
	std::lock_guard<std::mutex> lock(unhooks_mutex);
	for (const std::function<void()> &unhook : unhooks) {
		unhook();
	}
	unhooks.clear();
}

// TaskCallable is a Callable that runs a function once, returns its result, and then frees it.
class TaskCallable : public CallableCustom {
public:
	// A Callable that runs p_run.
	explicit TaskCallable(std::function<Variant()> p_run) :
			run(std::move(p_run)) {}

	// The address: each TaskCallable is only equal to itself.
	uint32_t hash() const override { return uint32_t(uintptr_t(this)); }
	// "gdpp::TaskCallable".
	String get_as_text() const override { return "gdpp::TaskCallable"; }
	// Compares addresses.
	CompareEqualFunc get_compare_equal_func() const override {
		return [](const CallableCustom *p_a, const CallableCustom *p_b) { return p_a == p_b; };
	}
	// Orders by address.
	CompareLessFunc get_compare_less_func() const override {
		return [](const CallableCustom *p_a, const CallableCustom *p_b) { return p_a < p_b; };
	}
	// Always true.
	bool is_valid() const override { return true; }
	// None: it isn't bound to an object.
	ObjectID get_object() const override { return ObjectID(); }
	// call runs the body, once, and returns its result. It takes no arguments.
	void call(const Variant **p_arguments, int p_argcount, Variant &r_return_value, GDExtensionCallError &r_call_error) const override {
		r_return_value = run();
		run = nullptr;
		r_call_error.error = GDEXTENSION_CALL_OK;
	}

private:
	mutable std::function<Variant()> run;
};

#define GDPP_GDCLASS(m_class, m_inherits) GDCLASS(m_class, m_inherits) // Expands m_class before GDCLASS quotes it.

// GDPP_ASYNC_CLASS is the package's class of tasks, which Async types name: a job that runs on the WorkerThreadPool,
// e.g. the body of an @onthread function, and its result once done. It's thread-safe. GD++ code calls its methods
// directly, and those of other packages' classes of tasks by name, so it works with their tasks too. The package registers it, if it has GD++ classes.
class GDPP_ASYNC_CLASS : public RefCounted {
	GDPP_GDCLASS(GDPP_ASYNC_CLASS, RefCounted)

public:
	// is_done reports whether the job has finished, and its result hasn't been claimed.
	bool is_done() const { return done.load(std::memory_order_acquire) && !claimed.load(std::memory_order_relaxed); }

	// is_valid reports whether the result hasn't been claimed: the job is running or done. It matches testing a
	// gdpp::Async as a bool.
	bool is_valid() const { return !claimed.load(std::memory_order_relaxed); }

	// claim returns the result of the finished job, and lets go of it: the task isn't done any more, like an empty
	// Async. The job must be done, and not claimed yet: debug builds check it, release builds don't.
	Variant claim() {
#ifdef DEBUG_ENABLED
		ERR_FAIL_COND_V_MSG(claimed.load(), Variant(), "The task holds no result: it's new, or its result has been claimed already.");
		ERR_FAIL_COND_V_MSG(!is_done(), Variant(), "The task isn't done yet. Check is_done() before claim(), or call wait().");
#endif
		join();
		if (claimed.exchange(true)) {
			return Variant(); // Another thread claimed it at the same time.
		}
		Variant value = result;
		result = Variant();
		return value;
	}

	// wait waits for the job to finish, and returns its result.
	Variant wait() {
		join();
		return get_result();
	}

	// get_result returns the result. The job must be done: debug builds check it, release builds don't.
	Variant get_result() const {
#ifdef DEBUG_ENABLED
		ERR_FAIL_COND_V_MSG(claimed.load(), Variant(), "The task holds no result: it's new, or its result has been claimed already.");
		ERR_FAIL_COND_V_MSG(!is_done(), Variant(), "The task isn't done yet. Check is_done() before get_result(), or call wait().");
#endif
		return result;
	}

	// cancel asks the job to stop: gdpp::is_cancelled() is true in it from now on.
	void cancel() { cancel_requested.store(true, std::memory_order_relaxed); }

	// start runs p_job on the WorkerThreadPool, as the task named p_name. If p_detached, nothing waits for the task:
	// once the job is done, the main thread waits for it, so the task can be dropped while it runs, without blocking.
	void start(const Callable &p_job, const String &p_name, bool p_detached = false) {
#ifdef DEBUG_ENABLED
		ERR_FAIL_COND_MSG(id >= 0, "The task has already started.");
#endif
		job = p_job;
		detached = p_detached;
		running = Ref<RefCounted>(this);
		claimed.store(false, std::memory_order_relaxed); // Before the task starts, and before other threads see the object.
		id = WorkerThreadPool::get_singleton()->add_task(callable_mp(this, &GDPP_ASYNC_CLASS::run), false, p_name);
	}

	// Waits for the job to finish, if nothing else does.
	~GDPP_ASYNC_CLASS() { join(); }

protected:
	static void _bind_methods() {
		ClassDB::bind_method(D_METHOD("is_done"), &GDPP_ASYNC_CLASS::is_done);
		ClassDB::bind_method(D_METHOD("is_valid"), &GDPP_ASYNC_CLASS::is_valid);
		ClassDB::bind_method(D_METHOD("wait"), &GDPP_ASYNC_CLASS::wait);
		ClassDB::bind_method(D_METHOD("get_result"), &GDPP_ASYNC_CLASS::get_result);
		ClassDB::bind_method(D_METHOD("claim"), &GDPP_ASYNC_CLASS::claim);
		ClassDB::bind_method(D_METHOD("cancel"), &GDPP_ASYNC_CLASS::cancel);
		// Read-only. result isn't for the inspector or the debugger, which would read it before the job is done.
		ClassDB::add_property(get_class_static(), PropertyInfo(Variant::BOOL, "done", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_EDITOR | PROPERTY_USAGE_READ_ONLY),
				"", "is_done");
		ClassDB::add_property(get_class_static(), PropertyInfo(Variant::NIL, "result", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_NIL_IS_VARIANT),
				"", "get_result");
		ClassDB::add_property(get_class_static(), PropertyInfo(Variant::BOOL, "valid", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_EDITOR | PROPERTY_USAGE_READ_ONLY),
				"", "is_valid");
	}

private:
	int64_t id = -1;
	Callable job;
	Ref<RefCounted> running; // Keeps the object alive while the job runs.
	Variant result; // Set before done.
	std::atomic<bool> done = false;
	std::atomic<bool> cancel_requested = false;
	bool detached = false; // Whether the task waits for itself, through the main thread, instead of its holders.
	std::atomic<bool> claimed = true; // Whether claim took the result. Until started: an object that runs nothing, e.g. from new(), holds nothing.
	std::mutex mutex;
	bool waited = false; // Godot requires waiting for each task once.

	void run() {
		running_tasks.fetch_add(1);
		current_cancel() = &cancel_requested;
		result = job.call();
		current_cancel() = nullptr;
		job = Callable(); // Frees what the job holds, e.g. the object it was called on.
		done.store(true, std::memory_order_release);
		if (detached) {
			// The main thread waits for the task, since nothing else does. Its id comes from the pool, since start may not
			// have stored it yet. Before the last reference, maybe this one, is dropped, so the destructor doesn't wait.
			std::lock_guard<std::mutex> lock(mutex);
			waited = true;
			callable_mp_static(&GDPP_ASYNC_CLASS::join_task).call_deferred(WorkerThreadPool::get_singleton()->get_caller_task_id());
		}
		Ref<RefCounted> self = running;
		running.unref();
		self.unref(); // May free this object, whose destructor then runs in this task.
		running_tasks.fetch_sub(1);
	}

	void join() {
		std::lock_guard<std::mutex> lock(mutex);
		if (waited || id < 0) {
			return;
		}
		waited = true;
		WorkerThreadPool *pool = WorkerThreadPool::get_singleton();
		if (pool->get_caller_task_id() == id) {
			// A task can't wait for itself, so the main thread waits for it once it's done.
			callable_mp_static(&GDPP_ASYNC_CLASS::join_task).call_deferred(id);
			return;
		}
		if (quitting.load()) {
			await_quit([&] { return pool->is_task_completed(id); });
		}
		pool->wait_for_task_completion(id);
	}

	static void join_task(int64_t p_id) {
		WorkerThreadPool::get_singleton()->wait_for_task_completion(p_id);
	}
};

// Async<T> is the C++ type of Async[T]: a task, whose result has type T, e.g. the call of an @onthread function,
// which runs on the WorkerThreadPool. It references an object of the package's class of tasks, and calls its
// methods by name, so it works with the tasks of other packages too. Copies share the task, like references to the
// task object in scripts, and each method does what the object's method of the same name does: claiming through one
// copy claims the task for all of them. A new Async is empty: it's false, like a claimed one, and destroying it does
// nothing. When the last reference to a task is gone, the task object waits for the task to finish, unless it
// already has. It's [[nodiscard]], so compilers warn about a call of an @onthread function whose task is dropped right
// away, which would wait for it.
template <typename T>
class [[nodiscard]] Async {
public:
	// An empty Async.
	Async() = default;
	// An Async of p_task, an object of a class of tasks, of this package or another one.
	explicit Async(const Ref<RefCounted> &p_task) :
			task(p_task), own(Object::cast_to<GDPP_ASYNC_CLASS>(p_task.ptr())) {}

	// An Async is true while its task is running or done, and false once it's claimed, or when it's empty.
	explicit operator bool() const { return task.is_valid() && (own ? own->is_valid() : task->call(GDPP_STRING_NAME("is_valid")).operator bool()); }

	// is_done reports whether the task has finished, and its result hasn't been claimed. It's false while the task
	// runs, once it's claimed, and for an empty Async.
	bool is_done() const { return task.is_valid() && (own ? own->is_done() : task->call(GDPP_STRING_NAME("is_done")).operator bool()); }

	// claim returns the result of a done task, and lets go of it: the task is claimed, for every copy. The task must
	// be done, and not claimed yet: debug builds check it, and print an error and return the default value if not.
	// Release builds don't check it.
	T claim() const { return call(GDPP_STRING_NAME("claim"), &GDPP_ASYNC_CLASS::claim); }

	// result returns the result of a done task, and keeps it, unlike claim. The task must be done, and not claimed
	// yet, like for claim.
	T result() const { return call(GDPP_STRING_NAME("get_result"), &GDPP_ASYNC_CLASS::get_result); }

	// wait waits for the task to finish, and returns its result, which it keeps, like result. The task must not be
	// claimed yet, like for claim.
	T wait() const { return call(GDPP_STRING_NAME("wait"), &GDPP_ASYNC_CLASS::wait); }

	// cancel asks the task to stop: gdpp::is_cancelled() is true in its body from now on. It's up to the body to check it,
	// and return early. The task's result is still claimed, or dropped, as usual. It's always safe: for an empty Async,
	// or a task that's done or claimed, it does nothing.
	void cancel() {
		if (own) {
			own->cancel();
		} else if (task.is_valid()) {
			task->call(GDPP_STRING_NAME("cancel"));
		}
	}

	// task is the object of the class of tasks, or null for an empty Async.
	const Ref<RefCounted> &object() const { return task; }
	// The object of the class of tasks, as a Variant.
	operator Variant() const { return task; }

private:
	Ref<RefCounted> task; // Null for an empty Async, which touches nothing, not even when destroyed.
	// own is task, if it's of this package's class of tasks, whose methods it then calls directly, without the engine.
	// It's null for the tasks of other packages, whose methods it calls by name.
	GDPP_ASYNC_CLASS *own = nullptr;

	// call calls the task object's method p_method, p_own_method if it's own, and converts its result to T.
	template <typename M>
	T call(const StringName &p_method, M p_own_method) const {
#ifdef DEBUG_ENABLED
		if (task.is_null()) {
			ERR_PRINT("There is no task: the Async is empty.");
			return T();
		}
#endif
		Variant value = own ? (own->*p_own_method)() : task->call(p_method);
		if constexpr (!std::is_void_v<T>) {
			return value.get_type() == Variant::NIL ? T() : cast<T>(value);
		}
	}
};

// run_task starts the call of an @onthread function on the WorkerThreadPool, as the task named p_name (e.g.
// "Player.find_path"), and returns its Async. p_job calls the function's body. If p_self, the object the function is
// called on, is refcounted, the task keeps it alive until the body has run. If p_detached, the caller can drop the
// Async right away: once the body is done, the task schedules a deferred wait for itself.
template <typename F>
auto run_task(const Object *p_self, const char *p_name, F p_job, bool p_detached = false) -> Async<std::invoke_result_t<F>> {
	using R = std::invoke_result_t<F>;
	if (!watching_quit.exchange(true)) {
		callable_mp_static(&watch_quit).call_deferred(); // On the main thread, which owns the scene tree.
	}
	Ref<GDPP_ASYNC_CLASS> task;
	task.instantiate();
	Ref<RefCounted> self = Object::cast_to<RefCounted>(const_cast<Object *>(p_self));
	// A variable, since memnew puts its argument in a decltype, where C++17 doesn't allow a lambda.
	auto run = [self, p_job]() -> Variant {
		if constexpr (std::is_void_v<R>) {
			p_job();
			return Variant();
		} else if constexpr (std::is_enum_v<R>) {
			return static_cast<int64_t>(p_job());
		} else {
			return Variant(p_job());
		}
	};
	Callable job(memnew(TaskCallable(std::move(run))));
	task->start(job, p_name, p_detached);
	return Async<R>(Ref<RefCounted>(task.ptr()));
}

// run_detached starts the call of an @onthread("detached") function, like run_task, but returns nothing: nothing waits
// for the task, which schedules a deferred wait for itself once the body is done.
template <typename F>
void run_detached(const Object *p_self, const char *p_name, F p_job) {
	static_cast<void>(run_task(p_self, p_name, std::move(p_job), true));
}

// Masked is what & returns for a bitfield E: it converts to E, and tests as true if any flag is set, so
// if (mask & Layer::ENEMY) works.
template <typename E>
struct Masked {
	// The flags that are set in both.
	E value;
	// The flags, as the enum.
	constexpr operator E() const { return value; }
	// True if any flag is set.
	constexpr explicit operator bool() const { return static_cast<int64_t>(value) != 0; }

};

} // namespace gdpp

// The runtime's names for user code, which writes them without a prefix. Generated code spells them gdpp::.
using gdpp::Async;
using gdpp::Emitted;
using gdpp::Ext;
using gdpp::ExtPtr;
using gdpp::ExtRef;
using gdpp::Weak;

// GDPP_SIGNATURE is the signature of the function it's in, e.g. "int Player::fire(int)", on the compilers that have one.
#if defined(__GNUC__) || defined(__clang__)
#define GDPP_SIGNATURE __PRETTY_FUNCTION__
#elif defined(_MSC_VER)
#define GDPP_SIGNATURE __FUNCSIG__
#endif

// GDPP_ASSERT is what `assert condition;` becomes: in debug builds, a failed condition prints an error and returns from
// the function, with T() in one that returns a T, and a lasting T() in one that returns a T &. It tells them apart by
// GDPP_SIGNATURE, and without one, doesn't compile. GDPP_ASSERT_VOID, GDPP_ASSERT_VALUE and GDPP_ASSERT_REFERENCE do
// the same in code where GD++ knows the function's return type, and
// GDPP_ASSERT_DEDUCED doesn't compile, since no return does in a function whose return type C++ deduces from its value.
// The error has no function name, since that of generated code, e.g. `_gdpp_body__ready` or a lambda's, would
// confuse. With GDPP_TRACING, the error is also a trace line, see below. Release builds don't evaluate the condition.
#define GDPP_TRACE_ASSERT(m_text) ((void)0)
#ifdef DEBUG_ENABLED
#define GDPP_ASSERT_(m_text, m_exit, ...) \
	if (!(__VA_ARGS__)) { \
		::godot::_err_print_error("", __FILE__, __LINE__, gdpp::assert_message(m_text)); \
		GDPP_TRACE_ASSERT(m_text); \
		m_exit; \
	} else \
		((void)0)
#else
#define GDPP_ASSERT_(m_text, m_exit, ...) \
	if constexpr (false) { \
		(void)(__VA_ARGS__); \
	} else \
		((void)0)
#endif
#ifdef GDPP_SIGNATURE
// The parentheses keep the comma from splitting GDPP_ASSERT_'s arguments.
#define GDPP_ASSERT(m_text, ...) GDPP_ASSERT_(m_text, return (gdpp::assert_return<gdpp::returns_void(GDPP_SIGNATURE), gdpp::returns_reference(GDPP_SIGNATURE)>()), __VA_ARGS__)
#else
#define GDPP_ASSERT(m_text, ...) static_assert(false, "GD++ can't tell what this function returns on this compiler, so assert can't return from it. Write assert_void or assert_val instead.")
#endif
#define GDPP_ASSERT_VOID(m_text, ...) GDPP_ASSERT_(m_text, return, __VA_ARGS__)
#define GDPP_ASSERT_VALUE(m_text, ...) GDPP_ASSERT_(m_text, return gdpp::Default{}, __VA_ARGS__)
#define GDPP_ASSERT_REFERENCE(m_text, ...) GDPP_ASSERT_(m_text, return gdpp::DefaultRef{}, __VA_ARGS__)
#define GDPP_ASSERT_DEDUCED(m_text, ...) static_assert(false, "C++ deduces this function's return type from its returns, so assert can't return from it. Write the return type, e.g. `-> int` for a lambda.")

namespace godot {

// Bindings see an extern as its base class. The hint names the extern, so the editor only accepts matching objects.

template <typename T>
struct GetTypeInfo<gdpp::ExtPtr<T>> {
	static constexpr GDExtensionVariantType VARIANT_TYPE = GDEXTENSION_VARIANT_TYPE_OBJECT;
	static constexpr GDExtensionClassMethodArgumentMetadata METADATA = GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE;
	static inline PropertyInfo get_class_info() {
		PropertyHint hint = std::is_base_of_v<Node, typename T::Base> ? PROPERTY_HINT_NODE_TYPE : PROPERTY_HINT_NONE;
		return PropertyInfo(Variant::OBJECT, "", hint, T::gdpp_name, PROPERTY_USAGE_DEFAULT, T::Base::get_class_static());
	}
};

template <typename T>
struct GetTypeInfo<gdpp::ExtRef<T>> {
	static constexpr GDExtensionVariantType VARIANT_TYPE = GDEXTENSION_VARIANT_TYPE_OBJECT;
	static constexpr GDExtensionClassMethodArgumentMetadata METADATA = GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE;
	static inline PropertyInfo get_class_info() {
		PropertyHint hint = std::is_base_of_v<Resource, typename T::Base> ? PROPERTY_HINT_RESOURCE_TYPE : PROPERTY_HINT_NONE;
		return PropertyInfo(Variant::OBJECT, "", hint, T::gdpp_name, PROPERTY_USAGE_DEFAULT, T::Base::get_class_static());
	}
};

template <typename T>
struct PtrToArg<gdpp::ExtPtr<T>> {
	_FORCE_INLINE_ static gdpp::ExtPtr<T> convert(const void *p_ptr) {
		return PtrToArg<typename T::Base *>::convert(p_ptr);
	}
	typedef Object *EncodeT;
	_FORCE_INLINE_ static void encode(gdpp::ExtPtr<T> p_val, void *p_ptr) {
		PtrToArg<typename T::Base *>::encode(p_val.base(), p_ptr);
	}
};

template <typename T>
struct PtrToArg<gdpp::ExtRef<T>> {
	_FORCE_INLINE_ static gdpp::ExtRef<T> convert(const void *p_ptr) {
		return PtrToArg<Ref<typename T::Base>>::convert(p_ptr);
	}
	typedef Ref<typename T::Base> EncodeT;
	_FORCE_INLINE_ static void encode(gdpp::ExtRef<T> p_val, void *p_ptr) {
		PtrToArg<Ref<typename T::Base>>::encode(p_val.base(), p_ptr);
	}
};

template <typename T>
struct VariantCaster<gdpp::ExtPtr<T>> {
	static _FORCE_INLINE_ gdpp::ExtPtr<T> cast(const Variant &p_variant) {
		return Object::cast_to<typename T::Base>(p_variant.operator Object *());
	}
};

template <typename T>
struct VariantCaster<gdpp::ExtRef<T>> {
	static _FORCE_INLINE_ gdpp::ExtRef<T> cast(const Variant &p_variant) {
		return Ref<typename T::Base>(p_variant);
	}
};

// Bindings see a Weak<T> as a strong_t<T>: the object, or null once it's gone.

template <typename T>
struct GetTypeInfo<gdpp::Weak<T>> {
	static constexpr GDExtensionVariantType VARIANT_TYPE = GDEXTENSION_VARIANT_TYPE_OBJECT;
	static constexpr GDExtensionClassMethodArgumentMetadata METADATA = GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE;
	static inline PropertyInfo get_class_info() {
		return GetTypeInfo<gdpp::strong_t<T>>::get_class_info();
	}
};

template <typename T>
struct PtrToArg<gdpp::Weak<T>> {
	_FORCE_INLINE_ static gdpp::Weak<T> convert(const void *p_ptr) {
		return PtrToArg<gdpp::strong_t<T>>::convert(p_ptr);
	}
	typedef typename PtrToArg<gdpp::strong_t<T>>::EncodeT EncodeT;
	_FORCE_INLINE_ static void encode(gdpp::Weak<T> p_val, void *p_ptr) {
		PtrToArg<gdpp::strong_t<T>>::encode(p_val, p_ptr);
	}
};

template <typename T>
struct VariantCaster<gdpp::Weak<T>> {
	static _FORCE_INLINE_ gdpp::Weak<T> cast(const Variant &p_variant) {
		return Object::cast_to<T>(p_variant.operator Object *());
	}
};

// Bindings see an Async as an object of the class of tasks.

template <typename T>
struct GetTypeInfo<gdpp::Async<T>> {
	static constexpr GDExtensionVariantType VARIANT_TYPE = GDEXTENSION_VARIANT_TYPE_OBJECT;
	static constexpr GDExtensionClassMethodArgumentMetadata METADATA = GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE;
	static inline PropertyInfo get_class_info() {
		return PropertyInfo(Variant::OBJECT, "", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT, gdpp::async_class);
	}
};

template <typename T>
struct PtrToArg<gdpp::Async<T>> {
	_FORCE_INLINE_ static gdpp::Async<T> convert(const void *p_ptr) {
		return gdpp::Async<T>(PtrToArg<Ref<RefCounted>>::convert(p_ptr));
	}
	typedef Ref<RefCounted> EncodeT;
	_FORCE_INLINE_ static void encode(gdpp::Async<T> p_val, void *p_ptr) {
		PtrToArg<Ref<RefCounted>>::encode(p_val.object(), p_ptr);
	}
};

template <typename T>
struct VariantCaster<gdpp::Async<T>> {
	static _FORCE_INLINE_ gdpp::Async<T> cast(const Variant &p_variant) {
		return gdpp::Async<T>(Ref<RefCounted>(p_variant));
	}
};

} // namespace godot

// GDPP_ENUM_TAG makes m_tag, a class's stand-in for one of the package's enums, bind as the enum m_name
// (e.g. "MyNode.Suit"), since each class exposes its own copy of the enums it uses. Use it in namespace godot.
#define GDPP_ENUM_TAG(m_tag, m_name) GDPP_INT_TAG(m_tag, m_name, PROPERTY_USAGE_CLASS_IS_ENUM)

// GDPP_BITFIELD_TAG is GDPP_ENUM_TAG for bitfields.
#define GDPP_BITFIELD_TAG(m_tag, m_name) GDPP_INT_TAG(m_tag, m_name, PROPERTY_USAGE_CLASS_IS_BITFIELD)

// GDPP_INT_TAG makes m_tag bind as an int with m_usage, e.g. PROPERTY_USAGE_CLASS_IS_ENUM, and class name m_name.
#define GDPP_INT_TAG(m_tag, m_name, m_usage) \
	template <> \
	struct GetTypeInfo<m_tag> { \
		static constexpr GDExtensionVariantType VARIANT_TYPE = GDEXTENSION_VARIANT_TYPE_INT; \
		static constexpr GDExtensionClassMethodArgumentMetadata METADATA = GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE; \
		static inline PropertyInfo get_class_info() { \
			return PropertyInfo(Variant::INT, "", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT | m_usage, m_name); \
		} \
	}; \
	template <> \
	struct VariantCaster<m_tag> { \
		static _FORCE_INLINE_ m_tag cast(const Variant &p_variant) { \
			return (m_tag)p_variant.operator int64_t(); \
		} \
	}; \
	template <> \
	struct PtrToArg<m_tag> { \
		_FORCE_INLINE_ static m_tag convert(const void *p_ptr) { \
			return m_tag(*reinterpret_cast<const int64_t *>(p_ptr)); \
		} \
		typedef int64_t EncodeT; \
		_FORCE_INLINE_ static void encode(m_tag p_val, void *p_ptr) { \
			*reinterpret_cast<int64_t *>(p_ptr) = p_val; \
		} \
	};

// GDPP_BITFIELD gives m_enum, a GD++ bitfield, the bitwise operators. & returns a gdpp::Masked, which tests as a bool.
// Use it in namespace godot.
#define GDPP_BITFIELD(m_enum) \
	constexpr m_enum operator|(m_enum a, m_enum b) { return m_enum(int64_t(a) | int64_t(b)); } \
	constexpr gdpp::Masked<m_enum> operator&(m_enum a, m_enum b) { return { m_enum(int64_t(a) & int64_t(b)) }; } \
	constexpr m_enum operator^(m_enum a, m_enum b) { return m_enum(int64_t(a) ^ int64_t(b)); } \
	constexpr m_enum operator~(m_enum a) { return m_enum(~int64_t(a)); } \
	constexpr m_enum &operator|=(m_enum &a, m_enum b) { return a = a | b; } \
	constexpr m_enum &operator&=(m_enum &a, m_enum b) { return a = a & b; } \
	constexpr m_enum &operator^=(m_enum &a, m_enum b) { return a = a ^ b; }

#endif // GDPP_SYNTAX_0_HPP

// The code that @trace and @profile generate, with gd++ build --trace or --profile. Only files that use it define
// GDPP_DEBUGGING, so the others don't include its headers. With --trace, the headers of classes with assertions
// define GDPP_TRACING, which also gets it, for failed assertions. It has its own guard, so the header of an extern
// with debugging on gets it even if the runtime was included before without it.
#if (defined(GDPP_DEBUGGING) || defined(GDPP_TRACING)) && !defined(GDPP_SYNTAX_0_DEBUGGING)
#define GDPP_SYNTAX_0_DEBUGGING

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstring>
#include <functional>
#include <mutex>
#include <vector>

#include <godot_cpp/classes/os.hpp>
#include <godot_cpp/classes/performance.hpp>
#include <godot_cpp/classes/scene_tree.hpp>
#include <godot_cpp/classes/window.hpp>
#include <godot_cpp/variant/callable_method_pointer.hpp>

namespace gdpp {

class Profile;
class Watch;

// now returns a steady time in nanoseconds. It costs a few tens of nanoseconds, unlike Godot's Time, which is an
// engine call with microsecond resolution.
inline int64_t now() {
	return std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now().time_since_epoch()).count();
}

// DebugThread is the state of tracing and profiling on one thread.
struct DebugThread {
	// How deep trace lines are indented.
	int depth = 0;
	// Nanoseconds spent tracing and profiling, which timings subtract.
	int64_t untimed = 0;
	// The innermost profiled call.
	Profile *profile = nullptr;
	// The innermost call that watches @trace vars.
	Watch *watch = nullptr;
	// Whether this is the main thread: 1 or 0, or -1 if not known yet.
	int main = -1;
};
GDPP_THREAD_LOCAL(DebugThread, debug_thread)

// escaped escapes s for print_rich, which reads [ as the start of a BBCode tag.
inline String escaped(const String &s) {
	return s.replace("[", "[lb]");
}

// describe returns how trace lines name p_object: its class, and a node's name or else the instance id.
inline String describe(const Object *p_object) {
	if (!p_object) {
		return "null";
	}
	String result = p_object->get_class();
	const Node *node = Object::cast_to<Node>(p_object);
	if (node && !String(node->get_name()).is_empty()) {
		return result + " \"" + escaped(node->get_name()) + "\"";
	}
	return result + "#" + String::num_uint64(p_object->get_instance_id());
}

// snapshot returns a value as trace lines show and compare it: enums as ints, and containers copied deeply, so
// later changes to their items show.
template <typename T>
Variant snapshot(const T &p_value) {
	if constexpr (std::is_enum_v<T>) {
		return static_cast<int64_t>(p_value);
	} else {
		Variant result = p_value;
		if (result.get_type() == Variant::ARRAY || result.get_type() == Variant::DICTIONARY) {
			result = result.duplicate(true);
		}
		return result;
	}
}

// repr returns how trace lines show a value: strings quoted, objects described, and long values shortened.
inline String repr(const Variant &p_value) {
	Variant::Type type = p_value.get_type();
	if (type == Variant::OBJECT) {
		return describe(p_value.operator Object *());
	}
	String s = p_value.stringify();
	if (s.length() > 60) {
		s = s.left(59) + String(U"…");
	}
	bool quoted = type == Variant::STRING || type == Variant::STRING_NAME || type == Variant::NODE_PATH;
	return escaped(quoted ? "\"" + s + "\"" : s);
}

// duration returns p_ns nanoseconds in µs or ms.
inline String duration(int64_t p_ns) {
	return p_ns < 1000000 ? String::num(p_ns / 1e3, 1) + String(U" µs") : String::num(p_ns / 1e6, 2) + " ms";
}

// add_args appends the name: value pairs of p_args, alternating names and values, to r_line.
inline void add_args(String &) {}
// add_args appends the first pair, then the rest.
template <typename T, typename... Rest>
void add_args(String &r_line, const char *p_name, const T &p_value, const Rest &...p_rest) {
	if (!r_line.ends_with("(")) {
		r_line += ", ";
	}
	r_line += String(p_name) + ": " + repr(snapshot(p_value));
	add_args(r_line, p_rest...);
}

// debug_print prints a trace line, indented by the call depth, after the frame and, off the main thread, the thread.
inline void debug_print(const String &p_line) {
	String prefix = "[color=gray][f" + String::num_uint64(Engine::get_singleton()->get_process_frames()) + "]";
	OS *os = OS::get_singleton();
	if (os->get_thread_caller_id() != os->get_main_thread_id()) {
		prefix += " [thread " + String::num_uint64(os->get_thread_caller_id()) + "]";
	}
	UtilityFunctions::print_rich(prefix + "[/color] " + String("  ").repeat(debug_thread().depth) + p_line);
}

// Untimed adds the time until its end to the untimed time of its thread.
struct Untimed {
	// When it was made, in now() time.
	int64_t start = now();
	// Adds the time since start to the thread's untimed time.
	~Untimed() { debug_thread().untimed += now() - start; }
};

// ViaExtern tags the tracing of a call or an emission through an extern. Its lines say "extern", and calls show with
// ▷ and ◁, since they only include what goes through this package's extern, not every call of the class.
struct ViaExtern {};
// via_extern is the ViaExtern that Trace and trace_emit take first.
inline constexpr ViaExtern via_extern;

// Trace prints a call of a @trace function: its arguments when it starts, and its result and duration when it
// returns. The duration leaves out the time spent tracing and profiling.
class Trace {
public:
	// p_args alternate the names and values of the arguments. p_self is null in static functions.
	template <typename... Args>
	Trace(const char *p_class, const Object *p_self, const char *p_func, const Args &...p_args) {
		int64_t begin = now();
		start(begin, false, (p_self ? describe(p_self) : String(p_class)) + "." + p_func, p_args...);
	}

	// The same for a call through an extern, which needs p_self.
	template <typename... Args>
	Trace(ViaExtern, const Object *p_self, const char *p_func, const Args &...p_args) {
		int64_t begin = now();
		start(begin, true, describe(p_self) + "." + p_func, p_args...);
	}

	// ret records the result, which the function returns.
	template <typename T>
	T ret(T p_value) {
		stop();
		result_ = String(U" → ") + repr(snapshot(p_value));
		return p_value;
	}

	// Prints the end of the call, with its result, if ret recorded one, and its duration.
	~Trace() {
		if (!end_) {
			stop();
		}
		int64_t took = end_ - start_ - (untimed_end_ - untimed_start_);
		debug_thread().depth--;
		debug_print(String(extern_ ? U"◁ extern " : U"◀ ") + name_ + result_ + "  [color=gray]" + duration(took) + "[/color]");
		// Everything since the end is untimed, including what the vars' Watch already counted.
		debug_thread().untimed = untimed_end_ + (now() - end_);
	}

private:
	// start prints the start line of the call named p_name, which began at p_begin, through an extern if p_extern.
	template <typename... Args>
	void start(int64_t p_begin, bool p_extern, const String &p_name, const Args &...p_args) {
		name_ = p_name;
		extern_ = p_extern;
		String line = String(extern_ ? U"▷ extern " : U"▶ ") + name_ + "(";
		add_args(line, p_args...);
		debug_print(line + ")");
		debug_thread().depth++;
		start_ = now();
		debug_thread().untimed += start_ - p_begin;
		untimed_start_ = debug_thread().untimed;
	}

	void stop() {
		end_ = now();
		untimed_end_ = debug_thread().untimed;
	}

	String name_, result_;
	bool extern_ = false;
	int64_t start_ = 0, end_ = 0, untimed_start_ = 0, untimed_end_ = 0;
};

// trace_lifetime prints the creation or the destruction of an object of a @trace class. It names the object by its
// instance id, since a node has no name yet when it's created, and can't be asked for it any more when destroyed.
inline void trace_lifetime(const char *p_class, const Object *p_self, bool p_created) {
	Untimed untimed;
	debug_print(String(p_created ? "+ " : "- ") + p_class + "#" + String::num_uint64(p_self->get_instance_id()) + (p_created ? " created" : " freed"));
}

// trace_recycle prints the reuse of an object of a @trace @pool class by its pool, or its return to the pool, like
// trace_lifetime.
inline void trace_recycle(const char *p_class, const Object *p_self, bool p_reused) {
	Untimed untimed;
	debug_print(String(U"↻ ") + p_class + "#" + String::num_uint64(p_self->get_instance_id()) + (p_reused ? " reused" : " returned to its pool"));
}

// trace_emit prints the emission of a signal of a @trace class. p_args alternate the names and values of its arguments.
template <typename... Args>
void trace_emit(const Object *p_self, const char *p_signal, const Args &...p_args) {
	Untimed untimed;
	String line = String(U"⚡ ") + describe(p_self) + " emits " + p_signal + "(";
	add_args(line, p_args...);
	debug_print(line + ")");
}

// The same for a signal emitted through an extern.
template <typename... Args>
void trace_emit(ViaExtern, const Object *p_self, const char *p_signal, const Args &...p_args) {
	Untimed untimed;
	String line = String(U"⚡ extern ") + describe(p_self) + " emits " + p_signal + "(";
	add_args(line, p_args...);
	debug_print(line + ")");
}

// trace_assert prints a failed assertion as a trace line, with its location, which trace lines have nowhere else.
inline void trace_assert(const char *p_condition, const char *p_file, int p_line) {
	Untimed untimed;
	debug_print(String(U"[color=red]✖ ") + escaped(vformat("Failed GD++ assertion: `%s`, at %s:%d.", p_condition, p_file, p_line)) + "[/color]");
}

// Watch prints the changes to the @trace vars of a class during a call of one of its functions.
class Watch {
public:
	// p_vars alternate names and functions that return the var's value.
	template <typename... Vars>
	Watch(const Object *p_self, const char *p_func, const Vars &...p_vars) :
			self_(p_self), func_(p_func), parent_(debug_thread().watch) {
		Untimed untimed;
		add(p_vars...);
		debug_thread().watch = this;
	}

	// Prints the vars that changed during the call, with their values before and after.
	~Watch() {
		Untimed untimed;
		debug_thread().watch = parent_;
		for (Var &v : vars_) {
			Variant value = v.get();
			if (value == v.before) {
				continue;
			}
			debug_print(describe(self_) + "." + v.name + ": " + repr(v.before) + String(U" → ") + repr(value) + "  [color=gray](in " + func_ + ")[/color]");
			// The calls that this one is inside see the change as done, so it's printed once.
			for (Watch *w = parent_; w; w = w->parent_) {
				for (Var &p : w->vars_) {
					if (w->self_ == self_ && std::strcmp(p.name, v.name) == 0) {
						p.before = value;
					}
				}
			}
		}
	}

private:
	struct Var {
		const char *name;
		std::function<Variant()> get;
		Variant before;
	};

	void add() {}
	template <typename F, typename... Rest>
	void add(const char *p_name, const F &p_get, const Rest &...p_rest) {
		vars_.push_back({ p_name, [p_get]() { return snapshot(p_get()); }, snapshot(p_get()) });
		add(p_rest...);
	}

	const Object *self_;
	const char *func_;
	Watch *parent_;
	std::vector<Var> vars_;
};

// ProfileStats are the timings of one @profile function, from all threads, in nanoseconds.
struct ProfileStats {
	// The function's name, e.g. "Player.fire".
	const char *name;
	// The number of calls, and those on the main thread, the time of the outermost calls, the time of all calls
	// without the profiled calls inside them, and the longest outermost call.
	std::atomic<int64_t> calls{ 0 }, main_calls{ 0 }, total{ 0 }, self{ 0 }, max{ 0 };
	// What the live monitor showed last, at frame shown_frame.
	int64_t shown_total = 0;
	// The frame of shown_total.
	uint64_t shown_frame = 0;
	// The totals when the last table was printed.
	int64_t printed_calls = 0, printed_total = 0, printed_self = 0;

	// An unnamed ProfileStats isn't registered, e.g. to calibrate.
	ProfileStats() = default;
	// Registers the function, which then shows in the editor's monitors, and if p_print_seconds isn't 0, in a
	// table printed every p_print_seconds seconds, with its share of a frame at p_fps frames per second.
	ProfileStats(const char *p_name, int64_t p_print_seconds = 0, int64_t p_fps = 60);
};

// Profiler holds the registered ProfileStats, and the cost of profiling a call.
struct Profiler {
	// Guards stats.
	std::mutex mutex;
	// The registered ProfileStats, in order of registration.
	std::vector<ProfileStats *> stats;
	// The time a profiled call measures that is really the profiling's.
	int64_t inner = 0;
	// The time a profiled call adds to the call it's inside, beyond its own.
	int64_t outer = 0;
	// Nanoseconds between tables, or 0 if the table isn't printed.
	int64_t print_every = 0;
	// When the last table was printed, or printing started.
	int64_t printed_at = 0;
	// The frame when the last table was printed.
	uint64_t printed_frame = 0;
	// The frame rate whose frame the table's budget column is a share of.
	int64_t fps = 60;
};

// profiler returns the package's one Profiler.
inline Profiler &profiler() {
	static Profiler p;
	return p;
}

// Profile times a call of a @profile function. The time spent tracing and profiling, including the calibrated cost
// of timing the profiled calls inside it, doesn't count.
class Profile {
public:
	// Starts timing a call of the function of p_stats.
	explicit Profile(ProfileStats &p_stats) :
			stats_(p_stats), parent_(debug_thread().profile) {
		debug_thread().profile = this;
		untimed_ = debug_thread().untimed;
		start_ = now();
	}

	// Adds the call's time to p_stats.
	~Profile() {
		int64_t took
 = std::max<int64_t>(now() - start_ - (debug_thread().untimed - untimed_) - profiler().inner, 0);
		debug_thread().profile = parent_;
		stats_.calls.fetch_add(1, std::memory_order_relaxed);
		if (debug_thread().main < 0) {
			debug_thread().main = OS::get_singleton()->get_thread_caller_id() == OS::get_singleton()->get_main_thread_id();
		}
		if (debug_thread().main) {
			stats_.main_calls.fetch_add(1, std::memory_order_relaxed);
		}
		stats_.self.fetch_add(std::max<int64_t>(took - children_, 0), std::memory_order_relaxed);
		// A recursive call's time is already in the outermost call's.
		bool outermost = true;
		for (Profile *p = parent_; p; p = p->parent_) {
			outermost = outermost && &p->stats_ != &stats_;
		}
		if (outermost) {
			stats_.total.fetch_add(took, std::memory_order_relaxed);
			int64_t max = stats_.max.load(std::memory_order_relaxed);
			while (took > max && !stats_.max.compare_exchange_weak(max, took, std::memory_order_relaxed)) {
			}
		}
		if (parent_) {
			parent_->children_ += took;
		}
		debug_thread().untimed += profiler().outer;
	}

private:
	ProfileStats &stats_;
	Profile *parent_;
	int64_t start_ = 0, untimed_ = 0, children_ = 0;
};

// calibrate measures the cost of profiling a call: the median of many empty profiled calls.
inline void calibrate(Profiler &r_profiler) {
	constexpr int count = 1000;
	ProfileStats empty;
	std::vector<int64_t> inner, outer;
	Profile *profile = debug_thread().profile;
	debug_thread().profile = nullptr;
	for (int i = 0; i < count; i++) {
		int64_t self = empty.self.load(), start = now();
		{
			Profile p(empty);
		}
		outer.push_back(now() - start);
		inner.push_back(empty.self.load() - self);
	}
	debug_thread().profile = profile;
	std::nth_element(inner.begin(), inner.begin() + count / 2, inner.end());
	std::nth_element(outer.begin(), outer.begin() + count / 2, outer.end());
	r_profiler.inner = inner[count / 2];
	r_profiler.outer = outer[count / 2];
}

// profile_monitor returns the milliseconds per frame that the registered function at p_index took since the
// monitor's last call.
inline double profile_monitor(int64_t p_index) {
	Profiler &p = profiler();
	std::lock_guard<std::mutex> lock(p.mutex);
	ProfileStats *s = p.stats[p_index];
	uint64_t frame = Engine::get_singleton()->get_process_frames();
	int64_t total = s->total.load(std::memory_order_relaxed);
	double result = frame > s->shown_frame ? (total - s->shown_total) / 1e6 / (frame - s->shown_frame) : 0.0;
	s->shown_total = total;
	s->shown_frame = frame;
	return result;
}

// print_profile prints the timings of the registered functions since the last table, slowest first. It leaves out
// those that didn't run, and prints nothing if none did.
inline void print_profile() {
	Profiler &p = profiler();
	std::lock_guard<std::mutex> lock(p.mutex);
	struct Row {
		const char *name;
		int64_t calls, total, self, max;
		String thread;
		bool main_only; // Whether it only ever ran on the main thread, so it uses up the frame's budget.
	};
	std::vector<Row> rows;
	for (ProfileStats *s : p.stats) {
		int64_t calls = s->calls.load(), total = s->total.load(), self = s->self.load();
		// Where the function ran so far, not only since the last table.
		int64_t main = s->main_calls.load();
		String thread = main == calls ? String("main") : main == 0 ? String("subthread") : String::num_int64(main * 100 / calls) + "% main";
		Row row{ s->name, calls - s->printed_calls, total - s->printed_total, self - s->printed_self, s->max.exchange(0), thread, main == calls };
		s->printed_calls = calls;
		s->printed_total = total;
		s->printed_self = self;
		if (row.calls > 0) {
			rows.push_back(row);
		}
	}
	uint64_t frame = Engine::get_singleton()->get_process_frames();
	double frames = std::max<uint64_t>(frame - p.printed_frame, 1);
	double seconds = (now() - p.printed_at) / 1e9;
	p.printed_frame = frame;
	p.printed_at = now();
	if (rows.empty()) {
		return;
	}
	std::sort(rows.begin(), rows.end(), [](const Row &a, const Row &b) { return a.total > b.total; });
#ifdef DEBUG_ENABLED
	String build = "debug";
#else
	String build = "release";
#endif
#if defined(__OPTIMIZE__) || defined(_MSC_VER) && !defined(_DEBUG)
	build += ", optimized";
#else
	build += ", unoptimized";
#endif
	int64_t width = 8;
	for (const Row &r : rows) {
		width = std::max<int64_t>(width, String(r.name).length());
	}
	std::vector<String> headers = { "Thread", "Calls", "Total ms", "Self ms", String(U"Avg µs"), String(U"Max µs"), "ms/frame",
		"Budget (" + String::num_int64(p.fps) + " FPS)" };
	// The cells of each row. A function that ran on other threads doesn't use up the main thread's frame, so its
	// budget isn't colored, and says so.
	std::vector<std::vector<String>> cells;
	for (const Row &r : rows) {
		double ms_per_frame = r.total / 1e6 / frames;
		double budget = ms_per_frame * p.fps / 10;
		cells.push_back({ r.thread, String::num_uint64(r.calls), String::num(r.total / 1e6, 2), String::num(r.self / 1e6, 2),
				String::num(r.total / 1e3 / r.calls, 2), String::num(r.max / 1e3, 2), String::num(ms_per_frame, 3),
				String::num(budget, 1) + "%" + (r.main_only ? "" : " (on background)") });
	}
	std::vector<int64_t> widths;
	int64_t total_width = width;
	for (size_t i = 0; i < headers.size(); i++) {
		int64_t w = std::max<int64_t>(12, headers[i].length() + 2);
		for (const std::vector<String> &row : cells) {
			w = std::max<int64_t>(w, row[i].length() + 2);
		}
		widths.push_back(w);
		total_width += w;
	}
	// One print, so no other output lands inside the table, and in [code], so its columns line up in the editor.
	String title = String(U"━━ GD++ profile · last ") + String::num(seconds, 1) + String(U" s · ") + String::num_uint64(frames) + String(U" frames · ") + build + " ";
	String table = "\n[code][color=cyan]" + title + String(U"━").repeat(std::max<int64_t>(total_width - title.length(), 2)) + "[/color]\n";
	auto line = [&](const String &name, const std::vector<String> &cells, const String &budget_color) {
		table += name.rpad(width);
		for (size_t i = 0; i < cells.size(); i++) {
			String cell = cells[i].lpad(widths[i]);
			table += i + 1 == cells.size() && !budget_color.is_empty() ? "[color=" + budget_color + "]" + cell + "[/color]" : cell;
		}
		table += "\n";
	};
	line("Function", headers, "");
	table += "[color=gray]" + String(U"─").repeat(total_width) + "[/color]\n";
	for (size_t i = 0; i < rows.size(); i++) {
		double budget = rows[i].total / 1e6 / frames * p.fps / 10;
		String color = !rows[i].main_only ? "" : budget < 10 ? "green" : budget <= 50 ? "yellow" : "red";
		line(rows[i].name, cells[i], color);
	}
	UtilityFunctions::print_rich(table.trim_suffix("\n") + "[/code]");
}

// profile_tick prints the table when its time has come. It runs every frame.
inline void profile_tick() {
	if (now() - profiler().printed_at >= profiler().print_every) {
		print_profile();
	}
}

inline ProfileStats::ProfileStats(const char *p_name, int64_t p_print_seconds, int64_t p_fps) :
		name(p_name) {
	Untimed untimed;
	Profiler &p = profiler();
	std::lock_guard<std::mutex> lock(p.mutex);
	if (p.stats.empty()) {
		calibrate(p);
	}
	Array index;
	index.push_back(int64_t(p.stats.size()));
	p.stats.push_back(this);
	String id = "GD++/" + String(p_name) + " (ms)";
	if (!Performance::get_singleton()->has_custom_monitor(id)) {
		Performance::get_singleton()->add_custom_monitor(id, callable_mp_static(&profile_monitor), index);
		on_unload([id] {
			if (Performance::get_singleton()->has_custom_monitor(id)) {
				Performance::get_singleton()->remove_custom_monitor(id);
			}
		});
	}
	SceneTree *tree = Object::cast_to<SceneTree>(Engine::get_singleton()->get_main_loop());
	if (p_print_seconds > 0 && !p.print_every && tree) {
		p.print_every = p_print_seconds * 1000000000;
		p.fps = p_fps;
		p.printed_at = now();
		p.printed_frame = Engine::get_singleton()->get_process_frames();
		connect_until_unload(tree, "process_frame", callable_mp_static(&profile_tick));
	}
}

} // namespace gdpp

#endif // GDPP_SYNTAX_0_DEBUGGING

// With GDPP_TRACING, failed assertions also print a trace line. It has its own guard, so a class's header gets it even
// if the runtime and its debugging code were included before without it.
#if defined(GDPP_TRACING) && !defined(GDPP_SYNTAX_0_TRACING)
#define GDPP_SYNTAX_0_TRACING
#undef GDPP_TRACE_ASSERT
#define GDPP_TRACE_ASSERT(m_text) gdpp::trace_assert(m_text, __FILE__, __LINE__)
#endif
