// Generated by GD++, do not edit.

#include <type_traits>

#include <gdextension_interface.h>
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/core/defs.hpp>
#include <godot_cpp/godot.hpp>
{{- if .Runtime}}

// The GD++ runtime, which defines the package's class of tasks, and unloads the package's GD++ code.
#include <{{.Runtime}}>
{{- end}}
{{- if .EditorPlugins}}
#include <godot_cpp/classes/editor_plugin_registration.hpp>
{{- end}}
{{- if .GpuRuntime}}

// The GD++ runtime of shaders, which defines the package's class of GPU arrays, and of the textures that shaders create.
#include <{{.GpuRuntime}}>
{{- end}}
{{range .Includes}}
#include {{.}}{{end}}

using namespace godot;

template <typename T>
constexpr bool gdpp_is_package_class = false{{range .Classes}} || std::is_same_v<T, {{.}}>{{end}};

// Runtime classes are classes without tool or abstract, which don't extend a
// class with one of those: in the editor, Godot makes placeholders of them
// that store their properties but run none of their code.
template <typename T>
constexpr bool gdpp_is_runtime_class = false{{range .RuntimeClasses}} || std::is_same_v<T, {{.}}>{{end}};

// Abstract classes are registered as virtual, like GDScript's @abstract: the
// editor creates none of their objects, but scripts that extend them work.
// Those with pure virtual functions are registered as abstract, which godot-cpp
// requires: then not even scripts that extend them can be created.
template <typename T>
constexpr bool gdpp_is_abstract_class = false{{range .AbstractClasses}} || std::is_same_v<T, {{.}}>{{end}};

// Whether T is registered. gdpp_uninitialize resets it: if the library stays
// loaded on hot reload, e.g. because of thread_local storage, it must register
// its classes again.
template <typename T>
static bool gdpp_registered = false;

// Registers T, after its parent if that's a class of this package too, since
// Godot requires parents to be registered first.
template <typename T>
static void gdpp_register_class() {
	if (gdpp_registered<T>) {
		return;
	}
	gdpp_registered<T> = true;
	if constexpr (gdpp_is_package_class<typename T::parent_type>) {
		gdpp_register_class<typename T::parent_type>();
	}
	if constexpr (std::is_abstract_v<T>) {
		GDREGISTER_ABSTRACT_CLASS(T);
	} else if constexpr (gdpp_is_abstract_class<T>) {
		GDREGISTER_VIRTUAL_CLASS(T);
	} else if constexpr (gdpp_is_runtime_class<T>) {
		GDREGISTER_RUNTIME_CLASS(T);
	} else {
		GDREGISTER_CLASS(T);
	}
{{- if .Runtime}}
	// Records the traits that T implements, which casts look up.
	gdpp::register_traits<T>();
{{- end}}
}

static void gdpp_initialize(ModuleInitializationLevel p_level) {
{{- if .EditorClasses}}
	// Classes that extend the editor's, which only exist in the editor.
	if (p_level == MODULE_INITIALIZATION_LEVEL_EDITOR) {
{{- range .EditorClasses}}
		gdpp_register_class<{{.}}>();
{{- end}}
{{- range .EditorPlugins}}
		EditorPlugins::add_by_type<{{.}}>();
{{- end}}
	}
{{- end}}
	if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
		return;
	}
{{- if .AsyncClass}}
	GDREGISTER_CLASS(gdpp::GDPP_ASYNC_CLASS);
{{- end}}
{{- if .GpuRuntime}}
	GDREGISTER_CLASS(gdpp::GDPP_GPU_ARRAY_CLASS);
	GDREGISTER_INTERNAL_CLASS(gdpp::GDPP_GPU_TEXTURE_CLASS);
{{- end}}
{{- range .SceneClasses}}
	gdpp_register_class<{{.}}>();
{{- end}}
{{- range .Singletons}}
	gdpp::add_singleton("{{.}}", {{.}}::_gdpp_singleton);
{{- end}}
{{- if .Testing}}
	// The runner of tests, which gd++ test runs as the main loop.
	GDREGISTER_CLASS(gdpp::GDPP_TESTS_CLASS);
{{- end}}
}

static void gdpp_uninitialize(ModuleInitializationLevel p_level) {
{{- if .EditorClasses}}
	if (p_level == MODULE_INITIALIZATION_LEVEL_EDITOR) {
{{- range .EditorPlugins}}
		EditorPlugins::remove_by_type<{{.}}>();
{{- end}}
{{- range .EditorClasses}}
		gdpp_registered<{{.}}> = false;
{{- end}}
	}
{{- end}}
	if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
		return;
	}
{{- range .Singletons}}
	gdpp::drop_singleton("{{.}}", {{.}}::_gdpp_singleton);
{{- end}}
{{- if .Runtime}}
	// Waits for the package's tasks, and removes the engine's hooks into the package's code, which must not run once
	// it's unloaded, e.g. by hot reload.
	gdpp::uninitialize();
{{- end}}
{{- range .SceneClasses}}
	gdpp_registered<{{.}}> = false;
{{- end}}
}

extern "C" GDExtensionBool GDE_EXPORT gdpp_library_init(GDExtensionInterfaceGetProcAddress p_get_proc_address, GDExtensionClassLibraryPtr p_library, GDExtensionInitialization *r_initialization) {
	GDExtensionBinding::InitObject init_obj(p_get_proc_address, p_library, r_initialization);
	init_obj.register_initializer(gdpp_initialize);
	init_obj.register_terminator(gdpp_uninitialize);
	init_obj.set_minimum_library_initialization_level(MODULE_INITIALIZATION_LEVEL_SCENE);
	return init_obj.init();
}
