package syntax_0

import (
	"fmt"
	"slices"
	"strings"

	"gd++/trans/meta"
)

// header returns the C++ header <name>.h of the unit's one declaration, named name: an enum type, an extern
// wrapper or a class definition.
func (u *unit) header(name string) string {
	w := &writer{self: name + ".h", source: u.opts.SourceName}
	w.ln("// Generated by GD++ from %s, do not edit.", u.opts.SourceName)
	w.ln("")
	w.ln("#pragma once")
	w.ln("")
	if slices.ContainsFunc(u.externs, (*externModel).debugging) {
		w.ln("#define GDPP_DEBUGGING")
	}
	w.ln("#include <%s>", RuntimeHeaderName)
	// Other GD++ headers may include this one in turn, and #pragma once cuts such a cycle short. So their classes,
	// externs and enums are forward-declared, and included at the end, unless they must be complete.
	names, complete := u.headerNames()
	forward := map[string]bool{}
	var forwardNames []string
	for _, name := range names {
		if s := u.symbols[name]; s != nil && s.gdpp && s.kind != meta.Other &&
			!slices.Contains(complete, name) && !forward[name] {
			forward[name] = true
			forwardNames = append(forwardNames, name)
		}
	}
	slices.Sort(forwardNames)
	top := u.includes(names, forward)
	for _, inc := range top {
		w.ln("#include %s", inc)
	}
	u.globals(w, true)
	w.ln("")
	w.ln("namespace godot {")
	if len(forwardNames) > 0 {
		w.ln("")
		for _, name := range forwardNames {
			if u.symbols[name].kind == meta.Enum {
				w.ln("enum class %s : int64_t;", name)
			} else {
				w.ln("class %s;", name)
			}
		}
	}
	for _, s := range u.enums {
		w.ln("")
		w.ln("enum class %s : int64_t {", s.name)
		for _, v := range s.values {
			w.ln("\t%s = %d,", v.Name, v.Value)
		}
		w.ln("};")
		if s.bitfield {
			w.ln("GDPP_BITFIELD(%s)", s.name)
		}
	}
	for _, c := range u.classes {
		for _, e := range c.enums {
			w.ln("")
			macro := "GDPP_ENUM_TAG"
			if e.bitfield {
				macro = "GDPP_BITFIELD_TAG"
			}
			w.ln("enum %s : int64_t {};", tagName(c, e))
			w.ln("%s(%s, %q)", macro, tagName(c, e), c.name+"."+e.name)
		}
	}
	for _, e := range u.externs {
		u.externDecl(w, e)
	}
	for _, c := range u.classes {
		u.classDecl(w, c)
	}
	// The members of externs come after the includes at the end, since they may use the classes those declare.
	var end []string
	for _, inc := range u.includes(forwardNames, nil) {
		if !slices.Contains(top, inc) {
			end = append(end, inc)
		}
	}
	if len(end) > 0 {
		w.ln("")
		w.ln("} // namespace godot")
		w.ln("")
		for _, inc := range end {
			w.ln("#include %s", inc)
		}
		if len(u.externs) == 0 {
			return w.String()
		}
		w.ln("")
		w.ln("namespace godot {")
	}
	for _, e := range u.externs {
		u.externDefs(w, e)
	}
	w.ln("")
	w.ln("} // namespace godot")
	return w.String()
}

// globals writes the @global decl blocks of the unit's classes, or with decl false, the @global impl blocks.
func (u *unit) globals(w *writer, decl bool) {
	for _, c := range u.classes {
		for _, g := range c.globals {
			if g.Decl && decl || g.Impl && !decl {
				w.ln("")
				w.block(g.Body, "", "")
			}
		}
	}
}

// tagName is the name of the stand-in type through which class c binds enum e.
func tagName(c *classModel, e *symbol) string {
	return "_gdpp_" + c.name + "_" + e.name
}

// tagged returns the type that bindings of class c use for t: its tag if t is an enum, else t itself.
func tagged(c *classModel, t *gtype) string {
	if t.enum != nil {
		return tagName(c, t.enum)
	}
	return t.cpp
}

// params returns a parameter list. With c set, enums are replaced by the class's tags.
func params(c *classModel, types []*gtype, list []*Param) string {
	var ps []string
	for i, t := range types {
		p := t.param()
		if c != nil && t.enum != nil {
			p = tagName(c, t.enum)
		}
		ps = append(ps, withSpace(p)+list[i].Name)
	}
	return strings.Join(ps, ", ")
}

// declParams returns the parameter list with which the class declares f, default values included.
func declParams(f *funcModel) string {
	var ps []string
	for i, t := range f.params {
		p := withSpace(t.param()) + f.f.Params[i].Name
		if f.f.Params[i].Default != nil {
			p += " = " + defaultName(f, f.f.Params[i]) + "()"
		}
		ps = append(ps, p)
	}
	return strings.Join(ps, ", ")
}

// defaultName is the name of the static method that returns the default value of parameter p of f.
func defaultName(f *funcModel, p *Param) string {
	return "_gdpp_default_" + f.f.Name + "_" + p.Name
}

// withSpace appends a space to a C++ type, unless it ends with * or &.
func withSpace(t string) string {
	if strings.HasSuffix(t, "*") || strings.HasSuffix(t, "&") {
		return t
	}
	return t + " "
}

// processing maps the Node functions that the constructor turns on the processing of, if overridden, to their setters.
var processing = map[string]string{"_process": "set_process", "_physics_process": "set_physics_process"}

func (c *classModel) needsCtor() bool {
	return c.ctor != nil || c.trace || slices.ContainsFunc(c.vars, func(v *varModel) bool { return v.v.Init != nil && !v.onready }) ||
		slices.ContainsFunc(c.funcs, func(f *funcModel) bool { return f.rpc != nil || f.override && processing[f.f.Name] != "" })
}

func (c *classModel) needsDtor() bool {
	return c.dtor != nil || c.trace
}

// rpcDecl returns the declarator of the helper that `rpc f(...)` and `rpc(peer) f(...)` call, without a class name.
// ps is the parameter list of f.
func rpcDecl(f *funcModel, ps string) string {
	if ps != "" {
		ps = ", " + ps
	}
	return fmt.Sprintf("_gdpp_rpc_%s(int64_t p_peer%s)", f.f.Name, ps)
}

// rpcCall returns the call to Godot's rpc_id that the RPC helper of f makes.
func rpcCall(f *funcModel) string {
	return fmt.Sprintf("rpc_id(p_peer, GDPP_STRING_NAME(%q)%s)", f.f.Name, args(f.params, f.f.Params))
}

// trampolined reports whether the getter and setter of v are bound through trampolines.
func (v *varModel) trampolined() bool {
	return v.t.enum != nil
}

func (u *unit) classDecl(w *writer, c *classModel) {
	w.ln("")
	w.ln("#define This %s", c.name)
	w.ln("class %s : public %s {", c.name, c.base)
	base := c.base
	if base == "T" || base == "B" {
		base = "::godot::" + base // GDCLASS has template parameters T and B, which would hide the base.
	}
	w.ln("\tGDCLASS(%s, %s)", c.name, base)
	for _, code := range c.codes {
		if code.Decl {
			w.ln("")
			w.ln("private:")
			w.block(code.Body, "", "")
		}
	}
	var fields []*varModel
	var decls []*Block
	for _, v := range c.vars {
		if v.v.Property == nil {
			fields = append(fields, v)
		}
		decls = append(decls, v.decls...)
	}
	if len(fields) > 0 {
		w.ln("")
		w.ln("public:")
		for _, v := range fields {
			w.ln("\t%s%s{};", withSpace(v.t.cpp), v.v.Name)
		}
	}
	if len(decls) > 0 {
		w.ln("")
		w.ln("private:")
		for _, d := range decls {
			w.block(d, "", "")
		}
	}
	var public []string
	for _, k := range c.consts {
		public = append(public, fmt.Sprintf("static constexpr int64_t %s = %d;", k.Name, k.Value.Value))
	}
	if c.needsCtor() {
		public = append(public, fmt.Sprintf("%s();", c.name))
	}
	if c.needsDtor() {
		public = append(public, fmt.Sprintf("~%s();", c.name))
	}
	for _, f := range c.funcs {
		if f.virtual {
			public = append(public, gdvirtual(c, f))
		}
		prefix, suffix := "", ""
		switch {
		case f.static:
			prefix = "static "
		case f.override:
			suffix = " override"
		}
		if f.isConst {
			suffix = " const" + suffix
		}
		public = append(public, fmt.Sprintf("%s%s%s(%s)%s;", prefix, withSpace(f.ret.cpp), f.f.Name, declParams(f), suffix))
		if f.rpc != nil {
			public = append(public, "Error "+rpcDecl(f, declParams(f))+";")
		}
	}
	for _, v := range c.vars {
		if v.getter != "" {
			public = append(public, fmt.Sprintf("%s%s() const;", withSpace(v.t.cpp), v.getter))
		}
		if v.setter != "" {
			public = append(public, fmt.Sprintf("void %s(%s%s);", v.setter, withSpace(v.t.param()), v.setterParam()))
		}
	}
	for _, s := range c.signals {
		public = append(public, fmt.Sprintf("gdpp::Emitted %s(%s);", s.s.Name, params(nil, s.params, s.s.Params)))
	}
	if len(public) > 0 {
		w.ln("")
		w.ln("public:")
		for _, line := range public {
			w.ln("\t%s", line)
		}
	}
	w.ln("")
	w.ln("protected:")
	w.ln("\tstatic void _bind_methods();")
	var helpers []string
	for _, f := range c.funcs {
		if !f.virtual && !f.override && f.trampolined() {
			helpers = append(helpers, trampolineDecl(c, f))
		}
		for i, p := range f.f.Params {
			if p.Default != nil {
				helpers = append(helpers, fmt.Sprintf("static %s%s();", withSpace(f.params[i].cpp), defaultName(f, p)))
			}
		}
	}
	for _, v := range c.vars {
		if v.trampolined() && v.getter != "" {
			helpers = append(helpers, fmt.Sprintf("%s _gdpp_%s() const;", tagName(c, v.t.enum), v.getter))
		}
		if v.trampolined() && v.setter != "" {
			helpers = append(helpers, fmt.Sprintf("void _gdpp_%s(%s p_value);", v.setter, tagName(c, v.t.enum)))
		}
	}
	if len(helpers) > 0 {
		w.ln("")
		w.ln("private:")
		for _, t := range helpers {
			w.ln("\t%s", t)
		}
	}
	w.ln("};")
	w.ln("#undef This")
}

// setterParam is the name of the setter's parameter.
func (v *varModel) setterParam() string {
	if v.set != nil {
		return v.set.Param.Name
	}
	return "p_value"
}

// gdvirtual returns the GDVIRTUAL macro that lets scripts override f.
func gdvirtual(c *classModel, f *funcModel) string {
	name := fmt.Sprintf("GDVIRTUAL%d", len(f.params))
	args := []string{f.f.Name}
	if !f.ret.void {
		name += "R"
		args = append([]string{tagged(c, f.ret)}, args...)
	}
	if f.isConst {
		name += "C"
	}
	for _, p := range f.params {
		args = append(args, tagged(c, p))
	}
	return name + "(" + strings.Join(args, ", ") + ")"
}

// trampolineDecl declares the method that binds f with the class's enum tags in place of enums.
func trampolineDecl(c *classModel, f *funcModel) string {
	prefix, suffix := "", ""
	if f.static {
		prefix = "static "
	}
	if f.isConst {
		suffix = " const"
	}
	return fmt.Sprintf("%s%s_gdpp_%s(%s)%s;", prefix, withSpace(tagged(c, f.ret)), f.f.Name, params(c, f.params, f.f.Params), suffix)
}

// externDecl declares the wrapper class of an extern. Its members are defined after the classes, which they
// may use. The wrapper of an extern that extends another extern derives from that one's, and shares its Base.
func (u *unit) externDecl(w *writer, e *externModel) {
	derived := u.symbols[e.base].isExtern()
	w.ln("")
	if derived {
		w.ln("class %s : public %s {", e.name, e.base)
	} else {
		w.ln("class %s {", e.name)
	}
	w.ln("public:")
	if !derived {
		w.ln("\tusing Base = %s;", e.base)
	}
	w.ln("\tstatic constexpr const char *gdpp_name = %q;", e.name)
	w.ln("")
	w.ln("\texplicit %s(Base *p_object) :", e.name)
	if derived {
		w.ln("\t\t\t%s(p_object) {}", e.base)
	} else {
		w.ln("\t\t\t_gdpp_base(p_object) {}")
	}
	if len(e.funcs)+len(e.vars)+len(e.signals) > 0 {
		w.ln("")
	}
	for _, f := range e.funcs {
		w.ln("\t%s%s(%s) const;", withSpace(f.ret.cpp), f.f.Name, params(nil, f.params, f.f.Params))
		if f.rpc != nil {
			w.ln("\tError %s const;", rpcDecl(f, params(nil, f.params, f.f.Params)))
		}
	}
	for _, v := range e.vars {
		w.ln("\t%s%s() const;", withSpace(v.t.cpp), v.getter)
		w.ln("\tvoid %s(%sp_value) const;", v.setter, withSpace(v.t.param()))
	}
	for _, s := range e.signals {
		w.ln("\tgdpp::Emitted %s(%s) const;", s.s.Name, params(nil, s.params, s.s.Params))
	}
	if !derived {
		w.ln("")
		w.ln("protected:")
		w.ln("\tBase *_gdpp_base;")
	}
	w.ln("};")
}

// args returns the arguments that pass the parameters on to a call resolved by name, enums as integers.
func args(types []*gtype, list []*Param) string {
	var as []string
	for i, t := range types {
		a := list[i].Name
		if t.enum != nil {
			a = "static_cast<int64_t>(" + a + ")"
		}
		as = append(as, ", "+a)
	}
	return strings.Join(as, "")
}

// deferredCall returns the call through which the @deferred or @thread_safe func f calls the method name of target.
func deferredCall(f *funcModel, target, name string) string {
	if f.deferral == "thread_safe" {
		return fmt.Sprintf("gdpp::call_thread_safe(%s, GDPP_STRING_NAME(%q)%s)", target, name, args(f.params, f.f.Params))
	}
	return fmt.Sprintf("%s->call_deferred(GDPP_STRING_NAME(%q)%s)", target, name, args(f.params, f.f.Params))
}

// debugging reports whether the extern's header uses the runtime's code for @trace and @profile.
func (e *externModel) debugging() bool {
	return slices.ContainsFunc(e.funcs, func(f *funcModel) bool { return f.trace || f.profile }) ||
		slices.ContainsFunc(e.vars, func(v *varModel) bool { return v.profile }) ||
		slices.ContainsFunc(e.signals, func(s *signalModel) bool { return s.trace })
}

// externDefs defines the members of an extern's wrapper class, which call the object's members by name.
// Their @profile and @trace hooks say "extern", since they only see the calls through this extern.
func (u *unit) externDefs(w *writer, e *externModel) {
	for _, f := range e.funcs {
		w.ln("")
		w.ln("inline %s%s::%s(%s) const {", withSpace(f.ret.cpp), e.name, f.f.Name, params(nil, f.params, f.f.Params))
		if f.profile {
			u.profile(w, "extern "+e.name+"."+f.f.Name)
		}
		if f.trace {
			w.ln("\tgdpp::Trace _gdpp_trace(gdpp::via_extern, _gdpp_base, %q%s);", f.f.Name, namedArgs(f.f.Params))
		}
		call := fmt.Sprintf("_gdpp_base->call(GDPP_STRING_NAME(%q)%s)", f.f.Name, args(f.params, f.f.Params))
		switch {
		case f.deferral != "":
			w.ln("\t%s;", deferredCall(f, "_gdpp_base", f.f.Name))
		case f.ret.void:
			w.ln("\t%s;", call)
		case f.trace:
			w.ln("\treturn _gdpp_trace.ret(gdpp::cast<%s>(%s));", f.ret.cpp, call)
		default:
			w.ln("\treturn gdpp::cast<%s>(%s);", f.ret.cpp, call)
		}
		w.ln("}")
		if f.rpc != nil {
			w.ln("")
			w.ln("inline Error %s::%s const {", e.name, rpcDecl(f, params(nil, f.params, f.f.Params)))
			w.ln("\tstatic_assert(std::is_base_of_v<Node, Base>, \"@rpc can only be used in externs that extend Node.\");")
			w.ln("\treturn _gdpp_base->%s;", rpcCall(f))
			w.ln("}")
		}
	}
	for _, v := range e.vars {
		w.ln("")
		w.ln("inline %s%s::%s() const {", withSpace(v.t.cpp), e.name, v.getter)
		if v.profile {
			u.profile(w, "extern "+e.name+"."+v.getter)
		}
		w.ln("\treturn gdpp::cast<%s>(_gdpp_base->get(GDPP_STRING_NAME(%q)));", v.t.cpp, v.v.Name)
		w.ln("}")
		w.ln("")
		w.ln("inline void %s::%s(%sp_value) const {", e.name, v.setter, withSpace(v.t.param()))
		if v.profile {
			u.profile(w, "extern "+e.name+"."+v.setter)
		}
		value := "p_value"
		if v.t.enum != nil {
			value = "static_cast<int64_t>(p_value)"
		}
		w.ln("\t_gdpp_base->set(GDPP_STRING_NAME(%q), %s);", v.v.Name, value)
		w.ln("}")
	}
	for _, s := range e.signals {
		w.ln("")
		w.ln("inline gdpp::Emitted %s::%s(%s) const {", e.name, s.s.Name, params(nil, s.params, s.s.Params))
		if s.trace {
			w.ln("\tgdpp::trace_emit(gdpp::via_extern, _gdpp_base, %q%s);", s.s.Name, namedArgs(s.s.Params))
		}
		w.ln("\treturn gdpp::Emitted{ _gdpp_base->emit_signal(GDPP_STRING_NAME(%q)%s) };", s.s.Name, args(s.params, s.s.Params))
		w.ln("}")
	}
}
