package syntax_0

import (
	"fmt"
	"slices"
	"strings"
)

// header returns the C++ header of the file: enum types, extern wrappers and class definitions.
func (u *unit) header() string {
	w := &writer{self: u.opts.HeaderName, source: u.opts.SourceName}
	w.ln("// Generated by GD++ from %s, do not edit.", u.opts.SourceName)
	w.ln("")
	w.ln("#pragma once")
	w.ln("")
	w.ln("#include <%s>", RuntimeHeaderName)
	for _, inc := range u.includes(u.headerNames(), nil) {
		w.ln("#include %s", inc)
	}
	for _, c := range u.topCode {
		if c.Decl {
			w.ln("")
			w.block(c.Body, "", "")
		}
	}
	w.ln("")
	w.ln("namespace godot {")
	u.aliases(w, u.headerNames(), nil)
	for _, s := range u.enums {
		w.ln("")
		w.ln("enum class %s : int64_t {", s.name)
		for _, v := range s.values {
			w.ln("\t%s = %d,", v.Name, v.Value)
		}
		w.ln("};")
	}
	if len(u.consts) > 0 {
		w.ln("")
		for _, c := range u.consts {
			w.ln("constexpr int64_t %s = %d;", c.Name, c.Value.Value)
		}
	}
	for _, c := range u.classes {
		for _, e := range c.enums {
			w.ln("")
			w.ln("enum %s : int64_t {};", tagName(c, e))
			w.ln("GDPP_ENUM_TAG(%s, %q)", tagName(c, e), c.name+"."+e.name)
		}
	}
	if len(u.classes) > 0 {
		w.ln("")
		for _, c := range u.classes {
			w.ln("class %s;", c.name)
		}
	}
	for _, e := range u.externs {
		u.externDecl(w, e)
	}
	for _, c := range u.classes {
		u.classDecl(w, c)
	}
	for _, e := range u.externs {
		u.externDefs(w, e)
	}
	w.ln("")
	w.ln("} // namespace godot")
	return w.String()
}

// tagName is the name of the stand-in type through which class c binds enum e.
func tagName(c *classModel, e *symbol) string {
	return "_gdpp_" + c.name + "_" + e.name
}

// tagged returns the type that bindings of class c use for t: its tag if t is an enum, else t itself.
func tagged(c *classModel, t *gtype) string {
	if t.enum != nil {
		return tagName(c, t.enum)
	}
	return t.cpp
}

// params returns a parameter list. With c set, enums are replaced by the class's tags.
func params(c *classModel, types []*gtype, list []*Param) string {
	var ps []string
	for i, t := range types {
		p := t.param()
		if c != nil && t.enum != nil {
			p = tagName(c, t.enum)
		}
		ps = append(ps, withSpace(p)+list[i].Name)
	}
	return strings.Join(ps, ", ")
}

// withSpace appends a space to a C++ type, unless it ends with * or &.
func withSpace(t string) string {
	if strings.HasSuffix(t, "*") || strings.HasSuffix(t, "&") {
		return t
	}
	return t + " "
}

func (c *classModel) needsCtor() bool {
	return c.ctor != nil || slices.ContainsFunc(c.vars, func(v *varModel) bool { return v.v.Init != nil && !v.onready }) ||
		slices.ContainsFunc(c.funcs, func(f *funcModel) bool { return f.rpc != nil })
}

// rpcDecl returns the declarator of the helper that `rpc f(...)` and `rpc_id(peer) f(...)` call, without a class name.
func rpcDecl(f *funcModel) string {
	ps := "int64_t p_peer"
	if f.f.Params != nil {
		ps += ", " + params(nil, f.params, f.f.Params)
	}
	return fmt.Sprintf("_gdpp_rpc_%s(%s)", f.f.Name, ps)
}

// rpcCall returns the call to Godot's rpc_id that the RPC helper of f makes.
func rpcCall(f *funcModel) string {
	return fmt.Sprintf("rpc_id(p_peer, %q%s)", f.f.Name, args(f.params, f.f.Params))
}

func (c *classModel) needsReady() bool {
	return slices.ContainsFunc(c.vars, func(v *varModel) bool { return v.v.Init != nil && v.onready })
}

// trampolined reports whether the getter and setter of v are bound through trampolines.
func (v *varModel) trampolined() bool {
	return v.t.enum != nil
}

func (u *unit) classDecl(w *writer, c *classModel) {
	w.ln("")
	w.ln("#define This %s", c.name)
	w.ln("class %s : public %s {", c.name, c.base)
	w.ln("\tGDCLASS(%s, %s)", c.name, c.base)
	for _, code := range c.codes {
		if code.Decl {
			w.ln("")
			w.ln("private:")
			w.block(code.Body, "", "")
		}
	}
	var fields []*varModel
	var decls []*Block
	for _, v := range c.vars {
		if v.v.Property == nil {
			fields = append(fields, v)
		}
		decls = append(decls, v.decls...)
	}
	if len(fields)+len(decls) > 0 {
		w.ln("")
		w.ln("private:")
		for _, v := range fields {
			w.ln("\t%s%s{};", withSpace(v.t.cpp), v.v.Name)
		}
		for _, d := range decls {
			w.block(d, "", "")
		}
	}
	var public []string
	for _, k := range c.consts {
		public = append(public, fmt.Sprintf("static constexpr int64_t %s = %d;", k.Name, k.Value.Value))
	}
	if c.needsCtor() {
		public = append(public, fmt.Sprintf("%s();", c.name))
	}
	if c.dtor != nil {
		public = append(public, fmt.Sprintf("~%s();", c.name))
	}
	for _, f := range c.funcs {
		if f.virtual {
			public = append(public, gdvirtual(c, f))
		}
		prefix, suffix := "", ""
		switch {
		case f.static:
			prefix = "static "
		case f.override:
			suffix = " override"
		}
		if f.isConst {
			suffix = " const" + suffix
		}
		public = append(public, fmt.Sprintf("%s%s%s(%s)%s;", prefix, withSpace(f.ret.cpp), f.f.Name, params(nil, f.params, f.f.Params), suffix))
		if f.rpc != nil {
			public = append(public, "Error "+rpcDecl(f)+";")
		}
	}
	for _, v := range c.vars {
		if v.getter != "" {
			public = append(public, fmt.Sprintf("%s%s() const;", withSpace(v.t.cpp), v.getter))
		}
		if v.setter != "" {
			public = append(public, fmt.Sprintf("void %s(%s%s);", v.setter, withSpace(v.t.param()), v.setterParam()))
		}
	}
	for _, s := range c.signals {
		public = append(public, fmt.Sprintf("gdpp::Emitted %s(%s);", s.s.Name, params(nil, s.params, s.s.Params)))
	}
	if len(public) > 0 {
		w.ln("")
		w.ln("public:")
		for _, line := range public {
			w.ln("\t%s", line)
		}
	}
	w.ln("")
	w.ln("protected:")
	w.ln("\tstatic void _bind_methods();")
	if c.needsReady() {
		w.ln("\tvoid _notification(int p_what);")
	}
	var trampolines []string
	for _, f := range c.funcs {
		if !f.virtual && !f.override && f.usesEnums() {
			trampolines = append(trampolines, trampolineDecl(c, f))
		}
	}
	for _, v := range c.vars {
		if v.trampolined() && v.getter != "" {
			trampolines = append(trampolines, fmt.Sprintf("%s _gdpp_%s() const;", tagName(c, v.t.enum), v.getter))
		}
		if v.trampolined() && v.setter != "" {
			trampolines = append(trampolines, fmt.Sprintf("void _gdpp_%s(%s p_value);", v.setter, tagName(c, v.t.enum)))
		}
	}
	if len(trampolines) > 0 {
		w.ln("")
		w.ln("private:")
		for _, t := range trampolines {
			w.ln("\t%s", t)
		}
	}
	w.ln("};")
	w.ln("#undef This")
}

// setterParam is the name of the setter's parameter.
func (v *varModel) setterParam() string {
	if v.set != nil {
		return v.set.Param.Name
	}
	return "p_value"
}

// gdvirtual returns the GDVIRTUAL macro that lets scripts override f.
func gdvirtual(c *classModel, f *funcModel) string {
	name := fmt.Sprintf("GDVIRTUAL%d", len(f.params))
	args := []string{f.f.Name}
	if !f.ret.void {
		name += "R"
		args = append([]string{tagged(c, f.ret)}, args...)
	}
	if f.isConst {
		name += "C"
	}
	for _, p := range f.params {
		args = append(args, tagged(c, p))
	}
	return name + "(" + strings.Join(args, ", ") + ")"
}

// trampolineDecl declares the method that binds f with the class's enum tags in place of enums.
func trampolineDecl(c *classModel, f *funcModel) string {
	prefix, suffix := "", ""
	if f.static {
		prefix = "static "
	}
	if f.isConst {
		suffix = " const"
	}
	return fmt.Sprintf("%s%s_gdpp_%s(%s)%s;", prefix, withSpace(tagged(c, f.ret)), f.f.Name, params(c, f.params, f.f.Params), suffix)
}

// externDecl declares the wrapper class of an extern. Its members are defined after the classes, which they
// may use.
func (u *unit) externDecl(w *writer, e *externModel) {
	w.ln("")
	w.ln("class %s {", e.name)
	w.ln("public:")
	w.ln("\tusing Base = %s;", e.base)
	w.ln("\tstatic constexpr const char *gdpp_name = %q;", e.name)
	w.ln("")
	w.ln("\texplicit %s(Base *p_object) :", e.name)
	w.ln("\t\t\t_gdpp_base(p_object) {}")
	w.ln("")
	for _, f := range e.funcs {
		w.ln("\t%s%s(%s) const;", withSpace(f.ret.cpp), f.f.Name, params(nil, f.params, f.f.Params))
		if f.rpc != nil {
			w.ln("\tError %s const;", rpcDecl(f))
		}
	}
	for _, v := range e.vars {
		w.ln("\t%s%s() const;", withSpace(v.t.cpp), v.getter)
		w.ln("\tvoid %s(%sp_value) const;", v.setter, withSpace(v.t.param()))
	}
	for _, s := range e.signals {
		w.ln("\tgdpp::Emitted %s(%s) const;", s.s.Name, params(nil, s.params, s.s.Params))
	}
	w.ln("")
	w.ln("private:")
	w.ln("\tBase *_gdpp_base;")
	w.ln("};")
}

// args returns the arguments that pass the parameters on to a call resolved by name, enums as integers.
func args(types []*gtype, list []*Param) string {
	var as []string
	for i, t := range types {
		a := list[i].Name
		if t.enum != nil {
			a = "static_cast<int64_t>(" + a + ")"
		}
		as = append(as, ", "+a)
	}
	return strings.Join(as, "")
}

// externDefs defines the members of an extern's wrapper class, which call the object's members by name.
func (u *unit) externDefs(w *writer, e *externModel) {
	for _, f := range e.funcs {
		w.ln("")
		w.ln("inline %s%s::%s(%s) const {", withSpace(f.ret.cpp), e.name, f.f.Name, params(nil, f.params, f.f.Params))
		call := fmt.Sprintf("_gdpp_base->call(%q%s)", f.f.Name, args(f.params, f.f.Params))
		switch {
		case f.deferred:
			w.ln("\t_gdpp_base->call_deferred(%q%s);", f.f.Name, args(f.params, f.f.Params))
		case f.ret.void:
			w.ln("\t%s;", call)
		default:
			w.ln("\treturn gdpp::from_variant<%s>(%s);", f.ret.cpp, call)
		}
		w.ln("}")
		if f.rpc != nil {
			w.ln("")
			w.ln("inline Error %s::%s const {", e.name, rpcDecl(f))
			w.ln("\tstatic_assert(std::is_base_of_v<Node, Base>, \"@rpc can only be used in externs that extend Node.\");")
			w.ln("\treturn _gdpp_base->%s;", rpcCall(f))
			w.ln("}")
		}
	}
	for _, v := range e.vars {
		w.ln("")
		w.ln("inline %s%s::%s() const {", withSpace(v.t.cpp), e.name, v.getter)
		w.ln("\treturn gdpp::from_variant<%s>(_gdpp_base->get(%q));", v.t.cpp, v.v.Name)
		w.ln("}")
		w.ln("")
		w.ln("inline void %s::%s(%sp_value) const {", e.name, v.setter, withSpace(v.t.param()))
		value := "p_value"
		if v.t.enum != nil {
			value = "static_cast<int64_t>(p_value)"
		}
		w.ln("\t_gdpp_base->set(%q, %s);", v.v.Name, value)
		w.ln("}")
	}
	for _, s := range e.signals {
		w.ln("")
		w.ln("inline gdpp::Emitted %s::%s(%s) const {", e.name, s.s.Name, params(nil, s.params, s.s.Params))
		w.ln("\treturn gdpp::Emitted{ _gdpp_base->emit_signal(%q%s) };", s.s.Name, args(s.params, s.s.Params))
		w.ln("}")
	}
}
