// GD++ runtime for syntax 0: helpers for the C++ that GD++ generates. Generated by GD++, do not edit.

#pragma once

#include <cstddef>
#include <cstdint>
#include <type_traits>

#include <godot_cpp/classes/engine.hpp>
#include <godot_cpp/classes/global_constants.hpp>
#include <godot_cpp/classes/node.hpp>
#include <godot_cpp/classes/project_settings.hpp>
#include <godot_cpp/classes/ref.hpp>
#include <godot_cpp/classes/ref_counted.hpp>
#include <godot_cpp/classes/resource.hpp>
#include <godot_cpp/classes/resource_loader.hpp>
#include <godot_cpp/core/binder_common.hpp>
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/core/gdvirtual.gen.inc>
#include <godot_cpp/core/method_ptrcall.hpp>
#include <godot_cpp/core/type_info.hpp>
#include <godot_cpp/variant/typed_array.hpp>
#include <godot_cpp/variant/typed_dictionary.hpp>
#include <godot_cpp/variant/utility_functions.hpp>
#include <godot_cpp/variant/variant.hpp>

// The C++ type of Godot's float.
typedef double float64_t;

// Godot's global scope functions, e.g. gd::print("Hello!").
using gd = godot::UtilityFunctions;

namespace gdpp {

using namespace godot;

// Emitted is the result of a signal's emit function. It's [[nodiscard]], so emitting a signal must be spelled
// `emit my_signal(42);`, which reads differently from a function call.
struct [[nodiscard]] Emitted {
	Error error;
};

// info returns the PropertyInfo of a value of type T named p_name, as bindings expose it.
template <typename T>
PropertyInfo info(const StringName &p_name, uint32_t p_usage = PROPERTY_USAGE_DEFAULT,
		PropertyHint p_hint = PROPERTY_HINT_NONE, const String &p_hint_string = "") {
	PropertyInfo result = GetTypeInfo<T>::get_class_info();
	result.name = p_name;
	result.usage = p_usage | (result.usage & (PROPERTY_USAGE_NIL_IS_VARIANT | PROPERTY_USAGE_CLASS_IS_ENUM));
	if constexpr (std::is_pointer_v<T>) {
		if constexpr (std::is_base_of_v<Node, std::remove_pointer_t<T>>) {
			result.hint = PROPERTY_HINT_NODE_TYPE;
		}
	}
	if (p_hint != PROPERTY_HINT_NONE) {
		result.hint = p_hint;
		result.hint_string = p_hint_string;
	}
	return result;
}

// add_property_category starts a category named p_name in the inspector, like GDScript's @export_category. Godot has
// no function for it, so it's a property without setter and getter, which godot-cpp's ClassDB doesn't allow.
inline void add_property_category(const StringName &p_class, const String &p_name) {
	PropertyInfo info(Variant::NIL, p_name, PROPERTY_HINT_NONE, "", PROPERTY_USAGE_CATEGORY);
	StringName none;
	GDExtensionPropertyInfo gdext_info = { GDEXTENSION_VARIANT_TYPE_NIL, info.name._native_ptr(), info.class_name._native_ptr(),
		info.hint, info.hint_string._native_ptr(), info.usage };
	gdextension_interface::classdb_register_extension_class_property(gdextension_interface::library, p_class._native_ptr(),
			&gdext_info, none._native_ptr(), none._native_ptr());
}

// rpc_config sets the RPC configuration of p_method on p_node, as @rpc declares it.
template <typename T>
void rpc_config(T *p_node, const StringName &p_method, int64_t p_mode, int64_t p_transfer_mode, bool p_call_local, int64_t p_channel) {
	static_assert(std::is_base_of_v<Node, T>, "@rpc can only be used in classes that extend Node.");
	Dictionary config;
	config["rpc_mode"] = p_mode;
	config["transfer_mode"] = p_transfer_mode;
	config["call_local"] = p_call_local;
	config["channel"] = p_channel;
	p_node->rpc_config(p_method, config);
}

// from_variant converts the result of a call resolved by name.
template <typename T>
T from_variant(const Variant &p_value) {
	if constexpr (std::is_enum_v<T>) {
		return static_cast<T>(p_value.operator int64_t());
	} else {
		return VariantCaster<T>::cast(p_value);
	}
}

// ExtPtr<T> points to an object of the extern T, whose base class isn't refcounted. Its members are called by
// name: ptr->foo() is ptr.get()->call("foo").
template <typename T>
class ExtPtr {
public:
	using Base = typename T::Base;

	ExtPtr() = default;
	ExtPtr(std::nullptr_t) {}
	ExtPtr(Base *p_object) :
			base_(p_object) {}

	Base *get() const { return base_; }
	Base *base() { return base_; }
	const Base *base() const { return base_; }
	explicit operator bool() const { return base_ != nullptr; }
	bool operator==(const ExtPtr &p_other) const { return base_ == p_other.base_; }
	operator Variant() const { return Variant(base_); }

	struct Arrow {
		T wrapper;
		T *operator->() { return &wrapper; }
	};
	Arrow operator->() const { return Arrow{ T(base_) }; }

private:
	Base *base_ = nullptr;
	Ref<RefCounted> keep_; // Keeps a refcounted object from memnew_ext alive until an ExtRef takes it.

	template <typename U>
	friend ExtPtr<U> memnew_ext();
};

// ExtRef<T> references an object of the extern T, whose base class is refcounted. Its members are called by
// name: ref->foo() is ref.get()->call("foo").
template <typename T>
class ExtRef {
public:
	using Base = typename T::Base;

	ExtRef() = default;
	ExtRef(std::nullptr_t) {}
	ExtRef(const Ref<Base> &p_object) :
			base_(p_object) {}
	ExtRef(Base *p_object) :
			base_(p_object) {}
	ExtRef(const ExtPtr<T> &p_object) :
			base_(p_object.get()) {}

	const Ref<Base> &get() const { return base_; }
	Ref<Base> &base() { return base_; }
	const Ref<Base> &base() const { return base_; }
	explicit operator bool() const { return base_.is_valid(); }
	bool operator==(const ExtRef &p_other) const { return base_ == p_other.base_; }
	operator Variant() const { return Variant(base_); }

	struct Arrow {
		T wrapper;
		T *operator->() { return &wrapper; }
	};
	Arrow operator->() const { return Arrow{ T(base_.ptr()) }; }

private:
	Ref<Base> base_;
};

// memnew_ext creates an object of the extern T, like memnew: an instance of the ClassDB class or global script class
// that T names.
template <typename T>
ExtPtr<T> memnew_ext() {
	StringName name = T::gdpp_name;
	Variant object;
	if (ClassDB::class_exists(name)) {
		object = ClassDB::instantiate(name);
	} else {
		TypedArray<Dictionary> classes = ProjectSettings::get_singleton()->get_global_class_list();
		for (int64_t i = 0; i < classes.size(); i++) {
			Dictionary c = classes[i];
			if (StringName(c["class"]) == name) {
				object = ResourceLoader::get_singleton()->load(c["path"])->call("new");
				break;
			}
		}
	}
	ExtPtr<T> result = Object::cast_to<typename T::Base>(object.operator Object *());
	ERR_FAIL_COND_V_MSG(!result, nullptr, String("Failed to create an object of the extern ") + T::gdpp_name + ".");
	result.keep_ = object;
	return result;
}

// memdelete_ext frees an object of the extern T, like memdelete. Refcounted objects are freed by their ExtRefs instead.
template <typename T>
void memdelete_ext(ExtPtr<T> p_object) {
	static_assert(!std::is_base_of_v<RefCounted, typename T::Base>, "Refcounted externs are freed by their ExtRefs.");
	memdelete(p_object.get());
}

// assert_message is the error printed by a failed gd_assert.
inline String assert_message(const char *p_condition, const String &p_message = "") {
	String result = String("Assertion failed: ") + p_condition;
	if (!p_message.is_empty()) {
		result += " - " + p_message;
	}
	return result + ".";
}

} // namespace gdpp

// gd_assert(condition) and gd_assert(condition, "message") mirror GDScript's assert: a failed condition prints an error.
// Like in GDScript, release builds skip the check and don't evaluate the condition. C's assert is a macro, so gd::assert
// can't be a function.
#ifdef DEBUG_ENABLED
#define gd_assert(m_condition, ...) \
	do { \
		if (!(m_condition)) { \
			ERR_PRINT(gdpp::assert_message(#m_condition, ##__VA_ARGS__)); \
		} \
	} while (0)
#else
#define gd_assert(m_condition, ...) ((void)0)
#endif

// memnew_ext(MyExtern) and memdelete_ext(ptr) mirror memnew and memdelete for ExtPtrs.
#define memnew_ext(m_class) gdpp::memnew_ext<m_class>()
#define memdelete_ext(m_object) gdpp::memdelete_ext(m_object)

// GDPP_STRING_NAME("name") is the StringName name, created on first use and reused after, like the engine's SNAME.
// Calls by name use it, so they don't intern the name, which locks a global mutex, on every call.
#define GDPP_STRING_NAME(m_name) ([]() -> const godot::StringName & { static const godot::StringName name(m_name, true); return name; })()

namespace godot {

// Bindings see an extern as its base class. The hint names the extern, so the editor only accepts matching objects.

template <typename T>
struct GetTypeInfo<gdpp::ExtPtr<T>> {
	static constexpr GDExtensionVariantType VARIANT_TYPE = GDEXTENSION_VARIANT_TYPE_OBJECT;
	static constexpr GDExtensionClassMethodArgumentMetadata METADATA = GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE;
	static inline PropertyInfo get_class_info() {
		PropertyHint hint = std::is_base_of_v<Node, typename T::Base> ? PROPERTY_HINT_NODE_TYPE : PROPERTY_HINT_NONE;
		return PropertyInfo(Variant::OBJECT, "", hint, T::gdpp_name, PROPERTY_USAGE_DEFAULT, T::Base::get_class_static());
	}
};

template <typename T>
struct GetTypeInfo<gdpp::ExtRef<T>> {
	static constexpr GDExtensionVariantType VARIANT_TYPE = GDEXTENSION_VARIANT_TYPE_OBJECT;
	static constexpr GDExtensionClassMethodArgumentMetadata METADATA = GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE;
	static inline PropertyInfo get_class_info() {
		PropertyHint hint = std::is_base_of_v<Resource, typename T::Base> ? PROPERTY_HINT_RESOURCE_TYPE : PROPERTY_HINT_NONE;
		return PropertyInfo(Variant::OBJECT, "", hint, T::gdpp_name, PROPERTY_USAGE_DEFAULT, T::Base::get_class_static());
	}
};

template <typename T>
struct PtrToArg<gdpp::ExtPtr<T>> {
	_FORCE_INLINE_ static gdpp::ExtPtr<T> convert(const void *p_ptr) {
		return PtrToArg<typename T::Base *>::convert(p_ptr);
	}
	typedef Object *EncodeT;
	_FORCE_INLINE_ static void encode(gdpp::ExtPtr<T> p_val, void *p_ptr) {
		PtrToArg<typename T::Base *>::encode(p_val.get(), p_ptr);
	}
};

template <typename T>
struct PtrToArg<gdpp::ExtRef<T>> {
	_FORCE_INLINE_ static gdpp::ExtRef<T> convert(const void *p_ptr) {
		return PtrToArg<Ref<typename T::Base>>::convert(p_ptr);
	}
	typedef Ref<typename T::Base> EncodeT;
	_FORCE_INLINE_ static void encode(gdpp::ExtRef<T> p_val, void *p_ptr) {
		PtrToArg<Ref<typename T::Base>>::encode(p_val.get(), p_ptr);
	}
};

template <typename T>
struct VariantCaster<gdpp::ExtPtr<T>> {
	static _FORCE_INLINE_ gdpp::ExtPtr<T> cast(const Variant &p_variant) {
		return Object::cast_to<typename T::Base>(p_variant.operator Object *());
	}
};

template <typename T>
struct VariantCaster<gdpp::ExtRef<T>> {
	static _FORCE_INLINE_ gdpp::ExtRef<T> cast(const Variant &p_variant) {
		return Ref<typename T::Base>(p_variant);
	}
};

} // namespace godot

// GDPP_ENUM_TAG makes m_tag, a class's stand-in for one of the package's enums, bind as the enum m_name
// (e.g. "MyNode.Suit"), since each class exposes its own copy of the enums it uses. Use it in namespace godot.
#define GDPP_ENUM_TAG(m_tag, m_name) \
	template <> \
	struct GetTypeInfo<m_tag> { \
		static constexpr GDExtensionVariantType VARIANT_TYPE = GDEXTENSION_VARIANT_TYPE_INT; \
		static constexpr GDExtensionClassMethodArgumentMetadata METADATA = GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE; \
		static inline PropertyInfo get_class_info() { \
			return PropertyInfo(Variant::INT, "", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_CLASS_IS_ENUM, m_name); \
		} \
	}; \
	template <> \
	struct VariantCaster<m_tag> { \
		static _FORCE_INLINE_ m_tag cast(const Variant &p_variant) { \
			return (m_tag)p_variant.operator int64_t(); \
		} \
	}; \
	template <> \
	struct PtrToArg<m_tag> { \
		_FORCE_INLINE_ static m_tag convert(const void *p_ptr) { \
			return m_tag(*reinterpret_cast<const int64_t *>(p_ptr)); \
		} \
		typedef int64_t EncodeT; \
		_FORCE_INLINE_ static void encode(m_tag p_val, void *p_ptr) { \
			*reinterpret_cast<int64_t *>(p_ptr) = p_val; \
		} \
	};
