package syntax_0

import (
	"fmt"
	"slices"
	"strings"
)

// source returns the C++ source of the file: method definitions and bindings.
func (u *unit) source() string {
	w := &writer{self: u.opts.CodeName, source: u.opts.SourceName}
	w.ln("// Generated by GD++ from %s, do not edit.", u.opts.SourceName)
	w.ln("")
	w.ln("#include %q", u.opts.HeaderName)
	header := map[string]bool{}
	for _, name := range u.headerNames() {
		header[name] = true
	}
	if incs := u.includes(u.sourceNames(), header); len(incs) > 0 {
		w.ln("")
		for _, inc := range incs {
			w.ln("#include %s", inc)
		}
	}
	for _, c := range u.topCode {
		if c.Impl {
			w.ln("")
			w.block(c.Body, "", "")
		}
	}
	w.ln("")
	w.ln("namespace godot {")
	u.aliases(w, u.sourceNames(), header)
	for _, c := range u.classes {
		u.classDefs(w, c)
	}
	w.ln("")
	w.ln("} // namespace godot")
	return w.String()
}

func (u *unit) classDefs(w *writer, c *classModel) {
	w.ln("")
	w.ln("#define This %s", c.name)
	w.ln("")
	w.ln("void %s::_bind_methods() {", c.name)
	u.bindings(w, c)
	w.ln("}")
	if c.needsCtor() {
		w.ln("")
		w.ln("%s::%s() {", c.name, c.name)
		for _, f := range c.funcs {
			if r := f.rpc; r != nil {
				w.ln("\tgdpp::rpc_config<This>(this, %q, %s, %s, %t, %s);", f.f.Name, r.mode, r.transfer, r.callLocal, r.channel)
			}
			if setter := processing[f.f.Name]; f.override && setter != "" {
				w.ln("\t%s(true);", setter)
			}
		}
		u.initializers(w, c, false)
		if c.ctor != nil {
			w.block(c.ctor, "\t{", "}")
		}
		w.ln("}")
	}
	if c.dtor != nil {
		w.ln("")
		w.ln("%s::~%s() {", c.name, c.name)
		w.block(c.dtor, "\t{", "}")
		w.ln("}")
	}
	if c.needsReady() {
		w.ln("")
		w.ln("void %s::_notification(int p_what) {", c.name)
		// Right before NOTIFICATION_READY, whose handlers call _ready. GDScript too runs @onready initializers first.
		w.ln("\tif (p_what != NOTIFICATION_POST_ENTER_TREE || gdpp::is_node_ready(this)) {")
		w.ln("\t\treturn;")
		w.ln("\t}")
		u.initializers(w, c, true)
		w.ln("}")
	}
	for _, f := range c.funcs {
		u.funcDef(w, c, f)
		defaultDefs(w, c, f)
		if f.rpc != nil {
			w.ln("")
			w.ln("Error %s::%s {", c.name, rpcDecl(f, params(nil, f.params, f.f.Params)))
			w.ln("\treturn %s;", rpcCall(f))
			w.ln("}")
		}
	}
	if c.hasOverrides() {
		overrideDefs(w, c)
	}
	for _, v := range c.vars {
		u.accessorDefs(w, c, v)
	}
	for _, s := range c.signals {
		w.ln("")
		w.ln("gdpp::Emitted %s::%s(%s) {", c.name, s.s.Name, params(nil, s.params, s.s.Params))
		w.ln("\treturn gdpp::Emitted{ emit_signal(%q%s) };", s.s.Name, args(s.params, s.s.Params))
		w.ln("}")
	}
	for _, code := range c.codes {
		if code.Impl {
			w.ln("")
			w.block(code.Body, "", "")
		}
	}
	w.ln("")
	w.ln("#undef This")
}

// initializers writes the assignments of the initial values of the class's vars: the @onready ones, or the others.
func (u *unit) initializers(w *writer, c *classModel, onready bool) {
	for _, v := range c.vars {
		init := v.v.Init
		if init == nil || v.onready != onready {
			continue
		}
		if init.Block != nil {
			w.block(init.Block, fmt.Sprintf("\t%s = [&]() -> %s {", v.v.Name, v.t.cpp), "}();")
		} else {
			w.user(init.Pos, "\t"+v.v.Name+" = ", init.Expr, ";")
		}
	}
}

// qualified returns the out-of-class declarator of a method of c, e.g. "int64_t MyNode::f(int64_t a) const".
func qualified(c *classModel, ret, name, params string, isConst bool) string {
	s := fmt.Sprintf("%s%s::%s(%s)", withSpace(ret), c.name, name, params)
	if isConst {
		s += " const"
	}
	return s
}

// castList converts arguments between enums and the class's tags: toTag converts enums to tags, else tags to enums.
func castList(c *classModel, types []*gtype, list []*Param, toTag bool) string {
	var as []string
	for i, t := range types {
		as = append(as, cast(c, t, list[i].Name, toTag))
	}
	return strings.Join(as, ", ")
}

func cast(c *classModel, t *gtype, expr string, toTag bool) string {
	switch {
	case t.enum == nil:
		return expr
	case toTag:
		return fmt.Sprintf("static_cast<%s>(%s)", tagName(c, t.enum), expr)
	}
	return fmt.Sprintf("static_cast<%s>(%s)", t.cpp, expr)
}

func (u *unit) funcDef(w *writer, c *classModel, f *funcModel) {
	w.ln("")
	w.ln("%s {", qualified(c, f.ret.cpp, f.f.Name, params(nil, f.params, f.f.Params), f.isConst))
	if !c.tool {
		// Like GDScript, only @tool classes run their code in the editor, which only loads debug builds.
		w.ln("#ifdef DEBUG_ENABLED")
		w.ln("\tif (Engine::get_singleton()->is_editor_hint()) {")
		if f.ret.void {
			w.ln("\t\treturn;")
		} else {
			w.ln("\t\treturn {};")
		}
		w.ln("\t}")
		w.ln("#endif")
	}
	if f.virtual {
		callArgs := castList(c, f.params, f.f.Params, true)
		if f.ret.void {
			w.ln("\tif (GDVIRTUAL_CALL(%s)) {", strings.Join(slices.DeleteFunc([]string{f.f.Name, callArgs}, func(s string) bool { return s == "" }), ", "))
			w.ln("\t\treturn;")
		} else {
			w.ln("\t%s _gdpp_ret;", tagged(c, f.ret))
			w.ln("\tif (GDVIRTUAL_CALL(%s)) {", strings.Join(slices.DeleteFunc([]string{f.f.Name, callArgs, "_gdpp_ret"}, func(s string) bool { return s == "" }), ", "))
			w.ln("\t\treturn %s;", cast(c, f.ret, "_gdpp_ret", false))
		}
		w.ln("\t}")
	}
	switch {
	case f.f.Body != nil:
		w.block(f.f.Body, "", "")
	case !f.ret.void:
		w.ln("\treturn {};")
	}
	w.ln("}")
	if f.virtual || f.override || !f.usesEnums() {
		return
	}
	w.ln("")
	w.ln("%s {", qualified(c, tagged(c, f.ret), "_gdpp_"+f.f.Name, params(c, f.params, f.f.Params), f.isConst))
	call := fmt.Sprintf("%s(%s)", f.f.Name, castList(c, f.params, f.f.Params, false))
	if f.ret.void {
		w.ln("\t%s;", call)
	} else {
		w.ln("\treturn %s;", cast(c, f.ret, call, true))
	}
	w.ln("}")
}

// defaultDefs defines the static methods that return the default values of f's parameters.
func defaultDefs(w *writer, c *classModel, f *funcModel) {
	for i, p := range f.f.Params {
		d := p.Default
		if d == nil {
			continue
		}
		w.ln("")
		w.ln("%s {", qualified(c, f.params[i].cpp, defaultName(f, p), "", false))
		if d.Block != nil {
			w.block(d.Block, "", "")
		} else {
			w.user(d.Pos, "\treturn ", d.Expr, ";")
		}
		w.ln("}")
	}
}

// overrideDefs defines the functions through which the engine calls the class's overrides, in engine builds: its
// patched GDVIRTUAL macros only call scripts and GDExtension classes otherwise.
func overrideDefs(w *writer, c *classModel) {
	var names []string
	for _, f := range c.funcs {
		if f.override {
			names = append(names, fmt.Sprintf("p_name == SNAME(%q)", f.f.Name))
		}
	}
	w.ln("")
	w.ln("#ifdef GDPP_ENGINE")
	w.ln("")
	w.ln("bool %s::_gdpp_has_virtual(const StringName &p_name) const {", c.name)
	w.ln("\treturn %s || %s::_gdpp_has_virtual(p_name);", strings.Join(names, " || "), c.base)
	w.ln("}")
	w.ln("")
	w.ln("bool %s::_gdpp_call_virtual(const StringName &p_name, const void **p_args, void *r_ret) const {", c.name)
	w.ln("\t%s *self = const_cast<%s *>(this);", c.name, c.name)
	for _, f := range c.funcs {
		if !f.override {
			continue
		}
		call, ret := "call_with_ptr_args", ""
		if !f.ret.void {
			call, ret = call+"_ret", ", r_ret"
		}
		if f.isConst {
			call += "c"
		}
		w.ln("\tif (p_name == SNAME(%q)) {", f.f.Name)
		w.ln("\t\t(void)&%s::_gdvirtual_%s_get_method_info; // Fails to compile if %s has no virtual %s.", c.base, f.f.Name, c.base, f.f.Name)
		w.ln("\t\t%s(self, &%s::%s, p_args%s);", call, c.name, f.f.Name, ret)
		w.ln("\t\treturn true;")
		w.ln("\t}")
	}
	w.ln("\treturn %s::_gdpp_call_virtual(p_name, p_args, r_ret);", c.base)
	w.ln("}")
	w.ln("")
	w.ln("#endif")
}

// accessorDefs defines the getter and setter of v, and their trampolines.
func (u *unit) accessorDefs(w *writer, c *classModel, v *varModel) {
	if v.getter != "" {
		w.ln("")
		w.ln("%s {", qualified(c, v.t.cpp, v.getter, "", true))
		if v.get != nil {
			w.block(v.get, "", "")
		} else {
			w.ln("\treturn %s;", v.v.Name)
		}
		w.ln("}")
	}
	if v.setter != "" {
		w.ln("")
		w.ln("%s {", qualified(c, "void", v.setter, withSpace(v.t.param())+v.setterParam(), false))
		if v.set != nil {
			w.block(v.set.Body, "", "")
		} else {
			w.ln("\t%s = p_value;", v.v.Name)
		}
		w.ln("}")
	}
	if !v.trampolined() {
		return
	}
	tag := tagName(c, v.t.enum)
	if v.getter != "" {
		w.ln("")
		w.ln("%s {", qualified(c, tag, "_gdpp_"+v.getter, "", true))
		w.ln("\treturn static_cast<%s>(%s());", tag, v.getter)
		w.ln("}")
	}
	if v.setter != "" {
		w.ln("")
		w.ln("%s {", qualified(c, "void", "_gdpp_"+v.setter, tag+" p_value", false))
		w.ln("\t%s(static_cast<%s>(p_value));", v.setter, v.t.cpp)
		w.ln("}")
	}
}

// method returns the D_METHOD expression for a method named name with the given parameters.
func method(name string, list ...string) string {
	quoted := []string{fmt.Sprintf("%q", name)}
	for _, p := range list {
		quoted = append(quoted, fmt.Sprintf("%q", p))
	}
	return "D_METHOD(" + strings.Join(quoted, ", ") + ")"
}

func paramNames(list []*Param) []string {
	var names []string
	for _, p := range list {
		names = append(names, p.Name)
	}
	return names
}

// info returns the gdpp::info expression for a value of type t named name, as class c binds it.
func info(c *classModel, t *gtype, name, usage, hint, hintString string) string {
	s := fmt.Sprintf("gdpp::info<%s>(%q", tagged(c, t), name)
	if usage != "" {
		s += ", " + usage
	}
	if hint != "" && hint != "PROPERTY_HINT_NONE" {
		s += fmt.Sprintf(", %s, %q", hint, hintString)
	}
	return s + ")"
}

// bindings writes the body of _bind_methods.
func (u *unit) bindings(w *writer, c *classModel) {
	for _, f := range c.funcs {
		// The method, followed by the default values of its parameters.
		ref := fmt.Sprintf("&%s::%s", c.name, f.f.Name)
		if f.usesEnums() {
			ref = fmt.Sprintf("&%s::_gdpp_%s", c.name, f.f.Name)
		}
		names := paramNames(f.f.Params)
		for i, p := range f.f.Params {
			if p.Default == nil {
				continue
			}
			value := defaultName(f, p) + "()"
			if f.params[i].enum != nil {
				value = "static_cast<int64_t>(" + value + ")"
			}
			ref += ", DEFVAL(" + value + ")"
		}
		switch {
		case f.override:
		case f.virtual:
			quoted := []string{f.f.Name}
			for _, n := range names {
				quoted = append(quoted, fmt.Sprintf("%q", n))
			}
			w.ln("\tGDVIRTUAL_BIND(%s);", strings.Join(quoted, ", "))
		case f.static:
			w.ln("\tClassDB::bind_static_method(get_class_static(), %s, %s);", method(f.f.Name, names...), ref)
		default:
			w.ln("\tClassDB::bind_method(%s, %s);", method(f.f.Name, names...), ref)
		}
	}
	for _, v := range c.vars {
		for _, s := range v.sections {
			if s.ann.Name == "export_category" {
				w.ln("\tgdpp::add_property_category(get_class_static(), %q);", s.name)
			} else {
				w.ln("\tClassDB::add_property_%s(get_class_static(), %q, %q);", strings.TrimPrefix(s.ann.Name, "export_"), s.name, s.prefix)
			}
		}
		prefix := "&" + c.name + "::"
		if v.trampolined() {
			prefix += "_gdpp_"
		}
		if v.getter != "" {
			w.ln("\tClassDB::bind_method(%s, %s%s);", method(v.getter), prefix, v.getter)
		}
		if v.setter != "" {
			w.ln("\tClassDB::bind_method(%s, %s%s);", method(v.setter, "value"), prefix, v.setter)
		}
		w.ln("\tClassDB::add_property(get_class_static(), %s, %q, %q);",
			info(c, v.t, v.v.Name, v.usage, v.hint, v.hintString), v.setter, v.getter)
	}
	for _, s := range c.signals {
		infos := []string{fmt.Sprintf("%q", s.s.Name)}
		for i, t := range s.params {
			infos = append(infos, info(c, t, s.s.Params[i].Name, "", "", ""))
		}
		w.ln("\tClassDB::add_signal(get_class_static(), MethodInfo(%s));", strings.Join(infos, ", "))
	}
	for _, k := range c.consts {
		w.ln("\tClassDB::bind_integer_constant(get_class_static(), \"\", %q, %s);", k.Name, k.Name)
	}
	for _, e := range c.enums {
		for _, v := range e.values {
			w.ln("\tClassDB::bind_integer_constant(get_class_static(), %q, %q, static_cast<int64_t>(%s::%s));",
				e.name, upperSnake(e.name)+"_"+v.Name, e.name, v.Name)
		}
	}
}

// typeNames returns the names used in t, including its type arguments.
func typeNames(t *Type) []string {
	if t == nil {
		return nil
	}
	names := []string{t.Name}
	for _, a := range t.Args {
		names = append(names, typeNames(a)...)
	}
	return names
}

// headerNames returns the names used in the header: bases, API types, imports and decl code.
func (u *unit) headerNames() []string {
	var names []string
	add := func(ts ...*Type) {
		for _, t := range ts {
			names = append(names, typeNames(t)...)
		}
	}
	code := func(b *Block) { names = append(names, identifiers(b.Text)...) }
	addFuncs := func(funcs []*funcModel, vars []*varModel, signals []*signalModel) {
		for _, f := range funcs {
			add(f.f.Return)
			for _, p := range f.f.Params {
				add(p.Type)
			}
		}
		for _, v := range vars {
			add(v.v.Type)
			for _, d := range v.decls {
				code(d)
			}
		}
		for _, s := range signals {
			for _, p := range s.s.Params {
				add(p.Type)
			}
		}
	}
	for _, c := range u.topCode {
		if c.Decl {
			code(c.Body)
		}
	}
	for _, e := range u.externs {
		names = append(names, e.base)
		addFuncs(e.funcs, e.vars, e.signals)
	}
	for _, c := range u.classes {
		names = append(names, c.base)
		add(c.imports...)
		addFuncs(c.funcs, c.vars, c.signals)
		for _, code := range c.codes {
			if code.Decl {
				names = append(names, identifiers(code.Body.Text)...)
			}
		}
	}
	return names
}

// sourceNames returns the names used in the source: function bodies, initial values and impl code.
func (u *unit) sourceNames() []string {
	var names []string
	code := func(b *Block) {
		if b != nil {
			names = append(names, identifiers(b.Text)...)
		}
	}
	for _, c := range u.topCode {
		if c.Impl {
			code(c.Body)
		}
	}
	for _, c := range u.classes {
		code(c.ctor)
		code(c.dtor)
		for _, f := range c.funcs {
			code(f.f.Body)
			for _, p := range f.f.Params {
				if d := p.Default; d != nil {
					code(d.Block)
					names = append(names, identifiers(d.Expr)...)
				}
			}
			if f.rpc != nil {
				names = append(names, "MultiplayerAPI", "MultiplayerPeer")
			}
		}
		for _, v := range c.vars {
			code(v.get)
			if v.set != nil {
				code(v.set.Body)
			}
			if init := v.v.Init; init != nil {
				code(init.Block)
				names = append(names, identifiers(init.Expr)...)
			}
		}
		for _, cd := range c.codes {
			if cd.Impl {
				code(cd.Body)
			}
		}
	}
	return names
}

// includes returns the sorted includes of the dependencies named in names, except those in exclude and those
// that a noimport suppresses.
func (u *unit) includes(names []string, exclude map[string]bool) []string {
	noimport := map[string]bool{}
	for _, c := range u.classes {
		for _, t := range c.noimports {
			noimport[t.Name] = true
		}
	}
	var incs []string
	for _, name := range names {
		if s := u.symbols[name]; s != nil && s.include != "" && !exclude[name] && !noimport[name] && !slices.Contains(incs, s.include) {
			incs = append(incs, s.include)
		}
	}
	slices.Sort(incs)
	return incs
}

// aliases writes the aliases of the dependencies named in names whose C++ name differs, except those in exclude.
func (u *unit) aliases(w *writer, names []string, exclude map[string]bool) {
	var lines []string
	for _, name := range names {
		if s := u.symbols[name]; s != nil && s.cpp != "" && !exclude[name] {
			lines = append(lines, fmt.Sprintf("using %s = %s;", name, s.cpp))
		}
	}
	slices.Sort(lines)
	if lines = slices.Compact(lines); len(lines) > 0 {
		w.ln("")
		for _, l := range lines {
			w.ln("%s", l)
		}
	}
}
