// Generated by GD++, do not edit.

{{if .AsyncClass -}}
#include <atomic>
#include <mutex>
{{end -}}
#include <type_traits>

#include <gdextension_interface.h>
{{- if .AsyncClass}}
#include <godot_cpp/classes/ref.hpp>
#include <godot_cpp/classes/ref_counted.hpp>
#include <godot_cpp/classes/worker_thread_pool.hpp>
{{- end}}
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/core/defs.hpp>
#include <godot_cpp/godot.hpp>
{{range .Includes}}
#include {{.}}{{end}}

using namespace godot;
{{- if .AsyncClass}}

// {{.AsyncClass}} is the package's class of tasks, which Async types name: a job
// that runs on the WorkerThreadPool, e.g. the body of an @onthread function, and
// its result once done. It's thread-safe. GD++ code calls its methods by name,
// so it works with the tasks of other packages too.
class {{.AsyncClass}} : public RefCounted {
	GDCLASS({{.AsyncClass}}, RefCounted)

public:
	bool is_done() const { return done.load(std::memory_order_acquire); }

	// wait waits for the job to finish, and returns its result.
	Variant wait() {
		join();
		return get_result();
	}

	// get_result returns the result. The job must be done: debug builds check
	// it, release builds don't.
	Variant get_result() const {
#ifdef DEBUG_ENABLED
		ERR_FAIL_COND_V_MSG(!is_done(), Variant(), "The task isn't done yet. Check is_done() before get_result(), or call wait().");
#endif
		return result;
	}

	// _gdpp_start runs p_job on the WorkerThreadPool, as the task named p_name.
	void _gdpp_start(const Callable &p_job, const String &p_name) {
#ifdef DEBUG_ENABLED
		ERR_FAIL_COND_MSG(id >= 0, "The task has already started.");
#endif
		job = p_job;
		running = Ref<RefCounted>(this);
		done.store(false, std::memory_order_relaxed); // Before the task starts, and before other threads see the object.
		id = WorkerThreadPool::get_singleton()->add_task(callable_mp(this, &{{.AsyncClass}}::run), false, p_name);
	}

	~{{.AsyncClass}}() { join(); }

protected:
	static void _bind_methods() {
		ClassDB::bind_method(D_METHOD("is_done"), &{{.AsyncClass}}::is_done);
		ClassDB::bind_method(D_METHOD("wait"), &{{.AsyncClass}}::wait);
		ClassDB::bind_method(D_METHOD("get_result"), &{{.AsyncClass}}::get_result);
		ClassDB::bind_method(D_METHOD("_gdpp_start", "job", "name"), &{{.AsyncClass}}::_gdpp_start);
	}

private:
	int64_t id = -1;
	Callable job;
	Ref<RefCounted> running; // Keeps the object alive while the job runs.
	Variant result; // Set before done.
	std::atomic<bool> done = true; // Until started: an object that runs nothing, e.g. from new(), is done, without result.
	std::mutex mutex;
	bool waited = false; // Godot requires waiting for each task once.

	void run() {
		result = job.call();
		job = Callable(); // Frees what the job holds, e.g. the object it was called on.
		done.store(true, std::memory_order_release);
		Ref<RefCounted> self = running;
		running.unref();
		// Freeing self may free this object, whose destructor then runs in this task.
	}

	void join() {
		std::lock_guard<std::mutex> lock(mutex);
		if (waited || id < 0) {
			return;
		}
		waited = true;
		if (WorkerThreadPool::get_singleton()->get_caller_task_id() == id) {
			// A task can't wait for itself, so the main thread waits for it once it's done.
			callable_mp_static(&{{.AsyncClass}}::join_task).call_deferred(id);
			return;
		}
		WorkerThreadPool::get_singleton()->wait_for_task_completion(id);
	}

	static void join_task(int64_t p_id) {
		WorkerThreadPool::get_singleton()->wait_for_task_completion(p_id);
	}
};
{{- end}}

template <typename T>
constexpr bool gdpp_is_package_class = false{{range .Classes}} || std::is_same_v<T, {{.}}>{{end}};

// Runtime classes are C++ classes without tool and GD++ classes without @tool:
// in the editor, Godot makes placeholders of them that store their properties
// but run none of their code.
template <typename T>
constexpr bool gdpp_is_runtime_class = false{{range .RuntimeClasses}} || std::is_same_v<T, {{.}}>{{end}};

// Registers T, after its parent if that's a class of this package too, since
// Godot requires parents to be registered first.
template <typename T>
static void gdpp_register_class() {
	static bool registered = false;
	if (registered) {
		return;
	}
	registered = true;
	if constexpr (gdpp_is_package_class<typename T::parent_type>) {
		gdpp_register_class<typename T::parent_type>();
	}
	if constexpr (gdpp_is_runtime_class<T>) {
		GDREGISTER_RUNTIME_CLASS(T);
	} else {
		GDREGISTER_CLASS(T);
	}
}

static void gdpp_initialize(ModuleInitializationLevel p_level) {
	if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
		return;
	}
{{- if .AsyncClass}}
	GDREGISTER_CLASS({{.AsyncClass}});
{{- end}}
{{- range .Classes}}
	gdpp_register_class<{{.}}>();
{{- end}}
}

static void gdpp_uninitialize(ModuleInitializationLevel p_level) {}

extern "C" GDExtensionBool GDE_EXPORT gdpp_library_init(GDExtensionInterfaceGetProcAddress p_get_proc_address, GDExtensionClassLibraryPtr p_library, GDExtensionInitialization *r_initialization) {
	GDExtensionBinding::InitObject init_obj(p_get_proc_address, p_library, r_initialization);
	init_obj.register_initializer(gdpp_initialize);
	init_obj.register_terminator(gdpp_uninitialize);
	init_obj.set_minimum_library_initialization_level(MODULE_INITIALIZATION_LEVEL_SCENE);
	return init_obj.init();
}
