// Generated by GD++, do not edit.

#include <type_traits>

#include <gdextension_interface.h>
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/core/defs.hpp>
#include <godot_cpp/godot.hpp>
{{range .Includes}}
#include {{.}}{{end}}

using namespace godot;
{{template "register_classes" .}}
static void gdpp_initialize(ModuleInitializationLevel p_level) {
	if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
		return;
	}
{{- range .Classes}}
	gdpp_register_class<{{.}}>();
{{- end}}
}

static void gdpp_uninitialize(ModuleInitializationLevel p_level) {}

extern "C" GDExtensionBool GDE_EXPORT gdpp_library_init(GDExtensionInterfaceGetProcAddress p_get_proc_address, GDExtensionClassLibraryPtr p_library, GDExtensionInitialization *r_initialization) {
	GDExtensionBinding::InitObject init_obj(p_get_proc_address, p_library, r_initialization);
	init_obj.register_initializer(gdpp_initialize);
	init_obj.register_terminator(gdpp_uninitialize);
	init_obj.set_minimum_library_initialization_level(MODULE_INITIALIZATION_LEVEL_SCENE);
	return init_obj.init();
}
