// Generated by GD++, do not edit.

#include <type_traits>

#include <gdextension_interface.h>
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/core/defs.hpp>
#include <godot_cpp/godot.hpp>
{{range .Includes}}
#include {{.}}{{end}}

using namespace godot;

template <typename T>
constexpr bool gdpp_is_package_class = false{{range .Classes}} || std::is_same_v<T, {{.}}>{{end}};

// Runtime classes are GD++ classes without @tool: in the editor, Godot makes
// placeholders of them that store their properties but run none of their code.
template <typename T>
constexpr bool gdpp_is_runtime_class = false{{range .RuntimeClasses}} || std::is_same_v<T, {{.}}>{{end}};

// Registers T, after its parent if that's a class of this package too, since
// Godot requires parents to be registered first.
template <typename T>
static void gdpp_register_class() {
	static bool registered = false;
	if (registered) {
		return;
	}
	registered = true;
	if constexpr (gdpp_is_package_class<typename T::parent_type>) {
		gdpp_register_class<typename T::parent_type>();
	}
	if constexpr (gdpp_is_runtime_class<T>) {
		GDREGISTER_RUNTIME_CLASS(T);
	} else {
		GDREGISTER_CLASS(T);
	}
}

static void gdpp_initialize(ModuleInitializationLevel p_level) {
	if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
		return;
	}
{{- range .Classes}}
	gdpp_register_class<{{.}}>();
{{- end}}
}

static void gdpp_uninitialize(ModuleInitializationLevel p_level) {}

extern "C" GDExtensionBool GDE_EXPORT gdpp_library_init(GDExtensionInterfaceGetProcAddress p_get_proc_address, GDExtensionClassLibraryPtr p_library, GDExtensionInitialization *r_initialization) {
	GDExtensionBinding::InitObject init_obj(p_get_proc_address, p_library, r_initialization);
	init_obj.register_initializer(gdpp_initialize);
	init_obj.register_terminator(gdpp_uninitialize);
	init_obj.set_minimum_library_initialization_level(MODULE_INITIALIZATION_LEVEL_SCENE);
	return init_obj.init();
}
