// GD++ runtime for @gpu functions, syntax 1: kernels on the GPU through Godot's RenderingDevice, and their CPU
// fallback. Generated by GD++, do not edit.

#ifndef GDPP_SYNTAX_1_GPU_HPP
#define GDPP_SYNTAX_1_GPU_HPP

#include <array>
#include <cmath>
#include <condition_variable>
#include <cstring>
#include <limits>
#include <memory>
#include <thread>

#include <gd++/syntax_1.hpp>

#include <godot_cpp/classes/image.hpp>
#include <godot_cpp/classes/image_texture.hpp>
#include <godot_cpp/classes/rd_sampler_state.hpp>
#include <godot_cpp/classes/rd_shader_source.hpp>
#include <godot_cpp/classes/rd_shader_spirv.hpp>
#include <godot_cpp/classes/rd_texture_format.hpp>
#include <godot_cpp/classes/rd_texture_view.hpp>
#include <godot_cpp/classes/rd_uniform.hpp>
#include <godot_cpp/classes/rendering_device.hpp>
#include <godot_cpp/classes/rendering_server.hpp>
#include <godot_cpp/classes/texture2d.hpp>
#include <godot_cpp/classes/texture2drd.hpp>

#if defined(_MSC_VER) && !defined(__clang__)
#include <intrin.h>
#endif

// GLSL in C++: the types and built-in functions of GLSL compute shaders, so the body of a @gpu function also compiles
// as C++, for its CPU fallback. The generated code opens it with `using namespace gdpp::glsl`.
namespace gdpp::glsl {

using godot::Color;
using godot::Vector2;
using godot::Vector2i;
using godot::Vector3;
using godot::Vector3i;
using godot::Vector4;
using godot::Vector4i;

typedef unsigned int uint; // As glibc's, so the two don't clash.

template <typename T, int N>
struct vec;

// is_vec tells vectors from scalars.
template <typename T>
struct is_vec : std::false_type {};
template <typename T, int N>
struct is_vec<vec<T, N>> : std::true_type {};

// components is how many components a scalar (1) or a vector has.
template <typename T>
struct components : std::integral_constant<int, 1> {};
template <typename T, int N>
struct components<vec<T, N>> : std::integral_constant<int, N> {};

// scalar_of is the component type of a vector, or the scalar itself.
template <typename T>
struct scalar_of {
	using type = T;
};
template <typename T, int N>
struct scalar_of<vec<T, N>> {
	using type = T;
};

// Each vector's components, named like GLSL's: xyzw, rgba and stpq.
template <typename T, int N>
struct vec_storage;
template <typename T>
struct vec_storage<T, 2> {
	union {
		struct {
			T x, y;
		};
		struct {
			T r, g;
		};
		struct {
			T s, t;
		};
		T data[2];
	};
};
template <typename T>
struct vec_storage<T, 3> {
	union {
		struct {
			T x, y, z;
		};
		struct {
			T r, g, b;
		};
		struct {
			T s, t, p;
		};
		T data[3];
	};
};
template <typename T>
struct vec_storage<T, 4> {
	union {
		struct {
			T x, y, z, w;
		};
		struct {
			T r, g, b, a;
		};
		struct {
			T s, t, p, q;
		};
		T data[4];
	};
};

// is_arithmetic is true for the scalars that convert to vector components.
template <typename T>
inline constexpr bool is_arithmetic = std::is_arithmetic_v<T>;

// count_components is the number of components of all of As together.
template <typename... As>
inline constexpr int count_components = (0 + ... + components<std::decay_t<As>>::value);

template <typename T, int N>
struct SwizzleRef;

// vec is GLSL's vec2-4, ivec2-4, uvec2-4 and bvec2-4: T is float, int, uint or bool.
template <typename T, int N>
struct vec : vec_storage<T, N> {
	using vec_storage<T, N>::data;

	// Zero.
	vec() {
		for (int i = 0; i < N; i++) {
			data[i] = T();
		}
	}
	// A scalar in every component, e.g. vec3(1.0).
	template <typename S, std::enable_if_t<is_arithmetic<S>, int> = 0>
	explicit vec(S p_value) {
		for (int i = 0; i < N; i++) {
			data[i] = T(p_value);
		}
	}
	// Components from scalars and vectors, in order, e.g. vec3(v.xy, 1.0).
	template <typename A, typename B, typename... Cs, std::enable_if_t<count_components<A, B, Cs...> == N, int> = 0>
	explicit vec(const A &p_a, const B &p_b, const Cs &...p_cs) {
		T *out = data;
		put(out, p_a);
		put(out, p_b);
		(put(out, p_cs), ...);
	}
	// The first N components of a longer vector, e.g. vec3(v4).
	template <typename U, int M, std::enable_if_t<(M > N), int> = 0>
	explicit vec(const vec<U, M> &p_other) {
		for (int i = 0; i < N; i++) {
			data[i] = T(p_other.data[i]);
		}
	}
	// Another component type, e.g. vec3(iv): implicit from integers to floats, as in GLSL.
	template <typename U, std::enable_if_t<!std::is_same_v<U, T> && std::is_integral_v<U> && std::is_floating_point_v<T>, int> = 0>
	vec(const vec<U, N> &p_other) {
		for (int i = 0; i < N; i++) {
			data[i] = T(p_other.data[i]);
		}
	}
	template <typename U, std::enable_if_t<!std::is_same_v<U, T> && !(std::is_integral_v<U> && std::is_floating_point_v<T>), int> = 0>
	explicit vec(const vec<U, N> &p_other) {
		for (int i = 0; i < N; i++) {
			data[i] = T(p_other.data[i]);
		}
	}
	vec(const vec &p_other) {
		for (int i = 0; i < N; i++) {
			data[i] = p_other.data[i];
		}
	}
	vec &operator=(const vec &p_other) {
		for (int i = 0; i < N; i++) {
			data[i] = p_other.data[i];
		}
		return *this;
	}

	// From and to Godot's vectors.
	template <typename G, std::enable_if_t<std::is_same_v<G, Vector2> || std::is_same_v<G, Vector2i> || std::is_same_v<G, Vector3> || std::is_same_v<G, Vector3i> ||
							   std::is_same_v<G, Vector4> || std::is_same_v<G, Vector4i>,
					   int> = 0>
	explicit vec(const G &p_godot) {
		for (int i = 0; i < N; i++) {
			data[i] = T(p_godot[i]);
		}
	}
	explicit vec(const Color &p_color) {
		const float c[4] = { p_color.r, p_color.g, p_color.b, p_color.a };
		for (int i = 0; i < N; i++) {
			data[i] = T(c[i]);
		}
	}
	operator Vector2() const {
		static_assert(N == 2, "Only a vec2 converts to a Vector2.");
		return Vector2(real_t(data[0]), real_t(data[1]));
	}
	operator Vector2i() const {
		static_assert(N == 2, "Only an ivec2 converts to a Vector2i.");
		return Vector2i(int32_t(data[0]), int32_t(data[1]));
	}
	operator Vector3() const {
		static_assert(N == 3, "Only a vec3 converts to a Vector3.");
		return Vector3(real_t(data[0]), real_t(data[1]), real_t(data[2]));
	}
	operator Vector3i() const {
		static_assert(N == 3, "Only an ivec3 converts to a Vector3i.");
		return Vector3i(int32_t(data[0]), int32_t(data[1]), int32_t(data[2]));
	}
	operator Vector4() const {
		static_assert(N == 4, "Only a vec4 converts to a Vector4.");
		return Vector4(real_t(data[0]), real_t(data[1]), real_t(data[2]), real_t(data[3]));
	}
	operator Color() const {
		static_assert(N == 4, "Only a vec4 converts to a Color.");
		return Color(float(data[0]), float(data[1]), float(data[2]), float(data[3]));
	}

	T &operator[](int p_index) { return data[p_index]; }
	const T &operator[](int p_index) const { return data[p_index]; }

	// A swizzle, e.g. v.xy, which GD++ writes as v.swizzle<0, 1>(): a copy of the components.
	template <int... I>
	vec<T, int(sizeof...(I))> swizzle() const {
		if constexpr (sizeof...(I) == 1) {
			return vec<T, 1>(data[I]...);
		} else {
			return vec<T, int(sizeof...(I))>(data[I]...);
		}
	}
	// A swizzle that's assigned to, e.g. v.xy = w, which GD++ writes as v.swizzle_ref<0, 1>() = w.
	template <int... I>
	SwizzleRef<vec, int(sizeof...(I))> swizzle_ref() {
		return SwizzleRef<vec, int(sizeof...(I))>{ *this, { I... } };
	}

	// GLSL's v.length() is the number of components. Not to be confused with length(v).
	static constexpr int length() { return N; }

	vec &operator+=(const vec &p_other) { return each([&](int i) { data[i] += p_other.data[i]; }); }
	vec &operator-=(const vec &p_other) { return each([&](int i) { data[i] -= p_other.data[i]; }); }
	vec &operator*=(const vec &p_other) { return each([&](int i) { data[i] *= p_other.data[i]; }); }
	vec &operator/=(const vec &p_other) { return each([&](int i) { data[i] /= p_other.data[i]; }); }
	template <typename S, std::enable_if_t<is_arithmetic<S>, int> = 0>
	vec &operator+=(S p_s) { return each([&](int i) { data[i] += T(p_s); }); }
	template <typename S, std::enable_if_t<is_arithmetic<S>, int> = 0>
	vec &operator-=(S p_s) { return each([&](int i) { data[i] -= T(p_s); }); }
	template <typename S, std::enable_if_t<is_arithmetic<S>, int> = 0>
	vec &operator*=(S p_s) { return each([&](int i) { data[i] *= T(p_s); }); }
	template <typename S, std::enable_if_t<is_arithmetic<S>, int> = 0>
	vec &operator/=(S p_s) { return each([&](int i) { data[i] /= T(p_s); }); }
	vec &operator++() { return each([&](int i) { data[i]++; }); }
	vec &operator--() { return each([&](int i) { data[i]--; }); }
	vec operator++(int) {
		vec old = *this;
		++*this;
		return old;
	}
	vec operator--(int) {
		vec old = *this;
		--*this;
		return old;
	}

private:
	template <typename F>
	vec &each(F p_f) {
		for (int i = 0; i < N; i++) {
			p_f(i);
		}
		return *this;
	}
	template <typename A>
	static void put(T *&p_out, const A &p_value) {
		if constexpr (is_vec<A>::value) {
			for (int i = 0; i < components<A>::value; i++) {
				*p_out++ = T(p_value.data[i]);
			}
		} else {
			*p_out++ = T(p_value);
		}
	}
};

// vec<T, 1> is a swizzle of one component, e.g. v.swizzle<2>(): it converts to T.
template <typename T>
struct vec<T, 1> {
	T data[1];
	explicit vec(T p_value) :
			data{ p_value } {}
	operator T() const { return data[0]; }
};

// SwizzleRef is what an assigned swizzle refers to: the components of v at index.
template <typename V, int K>
struct SwizzleRef {
	V &v;
	int index[K];

	operator vec<typename scalar_of<V>::type, K>() const {
		vec<typename scalar_of<V>::type, K> result;
		for (int i = 0; i < K; i++) {
			result.data[i] = v.data[index[i]];
		}
		return result;
	}
	SwizzleRef &operator=(const vec<typename scalar_of<V>::type, K> &p_value) {
		for (int i = 0; i < K; i++) {
			v.data[index[i]] = p_value.data[i];
		}
		return *this;
	}
	template <typename O>
	SwizzleRef &operator+=(const O &p_value) { return *this = vec<typename scalar_of<V>::type, K>(*this) + p_value; }
	template <typename O>
	SwizzleRef &operator-=(const O &p_value) { return *this = vec<typename scalar_of<V>::type, K>(*this) - p_value; }
	template <typename O>
	SwizzleRef &operator*=(const O &p_value) { return *this = vec<typename scalar_of<V>::type, K>(*this) * p_value; }
	template <typename O>
	SwizzleRef &operator/=(const O &p_value) { return *this = vec<typename scalar_of<V>::type, K>(*this) / p_value; }
};

typedef vec<float, 2> vec2;
typedef vec<float, 3> vec3;
typedef vec<float, 4> vec4;
typedef vec<int, 2> ivec2;
typedef vec<int, 3> ivec3;
typedef vec<int, 4> ivec4;
typedef vec<uint, 2> uvec2;
typedef vec<uint, 3> uvec3;
typedef vec<uint, 4> uvec4;
typedef vec<bool, 2> bvec2;
typedef vec<bool, 3> bvec3;
typedef vec<bool, 4> bvec4;

// map applies p_f to each component of vectors, or to scalars.
template <typename F, typename A>
auto map(F p_f, const A &p_a) {
	if constexpr (is_vec<A>::value) {
		using R = decltype(p_f(p_a.data[0]));
		vec<R, components<A>::value> result;
		for (int i = 0; i < components<A>::value; i++) {
			result.data[i] = p_f(p_a.data[i]);
		}
		return result;
	} else {
		return p_f(p_a);
	}
}

// common is the GLSL type that two operands of a built-in or an operator share: the vector if one is, else the
// scalar, where any floating-point scalar makes it float.
template <typename A, typename B>
struct common {
	using type = std::conditional_t<std::is_floating_point_v<A> || std::is_floating_point_v<B>, float,
			std::conditional_t<std::is_same_v<A, bool> && std::is_same_v<B, bool>, bool,
					std::conditional_t<std::is_unsigned_v<A> && !std::is_same_v<A, bool> || std::is_unsigned_v<B> && !std::is_same_v<B, bool>, uint, int>>>;
};
template <typename T, int N, typename B>
struct common<vec<T, N>, B> {
	using type = vec<T, N>;
};
template <typename A, typename T, int N>
struct common<A, vec<T, N>> {
	using type = vec<T, N>;
};
template <typename T, int N, typename U, int M>
struct common<vec<T, N>, vec<U, M>> {
	using type = vec<std::conditional_t<std::is_floating_point_v<T> || std::is_floating_point_v<U>, float, T>, N>;
};
template <typename A, typename B>
using common_t = typename common<A, B>::type;

// at returns component i of a vector, or the scalar.
template <typename A>
auto at(const A &p_a, int p_i) {
	if constexpr (is_vec<A>::value) {
		return p_a.data[p_i];
	} else {
		return p_a;
	}
}

// zip applies p_f to the components of p_a and p_b at each index, with the result type R.
template <typename R, typename F, typename A, typename B>
R zip(F p_f, const A &p_a, const B &p_b) {
	if constexpr (is_vec<R>::value) {
		R result;
		for (int i = 0; i < components<R>::value; i++) {
			result.data[i] = p_f(at(p_a, i), at(p_b, i));
		}
		return result;
	} else {
		return R(p_f(p_a, p_b));
	}
}

// zip3 is zip with three operands.
template <typename R, typename F, typename A, typename B, typename C>
R zip3(F p_f, const A &p_a, const B &p_b, const C &p_c) {
	if constexpr (is_vec<R>::value) {
		R result;
		for (int i = 0; i < components<R>::value; i++) {
			result.data[i] = p_f(at(p_a, i), at(p_b, i), at(p_c, i));
		}
		return result;
	} else {
		return R(p_f(p_a, p_b, p_c));
	}
}

// Operators on vectors, component-wise, with a scalar on either side.
template <typename A, typename B>
inline constexpr bool vec_operands = (is_vec<A>::value || is_vec<B>::value) && (is_vec<A>::value || is_arithmetic<A>) && (is_vec<B>::value || is_arithmetic<B>);

#define GDPP_GLSL_BINARY(m_op)                                                                           \
	template <typename A, typename B, std::enable_if_t<vec_operands<A, B>, int> = 0>                     \
	common_t<A, B> operator m_op(const A &p_a, const B &p_b) {                                           \
		using S = typename scalar_of<common_t<A, B>>::type;                                              \
		return zip<common_t<A, B>>([](auto p_x, auto p_y) { return S(S(p_x) m_op S(p_y)); }, p_a, p_b); \
	}
GDPP_GLSL_BINARY(+)
GDPP_GLSL_BINARY(-)
GDPP_GLSL_BINARY(*)
GDPP_GLSL_BINARY(/)
GDPP_GLSL_BINARY(%)
GDPP_GLSL_BINARY(&)
GDPP_GLSL_BINARY(|)
GDPP_GLSL_BINARY(^)
GDPP_GLSL_BINARY(<<)
GDPP_GLSL_BINARY(>>)
#undef GDPP_GLSL_BINARY

template <typename T, int N>
vec<T, N> operator-(const vec<T, N> &p_a) {
	return map([](T p_x) { return T(-p_x); }, p_a);
}
template <typename T, int N>
vec<T, N> operator+(const vec<T, N> &p_a) {
	return p_a;
}
template <typename T, int N>
vec<T, N> operator~(const vec<T, N> &p_a) {
	return map([](T p_x) { return T(~p_x); }, p_a);
}
// == and != compare whole vectors, as in GLSL.
template <typename T, int N>
bool operator==(const vec<T, N> &p_a, const vec<T, N> &p_b) {
	for (int i = 0; i < N; i++) {
		if (p_a.data[i] != p_b.data[i]) {
			return false;
		}
	}
	return true;
}
template <typename T, int N>
bool operator!=(const vec<T, N> &p_a, const vec<T, N> &p_b) {
	return !(p_a == p_b);
}

// mat is GLSL's matCxR, of C columns and R rows of floats, column-major.
template <int C, int R>
struct mat {
	vec<float, R> cols[C];

	// Zero.
	mat() {}
	// The scalar on the diagonal, e.g. mat3(1.0).
	template <typename S, std::enable_if_t<is_arithmetic<S>, int> = 0>
	explicit mat(S p_diagonal) {
		for (int i = 0; i < C && i < R; i++) {
			cols[i].data[i] = float(p_diagonal);
		}
	}
	// Components column by column, from scalars and vectors, e.g. mat2(a, b, c, d) or mat3(c0, c1, c2).
	template <typename A, typename B, typename... Cs, std::enable_if_t<count_components<A, B, Cs...> == C * R, int> = 0>
	explicit mat(const A &p_a, const B &p_b, const Cs &...p_cs) {
		float flat[C * R];
		float *out = flat;
		put(out, p_a);
		put(out, p_b);
		(put(out, p_cs), ...);
		for (int i = 0; i < C * R; i++) {
			cols[i / R].data[i % R] = flat[i];
		}
	}
	// Another size: the upper left part, and the identity elsewhere, as in GLSL.
	template <int C2, int R2, std::enable_if_t<C2 != C || R2 != R, int> = 0>
	explicit mat(const mat<C2, R2> &p_other) {
		for (int c = 0; c < C; c++) {
			for (int r = 0; r < R; r++) {
				cols[c].data[r] = c < C2 && r < R2 ? p_other.cols[c].data[r] : (c == r ? 1.0f : 0.0f);
			}
		}
	}
	// From Godot's matrices: a Basis is a mat3, a Transform3D a mat4x3, and a Projection a mat4.
	explicit mat(const godot::Basis &p_basis) {
		static_assert(C == 3 && R == 3, "Only a mat3 converts from a Basis.");
		for (int c = 0; c < 3; c++) {
			cols[c] = vec<float, R>(p_basis.get_column(c));
		}
	}
	explicit mat(const godot::Transform3D &p_transform) {
		static_assert(C == 4 && R == 3, "Only a mat4x3 converts from a Transform3D.");
		for (int c = 0; c < 3; c++) {
			cols[c] = vec<float, R>(p_transform.basis.get_column(c));
		}
		cols[3] = vec<float, R>(p_transform.origin);
	}
	explicit mat(const godot::Projection &p_projection) {
		static_assert(C == 4 && R == 4, "Only a mat4 converts from a Projection.");
		for (int c = 0; c < 4; c++) {
			cols[c] = vec<float, R>(p_projection.columns[c]);
		}
	}

	vec<float, R> &operator[](int p_column) { return cols[p_column]; }
	const vec<float, R> &operator[](int p_column) const { return cols[p_column]; }

	static constexpr int length() { return C; }

private:
	template <typename A>
	static void put(float *&p_out, const A &p_value) {
		if constexpr (is_vec<A>::value) {
			for (int i = 0; i < components<A>::value; i++) {
				*p_out++ = float(p_value.data[i]);
			}
		} else {
			*p_out++ = float(p_value);
		}
	}
};

typedef mat<2, 2> mat2;
typedef mat<3, 3> mat3;
typedef mat<4, 4> mat4;
typedef mat<2, 2> mat2x2;
typedef mat<2, 3> mat2x3;
typedef mat<2, 4> mat2x4;
typedef mat<3, 2> mat3x2;
typedef mat<3, 3> mat3x3;
typedef mat<3, 4> mat3x4;
typedef mat<4, 2> mat4x2;
typedef mat<4, 3> mat4x3;
typedef mat<4, 4> mat4x4;

template <int C, int R>
vec<float, R> operator*(const mat<C, R> &p_m, const vec<float, C> &p_v) {
	vec<float, R> result;
	for (int c = 0; c < C; c++) {
		result = result + p_m.cols[c] * p_v.data[c];
	}
	return result;
}
template <int C, int R>
vec<float, C> operator*(const vec<float, R> &p_v, const mat<C, R> &p_m) {
	vec<float, C> result;
	for (int c = 0; c < C; c++) {
		for (int r = 0; r < R; r++) {
			result.data[c] += p_v.data[r] * p_m.cols[c].data[r];
		}
	}
	return result;
}
template <int C, int R, int K>
mat<K, R> operator*(const mat<C, R> &p_a, const mat<K, C> &p_b) {
	mat<K, R> result;
	for (int k = 0; k < K; k++) {
		result.cols[k] = p_a * p_b.cols[k];
	}
	return result;
}
template <int C, int R, typename S, std::enable_if_t<is_arithmetic<S>, int> = 0>
mat<C, R> operator*(const mat<C, R> &p_m, S p_s) {
	mat<C, R> result;
	for (int c = 0; c < C; c++) {
		result.cols[c] = p_m.cols[c] * float(p_s);
	}
	return result;
}
template <int C, int R, typename S, std::enable_if_t<is_arithmetic<S>, int> = 0>
mat<C, R> operator*(S p_s, const mat<C, R> &p_m) {
	return p_m * p_s;
}
template <int C, int R>
mat<C, R> operator+(const mat<C, R> &p_a, const mat<C, R> &p_b) {
	mat<C, R> result;
	for (int c = 0; c < C; c++) {
		result.cols[c] = p_a.cols[c] + p_b.cols[c];
	}
	return result;
}
template <int C, int R>
mat<C, R> operator-(const mat<C, R> &p_a, const mat<C, R> &p_b) {
	mat<C, R> result;
	for (int c = 0; c < C; c++) {
		result.cols[c] = p_a.cols[c] - p_b.cols[c];
	}
	return result;
}
template <int C, int R>
mat<C, R> operator-(const mat<C, R> &p_a) {
	return p_a * -1.0f;
}
template <int C, int R>
mat<C, R> &operator*=(mat<C, R> &p_a, const mat<C, C> &p_b) {
	return p_a = p_a * p_b;
}

// The built-in functions of GLSL that compute shaders use.

// A scalar or vector of floats, for the built-ins that take one.
template <typename A>
using float_t_of = std::conditional_t<is_vec<A>::value, vec<float, components<A>::value>, float>;

#define GDPP_GLSL_UNARY(m_name, m_expr)                                         \
	template <typename A, std::enable_if_t<is_vec<A>::value || is_arithmetic<A>, int> = 0> \
	float_t_of<A> m_name(const A &p_a) {                                        \
		return map([](auto p_x) { float x = float(p_x); return float(m_expr); }, float_t_of<A>(p_a)); \
	}
GDPP_GLSL_UNARY(radians, x * 0.017453292519943295f)
GDPP_GLSL_UNARY(degrees, x * 57.29577951308232f)
GDPP_GLSL_UNARY(sin, std::sin(x))
GDPP_GLSL_UNARY(cos, std::cos(x))
GDPP_GLSL_UNARY(tan, std::tan(x))
GDPP_GLSL_UNARY(asin, std::asin(x))
GDPP_GLSL_UNARY(acos, std::acos(x))
GDPP_GLSL_UNARY(sinh, std::sinh(x))
GDPP_GLSL_UNARY(cosh, std::cosh(x))
GDPP_GLSL_UNARY(tanh, std::tanh(x))
GDPP_GLSL_UNARY(asinh, std::asinh(x))
GDPP_GLSL_UNARY(acosh, std::acosh(x))
GDPP_GLSL_UNARY(atanh, std::atanh(x))
GDPP_GLSL_UNARY(exp, std::exp(x))
GDPP_GLSL_UNARY(log, std::log(x))
GDPP_GLSL_UNARY(exp2, std::exp2(x))
GDPP_GLSL_UNARY(log2, std::log2(x))
GDPP_GLSL_UNARY(sqrt, std::sqrt(x))
GDPP_GLSL_UNARY(inversesqrt, 1.0f / std::sqrt(x))
GDPP_GLSL_UNARY(floor, std::floor(x))
GDPP_GLSL_UNARY(ceil, std::ceil(x))
GDPP_GLSL_UNARY(trunc, std::trunc(x))
GDPP_GLSL_UNARY(round, std::round(x))
GDPP_GLSL_UNARY(roundEven, std::nearbyint(x))
GDPP_GLSL_UNARY(fract, x - std::floor(x))
#undef GDPP_GLSL_UNARY

// When float_t_of would turn integers into floats, these keep the type: abs and sign of an int are ints.
template <typename A, std::enable_if_t<is_vec<A>::value || is_arithmetic<A>, int> = 0>
A abs(const A &p_a) {
	return map([](auto p_x) { return p_x < 0 ? decltype(p_x)(-p_x) : p_x; }, p_a);
}
template <typename A, std::enable_if_t<is_vec<A>::value || is_arithmetic<A>, int> = 0>
A sign(const A &p_a) {
	return map([](auto p_x) { return decltype(p_x)(p_x > 0 ? 1 : p_x < 0 ? -1 : 0); }, p_a);
}

template <typename A>
float_t_of<A> atan(const A &p_y_over_x) {
	return map([](auto p_x) { return float(std::atan(float(p_x))); }, float_t_of<A>(p_y_over_x));
}
template <typename A, typename B>
float_t_of<common_t<A, B>> atan(const A &p_y, const B &p_x) {
	return zip<float_t_of<common_t<A, B>>>([](auto p_a, auto p_b) { return std::atan2(float(p_a), float(p_b)); }, p_y, p_x);
}
template <typename A, typename B>
float_t_of<common_t<A, B>> pow(const A &p_a, const B &p_b) {
	return zip<float_t_of<common_t<A, B>>>([](auto p_x, auto p_y) { return std::pow(float(p_x), float(p_y)); }, p_a, p_b);
}
template <typename A, typename B>
float_t_of<common_t<A, B>> mod(const A &p_a, const B &p_b) {
	return zip<float_t_of<common_t<A, B>>>([](auto p_x, auto p_y) { return float(p_x) - float(p_y) * std::floor(float(p_x) / float(p_y)); }, p_a, p_b);
}
template <typename A, typename B>
common_t<A, B> min(const A &p_a, const B &p_b) {
	using S = typename scalar_of<common_t<A, B>>::type;
	return zip<common_t<A, B>>([](auto p_x, auto p_y) { return S(p_y) < S(p_x) ? S(p_y) : S(p_x); }, p_a, p_b);
}
template <typename A, typename B>
common_t<A, B> max(const A &p_a, const B &p_b) {
	using S = typename scalar_of<common_t<A, B>>::type;
	return zip<common_t<A, B>>([](auto p_x, auto p_y) { return S(p_x) < S(p_y) ? S(p_y) : S(p_x); }, p_a, p_b);
}
template <typename A, typename B, typename C>
common_t<A, common_t<B, C>> clamp(const A &p_x, const B &p_lo, const C &p_hi) {
	using R = common_t<A, common_t<B, C>>;
	using S = typename scalar_of<R>::type;
	return zip3<R>([](auto p_v, auto p_l, auto p_h) { S v = S(p_v); return v < S(p_l) ? S(p_l) : S(p_h) < v ? S(p_h) : v; }, p_x, p_lo, p_hi);
}
// mix blends p_a and p_b by p_t, or with a bool p_t picks one of them, per component.
template <typename A, typename B, typename C>
common_t<A, B> mix(const A &p_a, const B &p_b, const C &p_t) {
	using R = common_t<A, B>;
	if constexpr (std::is_same_v<typename scalar_of<C>::type, bool>) {
		return zip3<R>([](auto p_x, auto p_y, bool p_pick) { return p_pick ? p_y : p_x; }, R(p_a), R(p_b), p_t);
	} else {
		return zip3<R>([](auto p_x, auto p_y, auto p_w) { return float(p_x) + (float(p_y) - float(p_x)) * float(p_w); }, p_a, p_b, p_t);
	}
}
template <typename A, typename B>
float_t_of<B> step(const A &p_edge, const B &p_x) {
	return zip<float_t_of<B>>([](auto p_e, auto p_v) { return float(p_v) < float(p_e) ? 0.0f : 1.0f; }, p_edge, p_x);
}
template <typename A, typename B, typename C>
float_t_of<C> smoothstep(const A &p_lo, const B &p_hi, const C &p_x) {
	return zip3<float_t_of<C>>([](auto p_l, auto p_h, auto p_v) {
		float t = std::fmin(std::fmax((float(p_v) - float(p_l)) / (float(p_h) - float(p_l)), 0.0f), 1.0f);
		return t * t * (3.0f - 2.0f * t);
	},
			p_lo, p_hi, p_x);
}
template <typename A, typename B, typename C>
float_t_of<common_t<A, common_t<B, C>>> fma(const A &p_a, const B &p_b, const C &p_c) {
	return zip3<float_t_of<common_t<A, common_t<B, C>>>>([](auto p_x, auto p_y, auto p_z) { return std::fma(float(p_x), float(p_y), float(p_z)); }, p_a, p_b, p_c);
}
template <typename A>
auto isnan(const A &p_a) -> std::conditional_t<is_vec<A>::value, vec<bool, components<A>::value>, bool> {
	return map([](auto p_x) { return std::isnan(float(p_x)); }, p_a);
}
template <typename A>
auto isinf(const A &p_a) -> std::conditional_t<is_vec<A>::value, vec<bool, components<A>::value>, bool> {
	return map([](auto p_x) { return std::isinf(float(p_x)); }, p_a);
}
// modf returns the fraction of p_x, and sets p_whole to its whole part.
template <typename A>
A modf(const A &p_x, A &p_whole) {
	p_whole = trunc(p_x);
	return p_x - p_whole;
}

template <typename To, typename From>
To bit_cast(From p_from) {
	static_assert(sizeof(To) == sizeof(From), "bit_cast needs types of the same size.");
	To to;
	std::memcpy(&to, &p_from, sizeof(To));
	return to;
}
template <typename A>
auto floatBitsToInt(const A &p_a) {
	return map([](float p_x) { return bit_cast<int>(p_x); }, p_a);
}
template <typename A>
auto floatBitsToUint(const A &p_a) {
	return map([](float p_x) { return bit_cast<uint>(p_x); }, p_a);
}
template <typename A>
auto intBitsToFloat(const A &p_a) {
	return map([](int p_x) { return bit_cast<float>(p_x); }, p_a);
}
template <typename A>
auto uintBitsToFloat(const A &p_a) {
	return map([](uint p_x) { return bit_cast<float>(p_x); }, p_a);
}

template <typename T, int N>
float dot(const vec<T, N> &p_a, const vec<T, N> &p_b) {
	float sum = 0;
	for (int i = 0; i < N; i++) {
		sum += float(p_a.data[i]) * float(p_b.data[i]);
	}
	return sum;
}
template <typename A, typename B, std::enable_if_t<is_arithmetic<A> && is_arithmetic<B>, int> = 0>
float dot(A p_a, B p_b) {
	return float(p_a) * float(p_b);
}
template <typename A>
float length(const A &p_a) {
	if constexpr (is_vec<A>::value) {
		return std::sqrt(dot(p_a, p_a));
	} else {
		return std::fabs(float(p_a));
	}
}
template <typename A, typename B>
float distance(const A &p_a, const B &p_b) {
	return length(p_a - p_b);
}
inline vec3 cross(const vec3 &p_a, const vec3 &p_b) {
	return vec3(p_a.y * p_b.z - p_a.z * p_b.y, p_a.z * p_b.x - p_a.x * p_b.z, p_a.x * p_b.y - p_a.y * p_b.x);
}
template <typename A>
A normalize(const A &p_a) {
	return p_a / length(p_a);
}
template <typename A>
A faceforward(const A &p_n, const A &p_i, const A &p_nref) {
	return dot(p_nref, p_i) < 0 ? p_n : -p_n;
}
template <typename A>
A reflect(const A &p_i, const A &p_n) {
	return p_i - p_n * (2.0f * dot(p_n, p_i));
}
template <typename A, typename S>
A refract(const A &p_i, const A &p_n, S p_eta) {
	float eta = float(p_eta);
	float d = dot(p_n, p_i);
	float k = 1.0f - eta * eta * (1.0f - d * d);
	return k < 0 ? A(0.0f) : p_i * eta - p_n * (eta * d + std::sqrt(k));
}

template <int C, int R>
mat<C, R> matrixCompMult(const mat<C, R> &p_a, const mat<C, R> &p_b) {
	mat<C, R> result;
	for (int c = 0; c < C; c++) {
		result.cols[c] = p_a.cols[c] * p_b.cols[c];
	}
	return result;
}
template <int C, int R>
mat<C, R> outerProduct(const vec<float, R> &p_c, const vec<float, C> &p_r) {
	mat<C, R> result;
	for (int c = 0; c < C; c++) {
		result.cols[c] = p_c * p_r.data[c];
	}
	return result;
}
template <int C, int R>
mat<R, C> transpose(const mat<C, R> &p_m) {
	mat<R, C> result;
	for (int c = 0; c < C; c++) {
		for (int r = 0; r < R; r++) {
			result.cols[r].data[c] = p_m.cols[c].data[r];
		}
	}
	return result;
}
inline float determinant(const mat2 &p_m) {
	return p_m[0][0] * p_m[1][1] - p_m[1][0] * p_m[0][1];
}
inline float determinant(const mat3 &p_m) {
	return dot(p_m[0], cross(p_m[1], p_m[2]));
}
inline float determinant(const mat4 &p_m) {
	float d = 0;
	for (int c = 0; c < 4; c++) {
		mat3 minor;
		for (int k = 0, j = 0; k < 4; k++) {
			if (k != c) {
				minor[j++] = vec3(p_m[k][1], p_m[k][2], p_m[k][3]);
			}
		}
		d += (c % 2 ? -1.0f : 1.0f) * p_m[c][0] * determinant(minor);
	}
	return d;
}
// inverse inverts a square matrix by Gauss-Jordan elimination.
template <int N>
mat<N, N> inverse(const mat<N, N> &p_m) {
	float a[N][2 * N];
	for (int r = 0; r < N; r++) {
		for (int c = 0; c < N; c++) {
			a[r][c] = p_m[c][r];
			a[r][N + c] = r == c ? 1.0f : 0.0f;
		}
	}
	for (int c = 0; c < N; c++) {
		int pivot = c;
		for (int r = c + 1; r < N; r++) {
			if (std::fabs(a[r][c]) > std::fabs(a[pivot][c])) {
				pivot = r;
			}
		}
		for (int k = 0; k < 2 * N; k++) {
			std::swap(a[c][k], a[pivot][k]);
		}
		float scale = a[c][c] == 0 ? 0.0f : 1.0f / a[c][c];
		for (int k = 0; k < 2 * N; k++) {
			a[c][k] *= scale;
		}
		for (int r = 0; r < N; r++) {
			if (r != c) {
				float f = a[r][c];
				for (int k = 0; k < 2 * N; k++) {
					a[r][k] -= f * a[c][k];
				}
			}
		}
	}
	mat<N, N> result;
	for (int r = 0; r < N; r++) {
		for (int c = 0; c < N; c++) {
			result[c][r] = a[r][N + c];
		}
	}
	return result;
}

#define GDPP_GLSL_COMPARE(m_name, m_op)                                                               \
	template <typename T, int N>                                                                       \
	bvec<N> m_name(const vec<T, N> &p_a, const vec<T, N> &p_b) {                                       \
		return zip<bvec<N>>([](T p_x, T p_y) { return p_x m_op p_y; }, p_a, p_b);                      \
	}
template <int N>
using bvec = vec<bool, N>;
GDPP_GLSL_COMPARE(lessThan, <)
GDPP_GLSL_COMPARE(lessThanEqual, <=)
GDPP_GLSL_COMPARE(greaterThan, >)
GDPP_GLSL_COMPARE(greaterThanEqual, >=)
GDPP_GLSL_COMPARE(equal, ==)
GDPP_GLSL_COMPARE(notEqual, !=)
#undef GDPP_GLSL_COMPARE
template <int N>
bool any(const bvec<N> &p_v) {
	for (int i = 0; i < N; i++) {
		if (p_v.data[i]) {
			return true;
		}
	}
	return false;
}
template <int N>
bool all(const bvec<N> &p_v) {
	for (int i = 0; i < N; i++) {
		if (!p_v.data[i]) {
			return false;
		}
	}
	return true;
}
// glsl_not is GLSL's not(v), which GD++ renames, since not is a C++ keyword.
template <int N>
bvec<N> glsl_not(const bvec<N> &p_v) {
	return map([](bool p_x) { return !p_x; }, p_v);
}

template <typename A>
auto bitCount(const A &p_a) {
	return map([](auto p_x) { uint v = uint(p_x); int n = 0; for (; v; v &= v - 1) n++; return n; }, p_a);
}
template <typename A>
auto findLSB(const A &p_a) {
	return map([](auto p_x) { uint v = uint(p_x); if (!v) return -1; int i = 0; while (!(v & 1u)) { v >>= 1; i++; } return i; }, p_a);
}
template <typename A>
auto findMSB(const A &p_a) {
	return map([](auto p_x) {
		uint v = std::is_signed_v<decltype(p_x)> && p_x < 0 ? ~uint(p_x) : uint(p_x);
		int i = -1;
		for (; v; v >>= 1) i++;
		return i;
	},
			p_a);
}
template <typename A>
A bitfieldReverse(const A &p_a) {
	return map([](auto p_x) {
		uint v = uint(p_x), r = 0;
		for (int i = 0; i < 32; i++, v >>= 1) r = (r << 1) | (v & 1u);
		return decltype(p_x)(r);
	},
			p_a);
}

// half_from_float and float_from_half convert between floats and 16-bit floats, as packHalf2x16 and RGBA16F do.
inline uint16_t half_from_float(float p_f) {
	uint32_t x = bit_cast<uint32_t>(p_f);
	uint32_t sign = (x >> 16) & 0x8000u;
	int32_t exponent = int32_t((x >> 23) & 0xffu) - 127 + 15;
	uint32_t mantissa = x & 0x7fffffu;
	if (((x >> 23) & 0xffu) == 0xffu) {
		return uint16_t(sign | 0x7c00u | (mantissa ? 0x200u : 0u));
	}
	if (exponent >= 31) {
		return uint16_t(sign | 0x7c00u);
	}
	if (exponent <= 0) {
		if (exponent < -10) {
			return uint16_t(sign);
		}
		mantissa |= 0x800000u;
		return uint16_t(sign | ((mantissa >> uint32_t(14 - exponent)) + ((mantissa >> uint32_t(13 - exponent)) & 1u)));
	}
	uint32_t h = sign | (uint32_t(exponent) << 10) | (mantissa >> 13);
	return uint16_t(h + ((mantissa >> 12) & 1u));
}
inline float float_from_half(uint16_t p_h) {
	uint32_t sign = uint32_t(p_h & 0x8000u) << 16;
	uint32_t exponent = (p_h >> 10) & 0x1fu;
	uint32_t mantissa = p_h & 0x3ffu;
	if (exponent == 0) {
		return (sign ? -1.0f : 1.0f) * std::ldexp(float(mantissa), -24);
	}
	if (exponent == 31) {
		return bit_cast<float>(sign | 0x7f800000u | (mantissa << 13));
	}
	return bit_cast<float>(sign | ((exponent + 112) << 23) | (mantissa << 13));
}
inline uint packHalf2x16(const vec2 &p_v) {
	return uint(half_from_float(p_v.x)) | (uint(half_from_float(p_v.y)) << 16);
}
inline vec2 unpackHalf2x16(uint p_v) {
	return vec2(float_from_half(uint16_t(p_v & 0xffffu)), float_from_half(uint16_t(p_v >> 16)));
}
inline uint packUnorm4x8(const vec4 &p_v) {
	uint result = 0;
	for (int i = 0; i < 4; i++) {
		result |= uint(std::round(std::fmin(std::fmax(p_v.data[i], 0.0f), 1.0f) * 255.0f)) << (8 * i);
	}
	return result;
}
inline vec4 unpackUnorm4x8(uint p_v) {
	return vec4(float(p_v & 0xffu), float((p_v >> 8) & 0xffu), float((p_v >> 16) & 0xffu), float(p_v >> 24)) / 255.0f;
}

// Atomics on buffer elements and shared variables, which are ints or uints.
template <typename T>
bool atomic_cas(T &p_x, T &p_expected, T p_desired) {
	static_assert(sizeof(T) == 4, "Atomics need a 32-bit int or uint.");
#if defined(_MSC_VER) && !defined(__clang__)
	long old = _InterlockedCompareExchange(reinterpret_cast<volatile long *>(&p_x), long(p_desired), long(p_expected));
	bool ok = old == long(p_expected);
	p_expected = T(old);
	return ok;
#else
	return __atomic_compare_exchange_n(&p_x, &p_expected, p_desired, false, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);
#endif
}
// atomic_update sets p_x to p_f(p_x) atomically, and returns the old value.
template <typename T, typename F>
T atomic_update(T &p_x, F p_f) {
	T old = p_x;
	while (!atomic_cas(p_x, old, T(p_f(old)))) {
	}
	return old;
}
template <typename T, typename V>
T atomicAdd(T &p_x, V p_v) {
	return atomic_update(p_x, [&](T p_old) { return p_old + T(p_v); });
}
template <typename T, typename V>
T atomicMin(T &p_x, V p_v) {
	return atomic_update(p_x, [&](T p_old) { return T(p_v) < p_old ? T(p_v) : p_old; });
}
template <typename T, typename V>
T atomicMax(T &p_x, V p_v) {
	return atomic_update(p_x, [&](T p_old) { return p_old < T(p_v) ? T(p_v) : p_old; });
}
template <typename T, typename V>
T atomicAnd(T &p_x, V p_v) {
	return atomic_update(p_x, [&](T p_old) { return p_old & T(p_v); });
}
template <typename T, typename V>
T atomicOr(T &p_x, V p_v) {
	return atomic_update(p_x, [&](T p_old) { return p_old | T(p_v); });
}
template <typename T, typename V>
T atomicXor(T &p_x, V p_v) {
	return atomic_update(p_x, [&](T p_old) { return p_old ^ T(p_v); });
}
template <typename T, typename V>
T atomicExchange(T &p_x, V p_v) {
	return atomic_update(p_x, [&](T) { return T(p_v); });
}
template <typename T, typename C, typename V>
T atomicCompSwap(T &p_x, C p_compare, V p_v) {
	T expected = T(p_compare);
	atomic_cas(p_x, expected, T(p_v));
	return expected;
}

// The invocation's built-in variables, which the CPU fallback sets before each invocation.
struct Invocation {
	uvec3 global_id, local_id, group_id, groups, group_size;
	uint local_index = 0;
	const char *kernel = nullptr; // Its kernel's name, e.g. "Terrain.blur", for errors.
};
GDPP_THREAD_LOCAL(Invocation, invocation)
#define gl_GlobalInvocationID (::gdpp::glsl::invocation().global_id)
#define gl_LocalInvocationID (::gdpp::glsl::invocation().local_id)
#define gl_WorkGroupID (::gdpp::glsl::invocation().group_id)
#define gl_NumWorkGroups (::gdpp::glsl::invocation().groups)
#define gl_WorkGroupSize (::gdpp::glsl::invocation().group_size)
#define gl_LocalInvocationIndex (::gdpp::glsl::invocation().local_index)

// barrier has no CPU fallback: the CPU runs a workgroup's invocations one after another. Kernels whose body calls it
// have none, but a helper may still call it.
inline void barrier() {
	static std::atomic<bool> reported = false;
	if (!reported.exchange(true)) {
		ERR_PRINT(vformat("Kernel %s calls barrier(), which has no CPU fallback, so its results are wrong on the CPU.", invocation().kernel));
	}
}
inline void memoryBarrier() { std::atomic_thread_fence(std::memory_order_seq_cst); }
inline void memoryBarrierShared() { std::atomic_thread_fence(std::memory_order_seq_cst); }
inline void memoryBarrierBuffer() { std::atomic_thread_fence(std::memory_order_seq_cst); }
inline void memoryBarrierImage() { std::atomic_thread_fence(std::memory_order_seq_cst); }
inline void groupMemoryBarrier() { std::atomic_thread_fence(std::memory_order_seq_cst); }

// Pixels is an image's pixels as vec4s, row by row.
struct Pixels {
	int width = 0, height = 0;
	std::vector<vec4> data;
};

// sampler2D is a texture that a kernel samples: an Image or a Texture2D parameter.
struct sampler2D {
	std::shared_ptr<const Pixels> pixels;

	// The pixel at p_texel, clamped to the edges.
	vec4 fetch(int p_x, int p_y) const {
		if (!pixels || pixels->width == 0 || pixels->height == 0) {
			return vec4();
		}
		p_x = p_x < 0 ? 0 : p_x >= pixels->width ? pixels->width - 1 : p_x;
		p_y = p_y < 0 ? 0 : p_y >= pixels->height ? pixels->height - 1 : p_y;
		return pixels->data[size_t(p_y) * size_t(pixels->width) + size_t(p_x)];
	}
};
inline vec4 texelFetch(const sampler2D &p_s, const ivec2 &p_texel, int) {
	return p_s.fetch(p_texel.x, p_texel.y);
}
inline ivec2 textureSize(const sampler2D &p_s, int) {
	return p_s.pixels ? ivec2(p_s.pixels->width, p_s.pixels->height) : ivec2();
}
// texture samples bilinearly, clamped to the edges, like the sampler that GPU kernels get.
inline vec4 texture(const sampler2D &p_s, const vec2 &p_uv) {
	ivec2 size = textureSize(p_s, 0);
	float x = p_uv.x * float(size.x) - 0.5f, y = p_uv.y * float(size.y) - 0.5f;
	int x0 = int(std::floor(x)), y0 = int(std::floor(y));
	float fx = x - float(x0), fy = y - float(y0);
	vec4 top = mix(p_s.fetch(x0, y0), p_s.fetch(x0 + 1, y0), fx);
	vec4 bottom = mix(p_s.fetch(x0, y0 + 1), p_s.fetch(x0 + 1, y0 + 1), fx);
	return mix(top, bottom, fy);
}
inline vec4 textureLod(const sampler2D &p_s, const vec2 &p_uv, float) {
	return texture(p_s, p_uv);
}

// image2D is a texture that a kernel writes: a Texture2D[FORMAT] parameter. Copies share the pixels, which the
// runtime writes back once the kernel is done.
struct image2D {
	std::shared_ptr<Pixels> pixels;
};
inline vec4 imageLoad(const image2D &p_image, const ivec2 &p_texel) {
	const Pixels *p = p_image.pixels.get();
	if (!p || p_texel.x < 0 || p_texel.y < 0 || p_texel.x >= p->width || p_texel.y >= p->height) {
		return vec4();
	}
	return p->data[size_t(p_texel.y) * size_t(p->width) + size_t(p_texel.x)];
}
inline void imageStore(const image2D &p_image, const ivec2 &p_texel, const vec4 &p_value) {
	Pixels *p = p_image.pixels.get();
	if (p && p_texel.x >= 0 && p_texel.y >= 0 && p_texel.x < p->width && p_texel.y < p->height) {
		p->data[size_t(p_texel.y) * size_t(p->width) + size_t(p_texel.x)] = p_value;
	}
}
inline ivec2 imageSize(const image2D &p_image) {
	return p_image.pixels ? ivec2(p_image.pixels->width, p_image.pixels->height) : ivec2();
}

} // namespace gdpp::glsl

namespace gdpp {

// GpuFormat is the format of an Image or a Texture2D that a kernel writes, e.g. Texture2D[rgba8] in GD++.
enum class GpuFormat {
	r8,
	rg8,
	rgba8,
	rf,
	rgf,
	rgbah,
	rgbaf,
	// RGB formats, only for an Image that a shader returns: the GPU writes RGBA, which the runtime converts.
	rgb8,
	rgbh,
	rgbf,
};

// GDPP_GPU_ARRAY_CLASS is the name of the package's class of GPU arrays, e.g. FooGpuArray: its prefix and GpuArray.
// GDPP_GPU_TEXTURE_CLASS is the name of its internal class of textures that GD++ creates, e.g. FooGpuTexture. The
// package registers both if it has @gpu functions, and the build defines these macros.
#ifndef GDPP_GPU_ARRAY_CLASS
#define GDPP_GPU_ARRAY_CLASS GdppGpuArray
#endif
#ifndef GDPP_GPU_TEXTURE_CLASS
#define GDPP_GPU_TEXTURE_CLASS GdppGpuTexture
#endif
// gpu_array_class is the name of the package's class of GPU arrays, as a string, e.g. "FooGpuArray".
inline constexpr const char *gpu_array_class = GDPP_STRINGIFY(GDPP_GPU_ARRAY_CLASS);

namespace gpu {

using namespace glsl;

// FormatInfo describes a GpuFormat: its RenderingDevice format and the matching Image format, which the GPU writes,
// the Image format that a kernel's Image has in the end, and how many channels a kernel returns.
struct FormatInfo {
	RenderingDevice::DataFormat rd;
	Image::Format image;
	int channels;
	Image::Format final;
};
inline const FormatInfo &info(GpuFormat p_format) {
	static const FormatInfo infos[] = {
		{ RenderingDevice::DATA_FORMAT_R8_UNORM, Image::FORMAT_R8, 1, Image::FORMAT_R8 },
		{ RenderingDevice::DATA_FORMAT_R8G8_UNORM, Image::FORMAT_RG8, 2, Image::FORMAT_RG8 },
		{ RenderingDevice::DATA_FORMAT_R8G8B8A8_UNORM, Image::FORMAT_RGBA8, 4, Image::FORMAT_RGBA8 },
		{ RenderingDevice::DATA_FORMAT_R32_SFLOAT, Image::FORMAT_RF, 1, Image::FORMAT_RF },
		{ RenderingDevice::DATA_FORMAT_R32G32_SFLOAT, Image::FORMAT_RGF, 2, Image::FORMAT_RGF },
		{ RenderingDevice::DATA_FORMAT_R16G16B16A16_SFLOAT, Image::FORMAT_RGBAH, 4, Image::FORMAT_RGBAH },
		{ RenderingDevice::DATA_FORMAT_R32G32B32A32_SFLOAT, Image::FORMAT_RGBAF, 4, Image::FORMAT_RGBAF },
		{ RenderingDevice::DATA_FORMAT_R8G8B8A8_UNORM, Image::FORMAT_RGBA8, 3, Image::FORMAT_RGB8 },
		{ RenderingDevice::DATA_FORMAT_R16G16B16A16_SFLOAT, Image::FORMAT_RGBAH, 3, Image::FORMAT_RGBH },
		{ RenderingDevice::DATA_FORMAT_R32G32B32A32_SFLOAT, Image::FORMAT_RGBAF, 3, Image::FORMAT_RGBF },
	};
	return infos[int(p_format)];
}

// Elem is the element type of a GPU array, as Godot sees it.
enum class Elem {
	FLOAT,
	INT,
	VECTOR2,
	VECTOR3,
	VECTOR4,
	COLOR,
};

// ElemInfo describes an Elem: its packed array type, and its size in GPU (std430) and CPU memory.
struct ElemInfo {
	Variant::Type packed;
	int gpu_stride, cpu_stride;
	const char *name;
};
inline const ElemInfo &info(Elem p_elem) {
	static const ElemInfo infos[] = {
		{ Variant::PACKED_FLOAT32_ARRAY, 4, 4, "float" },
		{ Variant::PACKED_INT32_ARRAY, 4, 4, "int" },
		{ Variant::PACKED_VECTOR2_ARRAY, 8, 8, "Vector2" },
		{ Variant::PACKED_VECTOR3_ARRAY, 16, 12, "Vector3" },
		{ Variant::PACKED_VECTOR4_ARRAY, 16, 16, "Vector4" },
		{ Variant::PACKED_COLOR_ARRAY, 16, 16, "Color" },
	};
	return infos[int(p_elem)];
}

// ElemOf maps a GPU array's element type, e.g. float in GpuArray<float>, to its Elem, packed array, and GLSL type.
template <typename G>
struct ElemOf;
template <>
struct ElemOf<float> {
	static constexpr Elem elem = Elem::FLOAT;
	using Packed = PackedFloat32Array;
	using Glsl = float;
};
template <>
struct ElemOf<int32_t> {
	static constexpr Elem elem = Elem::INT;
	using Packed = PackedInt32Array;
	using Glsl = int;
};
template <>
struct ElemOf<Vector2> {
	static constexpr Elem elem = Elem::VECTOR2;
	using Packed = PackedVector2Array;
	using Glsl = vec2;
};
template <>
struct ElemOf<Vector3> {
	static constexpr Elem elem = Elem::VECTOR3;
	using Packed = PackedVector3Array;
	using Glsl = vec3;
};
template <>
struct ElemOf<Vector4> {
	static constexpr Elem elem = Elem::VECTOR4;
	using Packed = PackedVector4Array;
	using Glsl = vec4;
};
template <>
struct ElemOf<Color> {
	static constexpr Elem elem = Elem::COLOR;
	using Packed = PackedColorArray;
	using Glsl = vec4;
};

// elem_of returns the Elem of a packed array, or false for one that a GPU array can't hold.
inline bool elem_of(const Variant &p_packed, Elem &r_elem) {
	for (int e = 0; e <= int(Elem::COLOR); e++) {
		if (info(Elem(e)).packed == p_packed.get_type()) {
			r_elem = Elem(e);
			return true;
		}
	}
	return false;
}

// to_cpu converts a packed array of elem to the CPU's layout, the GLSL types' memory.
inline std::vector<uint8_t> to_cpu(Elem p_elem, const Variant &p_packed) {
	std::vector<uint8_t> bytes;
	auto put = [&](const auto &p_array, auto p_convert) {
		using V = decltype(p_convert(p_array[0]));
		bytes.resize(size_t(p_array.size()) * sizeof(V));
		V *out = reinterpret_cast<V *>(bytes.data());
		for (int64_t i = 0; i < p_array.size(); i++) {
			out[i] = p_convert(p_array[i]);
		}
	};
	switch (p_elem) {
		case Elem::FLOAT:
			put(PackedFloat32Array(p_packed), [](float p_v) { return p_v; });
			break;
		case Elem::INT:
			put(PackedInt32Array(p_packed), [](int32_t p_v) { return int(p_v); });
			break;
		case Elem::VECTOR2:
			put(PackedVector2Array(p_packed), [](const Vector2 &p_v) { return vec2(p_v); });
			break;
		case Elem::VECTOR3:
			put(PackedVector3Array(p_packed), [](const Vector3 &p_v) { return vec3(p_v); });
			break;
		case Elem::VECTOR4:
			put(PackedVector4Array(p_packed), [](const Vector4 &p_v) { return vec4(p_v); });
			break;
		case Elem::COLOR:
			put(PackedColorArray(p_packed), [](const Color &p_v) { return vec4(p_v); });
			break;
	}
	return bytes;
}

// from_cpu converts p_count elements of elem in the CPU's layout to a packed array.
inline Variant from_cpu(Elem p_elem, const uint8_t *p_bytes, int64_t p_count) {
	auto get = [&](auto p_array, auto p_glsl) {
		using V = decltype(p_glsl);
		const V *in = reinterpret_cast<const V *>(p_bytes);
		p_array.resize(p_count);
		for (int64_t i = 0; i < p_count; i++) {
			p_array.set(i, in[i]);
		}
		return Variant(p_array);
	};
	switch (p_elem) {
		case Elem::FLOAT:
			return get(PackedFloat32Array(), float());
		case Elem::INT:
			return get(PackedInt32Array(), int());
		case Elem::VECTOR2:
			return get(PackedVector2Array(), vec2());
		case Elem::VECTOR3:
			return get(PackedVector3Array(), vec3());
		case Elem::VECTOR4:
			return get(PackedVector4Array(), vec4());
		case Elem::COLOR:
			return get(PackedColorArray(), vec4());
	}
	return Variant();
}

// gpu_layout converts elements in the CPU's layout to the GPU's, which pads each vec3 to 16 bytes, and cpu_layout
// converts back.
inline PackedByteArray gpu_layout(Elem p_elem, const uint8_t *p_bytes, int64_t p_count) {
	const ElemInfo &e = info(p_elem);
	PackedByteArray result;
	result.resize(p_count * e.gpu_stride);
	uint8_t *out = result.ptrw();
	if (e.gpu_stride == e.cpu_stride) {
		std::memcpy(out, p_bytes, size_t(p_count * e.gpu_stride));
	} else {
		std::memset(out, 0, size_t(result.size()));
		for (int64_t i = 0; i < p_count; i++) {
			std::memcpy(out + i * e.gpu_stride, p_bytes + i * e.cpu_stride, size_t(e.cpu_stride));
		}
	}
	return result;
}
inline std::vector<uint8_t> cpu_layout(Elem p_elem, const PackedByteArray &p_gpu, int64_t p_count) {
	const ElemInfo &e = info(p_elem);
	std::vector<uint8_t> result(size_t(p_count * e.cpu_stride));
	p_count = std::min<int64_t>(p_count, p_gpu.size() / e.gpu_stride);
	for (int64_t i = 0; i < p_count; i++) {
		std::memcpy(result.data() + i * e.cpu_stride, p_gpu.ptr() + i * e.gpu_stride, size_t(e.cpu_stride));
	}
	return result;
}

// on_render_thread runs p_f on the render thread, which owns the main RenderingDevice: right away if this is it, as
// in Godot's default single-threaded rendering, else through call_on_render_thread, waiting for it if p_wait.
inline void on_render_thread(std::function<void()> p_f, bool p_wait) {
	RenderingServer *rs = RenderingServer::get_singleton();
	if (rs->is_on_render_thread()) {
		p_f();
		return;
	}
	// Variables, since memnew puts its argument in a decltype, where C++17 doesn't allow a lambda.
	if (!p_wait) {
		auto run = [p_f] {
			p_f();
			return Variant();
		};
		rs->call_on_render_thread(Callable(memnew(TaskCallable(std::move(run)))));
		return;
	}
	struct Done {
		std::mutex mutex;
		std::condition_variable cv;
		bool done = false;
	};
	std::shared_ptr<Done> done = std::make_shared<Done>();
	auto run = [p_f, done] {
		p_f();
		std::lock_guard<std::mutex> lock(done->mutex);
		done->done = true;
		done->cv.notify_all();
		return Variant();
	};
	rs->call_on_render_thread(Callable(memnew(TaskCallable(std::move(run)))));
	std::unique_lock<std::mutex> lock(done->mutex);
	done->cv.wait(lock, [&] { return done->done; });
}

// Device is a RenderingDevice that runs kernels: the main one, which renders, or the package's local one.
//
// Godot only lets a RenderingDevice's own thread, the one that created it, use it. For the main one, that's the
// render thread. The local one gets a thread of its own, which creates it, and runs the work that other threads
// queue for it, until the library is unloaded.
struct Device {
	RenderingDevice *rd = nullptr;
	bool main = false;
	RID sampler; // Linear, clamped to the edges, for sampled textures.

	// run runs p_f with the device, on the device's thread, waiting for it if p_wait.
	void run(std::function<void()> p_f, bool p_wait) {
		if (main) {
			on_render_thread(std::move(p_f), p_wait);
			return;
		}
		if (std::this_thread::get_id() == owner) {
			p_f();
			return;
		}
		std::shared_ptr<Done> done = p_wait ? std::make_shared<Done>() : nullptr;
		{
			std::lock_guard<std::mutex> lock(mutex);
			queue.push_back({ std::move(p_f), done });
		}
		cv.notify_all();
		if (done) {
			std::unique_lock<std::mutex> lock(done->mutex);
			done->cv.wait(lock, [&] { return done->done; });
		}
	}

	// Lets the local device's thread go if the library is never unloaded, since joining it then would hang.
	~Device() {
		if (thread.joinable()) {
			thread.detach();
		}
	}

	// start starts the local device's thread, which creates the device, and waits until it did.
	void start() {
		std::shared_ptr<Done> ready = std::make_shared<Done>();
		thread = std::thread([this, ready] {
			owner = std::this_thread::get_id();
			rd = RenderingServer::get_singleton()->create_local_rendering_device();
			ready->finish();
			loop();
		});
		{
			std::unique_lock<std::mutex> lock(ready->mutex);
			ready->cv.wait(lock, [&] { return ready->done; });
		}
		if (!rd) {
			stop([] {});
		}
	}

	// stop runs p_last on the local device's thread, after the work queued before it, and ends the thread.
	void stop(std::function<void()> p_last) {
		run(std::move(p_last), true);
		{
			std::lock_guard<std::mutex> lock(mutex);
			stopping = true;
		}
		cv.notify_all();
		if (thread.joinable()) {
			thread.join();
		}
	}

private:
	// Done tells a thread that waits for some work that it's done.
	struct Done {
		std::mutex mutex;
		std::condition_variable cv;
		bool done = false;
		void finish() {
			std::lock_guard<std::mutex> lock(mutex);
			done = true;
			cv.notify_all();
		}
	};
	struct Work {
		std::function<void()> f;
		std::shared_ptr<Done> done; // Null if nothing waits for it.
	};
	std::thread thread;
	std::thread::id owner; // The thread that may use the device: the local device's own one.
	std::mutex mutex;      // Guards queue and stopping.
	std::condition_variable cv;
	std::vector<Work> queue;
	bool stopping = false;

	// loop runs the queued work, in order, until stop.
	void loop() {
		while (true) {
			std::vector<Work> batch;
			{
				std::unique_lock<std::mutex> lock(mutex);
				cv.wait(lock, [&] { return stopping || !queue.empty(); });
				if (queue.empty()) {
					return;
				}
				batch.swap(queue);
			}
			for (Work &w : batch) {
				w.f();
				if (w.done) {
					w.done->finish();
				}
			}
		}
	}

public:
	// linear_sampler returns the device's sampler, made on first use.
	RID linear_sampler() {
		if (!sampler.is_valid()) {
			Ref<RDSamplerState> state;
			state.instantiate();
			state->set_min_filter(RenderingDevice::SAMPLER_FILTER_LINEAR);
			state->set_mag_filter(RenderingDevice::SAMPLER_FILTER_LINEAR);
			state->set_repeat_u(RenderingDevice::SAMPLER_REPEAT_MODE_CLAMP_TO_EDGE);
			state->set_repeat_v(RenderingDevice::SAMPLER_REPEAT_MODE_CLAMP_TO_EDGE);
			sampler = rd->sampler_create(state);
		}
		return sampler;
	}
};

// force_cpu is whether @gpu functions always run on the CPU: in builds with gd++ build --nogpu.
#ifdef GDPP_GPU_FORCE_CPU
inline constexpr bool force_cpu = true;
#else
inline constexpr bool force_cpu = false;
#endif

// main_device returns the main RenderingDevice, or null without one, e.g. with the Compatibility renderer or
// --headless, or in builds with --nogpu.
inline Device *main_device() {
	static Device device;
	static std::once_flag once;
	std::call_once(once, [] {
		if (!force_cpu && RenderingServer::get_singleton()) {
			device.rd = RenderingServer::get_singleton()->get_rendering_device();
			device.main = true;
		}
	});
	return device.rd ? &device : nullptr;
}

// unload_hooked is whether the GPU runtime has hooked uninitialize, to free its resources.
inline std::atomic<bool> unload_hooked = false;
void free_resources();

// local_device returns the package's local RenderingDevice, made on first use if p_make, or null without a main one.
inline Device *local_device(bool p_make = true) {
	static Device device;
	static std::once_flag once;
	if (p_make) {
		std::call_once(once, [] {
			if (main_device()) {
				device.start();
			}
			if (!unload_hooked.exchange(true)) {
				on_unload(free_resources);
			}
		});
	}
	return device.rd ? &device : nullptr;
}

// Kernel is a @gpu function: its GLSL code, compiled on first use on each device.
class Kernel {
public:
	// The kernel named p_name, e.g. "Terrain.blur", with p_glsl, workgroups of p_group_size, and a CPU fallback if
	// p_cpu. If p_main, it runs on the main device, since it uses GPU-resident arguments or results. If p_sync, unless
	// @async, its calls return only once the GPU is done with it.
	Kernel(const char *p_name, const char *p_glsl, std::array<uint32_t, 3> p_group_size, bool p_main, bool p_cpu, bool p_sync) :
			name(p_name), glsl(p_glsl), group_size(p_group_size), main(p_main), cpu(p_cpu), sync(p_sync) {
		std::lock_guard<std::mutex> lock(registry_mutex());
		registry().push_back(this);
	}

	const char *name;
	const char *glsl;
	std::array<uint32_t, 3> group_size;
	bool main, cpu, sync;
	std::atomic<bool> warned_image_texture = false; // Whether a call warned that it writes an ImageTexture on the CPU.

	// Compiled is the kernel on one device.
	struct Compiled {
		bool tried = false, ok = false;
		RID shader, pipeline;
	};
	Compiled on_main, on_local;

	// device returns the device that the kernel runs on, compiled for it, or null if it runs on the CPU: without a
	// device, or if its code doesn't compile.
	Device *device() {
		Device *d = main ? main_device() : local_device();
		if (!d) {
			return nullptr;
		}
		Compiled &c = d->main ? on_main : on_local;
		if (!c.tried) {
			d->run([&] { compile(*d, c); }, true);
		}
		return c.ok ? d : nullptr;
	}
	// pipeline returns the kernel's pipeline and shader on p_device.
	const Compiled &compiled(const Device &p_device) const { return p_device.main ? on_main : on_local; }

	// registry lists all kernels, whose resources free_resources frees.
	static std::vector<Kernel *> &registry() {
		static std::vector<Kernel *> kernels;
		return kernels;
	}
	static std::mutex &registry_mutex() {
		static std::mutex mutex;
		return mutex;
	}

private:
	void compile(Device &p_device, Compiled &r_compiled) {
		if (r_compiled.tried) {
			return;
		}
		r_compiled.tried = true;
		Ref<RDShaderSource> source;
		source.instantiate();
		source->set_language(RenderingDevice::SHADER_LANGUAGE_GLSL);
		source->set_stage_source(RenderingDevice::SHADER_STAGE_COMPUTE, glsl);
		Ref<RDShaderSPIRV> spirv = p_device.rd->shader_compile_spirv_from_source(source);
		String error = spirv.is_valid() ? spirv->get_stage_compile_error(RenderingDevice::SHADER_STAGE_COMPUTE) : String("No GLSL compiler.");
		if (!error.is_empty()) {
			ERR_PRINT(vformat("Kernel %s failed to compile for the GPU, so it runs on the CPU:\n%s", name, error));
			return;
		}
		r_compiled.shader = p_device.rd->shader_create_from_spirv(spirv, name);
		if (r_compiled.shader.is_valid()) {
			r_compiled.pipeline = p_device.rd->compute_pipeline_create(r_compiled.shader);
		}
		r_compiled.ok = r_compiled.pipeline.is_valid();
	}
};

// free_resources frees the kernels' shaders and the local device when the package's library is unloaded.
inline void free_resources() {
	std::vector<Kernel *> kernels;
	{
		std::lock_guard<std::mutex> lock(Kernel::registry_mutex());
		kernels = Kernel::registry();
	}
	if (Device *d = main_device()) {
		d->run([&] {
			for (Kernel *k : kernels) {
				if (k->on_main.shader.is_valid()) {
					d->rd->free_rid(k->on_main.shader); // Frees the pipeline too.
				}
				k->on_main = {};
			}
			if (d->sampler.is_valid()) {
				d->rd->free_rid(d->sampler);
				d->sampler = RID();
			}
		},
				true);
	}
	if (Device *d = local_device(false)) {
		d->stop([&] {
			for (Kernel *k : kernels) {
				if (k->on_local.shader.is_valid()) {
					d->rd->free_rid(k->on_local.shader);
				}
				k->on_local = {};
			}
			if (d->sampler.is_valid()) {
				d->rd->free_rid(d->sampler);
				d->sampler = RID();
			}
			memdelete(d->rd);
			d->rd = nullptr;
		});
	}
}

// Shaders are the kernels of a class's shaders, by name, which @factory_shader's methods compile.
using Shaders = std::vector<std::pair<const char *, Kernel &(*)()>>;

// compile compiles all of p_shaders for the devices they run on, so that their first calls don't wait for it. Without
// a GPU, it does nothing.
inline void compile(const Shaders &p_shaders) {
	for (const auto &[name, kernel] : p_shaders) {
		kernel().device();
	}
}

// compile compiles the shader named p_shader, one of p_shaders, the shaders of the class p_class, like the other
// compile. Prints an error if there's no such shader.
inline void compile(const Shaders &p_shaders, const char *p_class, const StringName &p_shader) {
	for (const auto &[name, kernel] : p_shaders) {
		if (String(p_shader) == name) {
			kernel().device();
			return;
		}
	}
	ERR_PRINT(vformat("Class %s has no shader named %s.", p_class, p_shader));
}

// pixels_from_image converts any Image to pixels, e.g. for the CPU.
inline std::shared_ptr<Pixels> pixels_from_image(const Ref<Image> &p_image) {
	std::shared_ptr<Pixels> pixels = std::make_shared<Pixels>();
	if (p_image.is_null() || p_image->is_empty()) {
		return pixels;
	}
	Ref<Image> image = p_image->duplicate();
	if (image->is_compressed()) {
		image->decompress();
	}
	image->clear_mipmaps();
	image->convert(Image::FORMAT_RGBAF);
	pixels->width = image->get_width();
	pixels->height = image->get_height();
	pixels->data.resize(size_t(pixels->width) * size_t(pixels->height));
	PackedByteArray bytes = image->get_data();
	std::memcpy(pixels->data.data(), bytes.ptr(), std::min(size_t(bytes.size()), pixels->data.size() * sizeof(vec4)));
	return pixels;
}

// image_from_pixels converts pixels to an Image of p_format.
inline Ref<Image> image_from_pixels(const Pixels &p_pixels, GpuFormat p_format) {
	PackedByteArray bytes;
	bytes.resize(int64_t(p_pixels.data.size() * sizeof(vec4)));
	if (!p_pixels.data.empty()) {
		std::memcpy(bytes.ptrw(), p_pixels.data.data(), size_t(bytes.size()));
	}
	Ref<Image> image = Image::create_from_data(std::max(p_pixels.width, 1), std::max(p_pixels.height, 1), false, Image::FORMAT_RGBAF,
			p_pixels.data.empty() ? PackedByteArray() : bytes);
	if (image.is_valid() && !p_pixels.data.empty()) {
		image->convert(info(p_format).final);
	}
	return image;
}

} // namespace gpu

// GDPP_GPU_ARRAY_CLASS is the package's class of GPU arrays: arrays of floats, ints or vectors that stay on the GPU,
// where kernels read and write them. Without a GPU, they're arrays in memory.
class GDPP_GPU_ARRAY_CLASS : public RefCounted {
	GDPP_GDCLASS(GDPP_GPU_ARRAY_CLASS, RefCounted)

public:
	gpu::Elem elem = gpu::Elem::FLOAT;
	int64_t count = 0;
	RID buffer;               // On the main device, with a GPU.
	std::vector<uint8_t> cpu; // In memory, in the CPU's layout, without a GPU.

	~GDPP_GPU_ARRAY_CLASS() {
		if (buffer.is_valid()) {
			if (gpu::Device *d = gpu::main_device()) {
				RID rid = buffer;
				d->run([d, rid] { d->rd->free_rid(rid); }, false);
			}
		}
	}

	// make returns a new array of p_count elements of p_elem, all zero.
	static Ref<GDPP_GPU_ARRAY_CLASS> make(gpu::Elem p_elem, int64_t p_count) {
		Ref<GDPP_GPU_ARRAY_CLASS> array;
		array.instantiate();
		array->elem = p_elem;
		array->count = std::max<int64_t>(p_count, 0);
		const gpu::ElemInfo &e = gpu::info(p_elem);
		if (gpu::Device *d = gpu::main_device()) {
			GDPP_GPU_ARRAY_CLASS *self = array.ptr();
			d->run([d, self, e] {
				self->buffer = d->rd->storage_buffer_create(uint32_t(std::max<int64_t>(self->count * e.gpu_stride, 16)));
			},
					true);
		} else {
			array->cpu.assign(size_t(array->count * e.cpu_stride), 0);
		}
		return array;
	}

	// size returns how many elements the array has.
	int64_t size() const { return count; }

	// read returns the array's elements as a packed array, waiting for the kernels that write them.
	Variant read() const {
		if (!buffer.is_valid()) {
			return gpu::from_cpu(elem, cpu.data(), count);
		}
		std::vector<uint8_t> bytes = download();
		return gpu::from_cpu(elem, bytes.data(), count);
	}

	// write sets the array's elements from p_packed, a packed array of its element type and size.
	void write(const Variant &p_packed) {
		gpu::Elem e;
		ERR_FAIL_COND_MSG(!gpu::elem_of(p_packed, e) || e != elem, vformat("A GPU array of %s can't be written from a %s.", gpu::info(elem).name, Variant::get_type_name(p_packed.get_type())));
		std::vector<uint8_t> bytes = gpu::to_cpu(elem, p_packed);
		ERR_FAIL_COND_MSG(int64_t(bytes.size()) != count * gpu::info(elem).cpu_stride, vformat("A GPU array of size %d can't be written from an array of size %d.", count, int64_t(bytes.size()) / gpu::info(elem).cpu_stride));
		upload(bytes);
	}

	// from returns a new array with the elements of p_packed, a packed array of floats, ints, vectors or colors.
	static Ref<GDPP_GPU_ARRAY_CLASS> from(const Variant &p_packed) {
		gpu::Elem e;
		ERR_FAIL_COND_V_MSG(!gpu::elem_of(p_packed, e), Ref<GDPP_GPU_ARRAY_CLASS>(),
				vformat("A GPU array can't hold the elements of a %s: use a PackedFloat32Array, PackedInt32Array, PackedVector2Array, PackedVector3Array, PackedVector4Array or PackedColorArray.",
						Variant::get_type_name(p_packed.get_type())));
		std::vector<uint8_t> bytes = gpu::to_cpu(e, p_packed);
		Ref<GDPP_GPU_ARRAY_CLASS> array = make(e, int64_t(bytes.size()) / gpu::info(e).cpu_stride);
		array->upload(bytes);
		return array;
	}

	// download returns the elements in the CPU's layout, from the GPU.
	std::vector<uint8_t> download() const {
		PackedByteArray gpu_bytes;
		gpu::Device *d = gpu::main_device();
		RID rid = buffer;
		d->run([&] { gpu_bytes = d->rd->buffer_get_data(rid); }, true);
		return gpu::cpu_layout(elem, gpu_bytes, count);
	}
	// upload sets the elements from p_bytes in the CPU's layout.
	void upload(const std::vector<uint8_t> &p_bytes) {
		if (!buffer.is_valid()) {
			cpu = p_bytes;
			return;
		}
		PackedByteArray gpu_bytes = gpu::gpu_layout(elem, p_bytes.data(), count);
		if (gpu_bytes.is_empty()) {
			return;
		}
		gpu::Device *d = gpu::main_device();
		RID rid = buffer;
		d->run([d, rid, gpu_bytes] { d->rd->buffer_update(rid, 0, uint32_t(gpu_bytes.size()), gpu_bytes); }, false);
	}

protected:
	static void _bind_methods() {
		ClassDB::bind_method(D_METHOD("size"), &GDPP_GPU_ARRAY_CLASS::size);
		ClassDB::bind_method(D_METHOD("read"), &GDPP_GPU_ARRAY_CLASS::read);
		ClassDB::bind_method(D_METHOD("write", "packed"), &GDPP_GPU_ARRAY_CLASS::write);
		ClassDB::bind_static_method(get_class_static(), D_METHOD("from", "packed"), &GDPP_GPU_ARRAY_CLASS::from);
	}
};

// GDPP_GPU_TEXTURE_CLASS is the package's internal class of the textures that GD++ creates: a Texture2DRD that owns
// its RenderingDevice texture, and frees it when it's freed. Scripts see a Texture2DRD.
class GDPP_GPU_TEXTURE_CLASS : public Texture2DRD {
	GDPP_GDCLASS(GDPP_GPU_TEXTURE_CLASS, Texture2DRD)

public:
	RID owned; // The RenderingDevice texture, on the main device.
	GpuFormat format = GpuFormat::rgba8;

	// Frees the RenderingDevice texture later: after Texture2DRD's destructor, which runs next, frees the
	// RenderingServer's texture that wraps it.
	~GDPP_GPU_TEXTURE_CLASS() {
		gpu::Device *d = gpu::main_device();
		if (!owned.is_valid() || !d) {
			return;
		}
		RID rid = owned;
		auto free = [d, rid] {
			d->run([d, rid] { d->rd->free_rid(rid); }, false);
			return Variant();
		};
		Callable(memnew(TaskCallable(std::move(free)))).call_deferred();
	}

protected:
	static void _bind_methods() {}
};

namespace gpu {

// texture_usage is how the textures that GD++ creates are used: sampled, e.g. by materials, written by kernels, and
// read back and updated.
inline constexpr int64_t texture_usage = RenderingDevice::TEXTURE_USAGE_SAMPLING_BIT | RenderingDevice::TEXTURE_USAGE_STORAGE_BIT |
		RenderingDevice::TEXTURE_USAGE_CAN_UPDATE_BIT | RenderingDevice::TEXTURE_USAGE_CAN_COPY_FROM_BIT;

// create_texture creates a texture on p_device, of p_size and p_format, from p_data if it's not empty.
inline RID create_texture(Device &p_device, Vector2i p_size, RenderingDevice::DataFormat p_format, int64_t p_usage, const PackedByteArray &p_data) {
	Ref<RDTextureFormat> format;
	format.instantiate();
	format->set_format(p_format);
	format->set_width(uint32_t(std::max(p_size.x, 1)));
	format->set_height(uint32_t(std::max(p_size.y, 1)));
	format->set_usage_bits(p_usage);
	Ref<RDTextureView> view;
	view.instantiate();
	TypedArray<PackedByteArray> data;
	if (!p_data.is_empty()) {
		data.push_back(p_data);
	}
	return p_device.rd->texture_create(format, view, data);
}

} // namespace gpu

// gpu_texture returns a new texture of p_size and p_format, which kernels write and materials draw: a Texture2DRD on
// the GPU, and an ImageTexture without one. All its pixels are zero.
inline Ref<Texture2D> gpu_texture(Vector2i p_size, GpuFormat p_format) {
	p_size = Vector2i(std::max(p_size.x, 1), std::max(p_size.y, 1));
	gpu::Device *d = gpu::main_device();
	if (!d) {
		glsl::Pixels pixels;
		pixels.width = p_size.x;
		pixels.height = p_size.y;
		pixels.data.resize(size_t(p_size.x) * size_t(p_size.y));
		return ImageTexture::create_from_image(gpu::image_from_pixels(pixels, p_format));
	}
	Ref<GDPP_GPU_TEXTURE_CLASS> texture;
	texture.instantiate();
	texture->format = p_format;
	GDPP_GPU_TEXTURE_CLASS *self = texture.ptr();
	d->run([d, self, p_size, p_format] {
		self->owned = gpu::create_texture(*d, p_size, gpu::info(p_format).rd, gpu::texture_usage, PackedByteArray());
		d->rd->texture_clear(self->owned, Color(0, 0, 0, 0), 0, 1, 0, 1);
		self->set_texture_rd_rid(self->owned);
	},
			true);
	return texture;
}

// GpuArray<T> is a GPU array of T: float, int32_t (a GD++ int), Vector2, Vector3, Vector4 or Color. Its elements stay
// on the GPU, where @gpu functions read and write them, until read() copies them back. Copies share the array.
template <typename T>
class GpuArray {
public:
	using Packed = typename gpu::ElemOf<T>::Packed;

	// No array, which tests as false.
	GpuArray() = default;
	// An array of p_count elements, all zero.
	explicit GpuArray(int64_t p_count) :
			object(GDPP_GPU_ARRAY_CLASS::make(gpu::ElemOf<T>::elem, p_count)) {}
	// An array with the elements of p_packed.
	explicit GpuArray(const Packed &p_packed) :
			object(GDPP_GPU_ARRAY_CLASS::from(p_packed)) {}
	// The array that p_object holds, or none, with an error, if it's not a GPU array of T.
	explicit GpuArray(const Ref<GDPP_GPU_ARRAY_CLASS> &p_object) {
		if (p_object.is_valid() && p_object->elem == gpu::ElemOf<T>::elem) {
			object = p_object;
		} else if (p_object.is_valid()) {
			ERR_PRINT(vformat("Expected a GPU array of %s, but got one of %s.", gpu::info(gpu::ElemOf<T>::elem).name, gpu::info(p_object->elem).name));
		}
	}
	explicit GpuArray(const Variant &p_value) :
			GpuArray(Ref<GDPP_GPU_ARRAY_CLASS>(Object::cast_to<GDPP_GPU_ARRAY_CLASS>(p_value.operator Object *()))) {}

	explicit operator bool() const { return object.is_valid(); }
	operator Variant() const { return object; }

	// size returns how many elements it has.
	int64_t size() const { return object.is_valid() ? object->count : 0; }
	// read returns its elements, waiting for the kernels that write them.
	Packed read() const { return object.is_valid() ? Packed(object->read()) : Packed(); }
	// write sets its elements from p_packed, which must have its size.
	void write(const Packed &p_packed) {
		ERR_FAIL_COND_MSG(object.is_null(), "Can't write to an empty GpuArray.");
		object->write(p_packed);
	}

	// object returns the GPU array as the package's class of GPU arrays.
	const Ref<GDPP_GPU_ARRAY_CLASS> &ptr() const { return object; }

private:
	Ref<GDPP_GPU_ARRAY_CLASS> object;
};

namespace gpu {

// ReadBuffer is a packed array that a kernel reads, on the CPU.
template <typename T>
class ReadBuffer {
public:
	template <typename P>
	explicit ReadBuffer(const P &p_packed) {
		Elem e;
		Variant packed = p_packed;
		if (elem_of(packed, e)) {
			std::vector<uint8_t> bytes = to_cpu(e, packed);
			data.resize(bytes.size() / sizeof(T));
			std::memcpy(data.data(), bytes.data(), data.size() * sizeof(T));
		}
	}
	const T &operator[](int p_index) const {
#ifdef DEBUG_ENABLED
		if (p_index < 0 || size_t(p_index) >= data.size()) {
			return out_of_bounds(p_index);
		}
#endif
		return data[size_t(p_index)];
	}
	// length returns how many elements it has, like GLSL's arr.length().
	int length() const { return int(data.size()); }

private:
	std::vector<T> data;
	const T &out_of_bounds(int p_index) const {
		static const T none{};
		ERR_PRINT_ONCE(vformat("Kernel %s reads element %d of an array of size %d.", invocation().kernel, p_index, length()));
		return none;
	}
};

// RwBuffer is a GPU array that a kernel reads and writes, on the CPU: its memory, or a copy of its elements on the
// GPU, which it writes back once the last copy of it is gone.
template <typename T>
class RwBuffer {
public:
	template <typename G>
	explicit RwBuffer(const GpuArray<G> &p_array) :
			state(std::make_shared<State>()) {
		state->array = p_array.ptr();
		if (state->array.is_null()) {
			return;
		}
		if (state->array->buffer.is_valid()) {
			state->copy = state->array->download();
			state->data = reinterpret_cast<T *>(state->copy.data());
		} else {
			state->data = reinterpret_cast<T *>(state->array->cpu.data());
		}
		state->count = int(state->array->count);
	}
	T &operator[](int p_index) const {
#ifdef DEBUG_ENABLED
		if (p_index < 0 || p_index >= state->count) {
			static T none{};
			ERR_PRINT_ONCE(vformat("Kernel %s uses element %d of a GpuArray of size %d.", invocation().kernel, p_index, state->count));
			return none = T{};
		}
#endif
		return state->data[p_index];
	}
	int length() const { return state->count; }

private:
	struct State {
		Ref<GDPP_GPU_ARRAY_CLASS> array;
		std::vector<uint8_t> copy;
		T *data = nullptr;
		int count = 0;
		~State() {
			if (array.is_valid() && array->buffer.is_valid()) {
				array->upload(copy);
			}
		}
	};
	std::shared_ptr<State> state;
};

// sampled returns a sampled texture on the CPU, from an Image or a Texture2D.
inline sampler2D sampled(const Ref<Image> &p_image) {
	return sampler2D{ pixels_from_image(p_image) };
}
inline sampler2D sampled(const Ref<Texture2D> &p_texture) {
	return sampler2D{ pixels_from_image(p_texture.is_valid() ? p_texture->get_image() : Ref<Image>()) };
}

// writable returns a written texture on the CPU, from a Texture2D[p_format], which it updates once the kernel is
// done: a Texture2DRD's texture on the GPU, or an ImageTexture.
inline image2D writable(const Ref<Texture2D> &p_texture, GpuFormat p_format) {
	struct WriteBack : Pixels {
		Ref<Texture2D> texture;
		GpuFormat format;
		~WriteBack() {
			if (texture.is_null()) {
				return;
			}
			Ref<Image> image = image_from_pixels(*this, format);
			Ref<Texture2DRD> rd = texture;
			Device *d = main_device();
			if (rd.is_valid() && d) {
				RID rid = rd->get_texture_rd_rid();
				PackedByteArray bytes = image->get_data();
				d->run([d, rid, bytes] { d->rd->texture_update(rid, 0, bytes); }, false);
			} else if (Ref<ImageTexture> it = texture; it.is_valid()) {
				it->update(image);
			}
		}
	};
	std::shared_ptr<WriteBack> state = std::make_shared<WriteBack>();
	state->format = p_format;
	if (Ref<Texture2DRD>(p_texture).is_valid() || Ref<ImageTexture>(p_texture).is_valid()) {
		std::shared_ptr<Pixels> pixels = pixels_from_image(p_texture->get_image());
		static_cast<Pixels &>(*state) = *pixels;
		state->texture = p_texture;
	} else if (p_texture.is_valid()) {
		ERR_PRINT("A kernel can only write a Texture2DRD or an ImageTexture.");
	}
	return image2D{ state };
}

// Grid is the cells that a kernel's invocations run on: its first argument, an int, Vector2i or Vector3i.
struct Grid {
	int64_t size[3] = { 1, 1, 1 };
	int dims = 1;
	Grid(int64_t p_n) :
			size{ p_n, 1, 1 }, dims(1) {}
	Grid(const Vector2i &p_size) :
			size{ p_size.x, p_size.y, 1 }, dims(2) {}
	Grid(const Vector3i &p_size) :
			size{ p_size.x, p_size.y, p_size.z }, dims(3) {}
	int64_t cells() const { return size[0] * size[1] * size[2]; }
	bool valid() const { return size[0] >= 0 && size[1] >= 0 && size[2] >= 0; }
};

// cpu_run runs kernel p_k on the CPU, over p_grid, on the WorkerThreadPool: one task per workgroup, whose
// invocations run one after another. For each cell, p_store gets its flat index and what the body returned.
template <typename K, typename S>
void cpu_run(const Kernel &p_kernel, const K &p_k, const Grid &p_grid, S p_store) {
	struct Job {
		const Kernel *kernel;
		const K *k;
		const Grid *grid;
		S *store;
		uint32_t groups[3];
	};
	Job job{ &p_kernel, &p_k, &p_grid, &p_store, {} };
	uint32_t total = 1;
	for (int i = 0; i < 3; i++) {
		job.groups[i] = uint32_t((p_grid.size[i] + p_kernel.group_size[i] - 1) / p_kernel.group_size[i]);
		total *= job.groups[i];
	}
	if (total == 0) {
		return;
	}
	auto group = [](void *p_job, uint32_t p_index) {
		const Job &j = *static_cast<const Job *>(p_job);
		Invocation &inv = invocation();
		inv.kernel = j.kernel->name;
		inv.groups = uvec3(j.groups[0], j.groups[1], j.groups[2]);
		inv.group_size = uvec3(j.kernel->group_size[0], j.kernel->group_size[1], j.kernel->group_size[2]);
		inv.group_id = uvec3(p_index % j.groups[0], p_index / j.groups[0] % j.groups[1], p_index / j.groups[0] / j.groups[1]);
		for (uint32_t z = 0; z < j.kernel->group_size[2]; z++) {
			for (uint32_t y = 0; y < j.kernel->group_size[1]; y++) {
				for (uint32_t x = 0; x < j.kernel->group_size[0]; x++) {
					inv.local_id = uvec3(x, y, z);
					inv.local_index = (z * j.kernel->group_size[1] + y) * j.kernel->group_size[0] + x;
					inv.global_id = inv.group_id * inv.group_size + inv.local_id;
					const uvec3 &g = inv.global_id;
					if (g.x >= j.grid->size[0] || g.y >= j.grid->size[1] || g.z >= j.grid->size[2]) {
						continue;
					}
					int64_t flat = (int64_t(g.z) * j.grid->size[1] + int64_t(g.y)) * j.grid->size[0] + int64_t(g.x);
					typename K::Id id;
					if constexpr (std::is_same_v<typename K::Id, int>) {
						id = int(g.x);
					} else if constexpr (std::is_same_v<typename K::Id, ivec2>) {
						id = ivec2(g.x, g.y);
					} else {
						id = ivec3(g.x, g.y, g.z);
					}
					if constexpr (std::is_void_v<decltype(j.k->body(id))>) {
						j.k->body(id);
					} else {
						(*j.store)(flat, j.k->body(id));
					}
				}
			}
		}
	};
	if (total == 1) {
		group(&job, 0);
		return;
	}
	WorkerThreadPool *pool = WorkerThreadPool::get_singleton();
	pool->wait_for_group_task_completion(pool->add_native_group_task(group, &job, int(total), -1, true, p_kernel.name));
}

// Binding is an argument of a kernel on the GPU, other than a scalar, which goes into the uniform block.
struct Binding {
	enum Kind {
		BUFFER,  // A storage buffer: of bytes to upload, or a GPU array's.
		SAMPLER, // A sampled texture: of an image to upload, or a Texture2D's.
		IMAGE,   // A written texture: a Texture2DRD's, or an ImageTexture's, which it uploads and reads back.
	} kind;
	PackedByteArray bytes;          // To upload: a buffer's elements.
	Ref<Image> image;               // To upload: a sampled or written image, in a format that the device can use.
	Ref<RefCounted> holder;         // What owns the GPU resource, which stays alive until the kernel ran.
	RID rid;                        // The resource that exists already.
	Ref<ImageTexture> write_back;   // An ImageTexture to update after the kernel ran.
	RenderingDevice::DataFormat format = RenderingDevice::DATA_FORMAT_R8G8B8A8_UNORM;
};

// sampleable returns p_image in a format that the GPU samples as it is, or converted to RGBAF.
inline Ref<Image> sampleable(const Ref<Image> &p_image, RenderingDevice::DataFormat &r_format) {
	static const std::pair<Image::Format, RenderingDevice::DataFormat> direct[] = {
		{ Image::FORMAT_R8, RenderingDevice::DATA_FORMAT_R8_UNORM },
		{ Image::FORMAT_RG8, RenderingDevice::DATA_FORMAT_R8G8_UNORM },
		{ Image::FORMAT_RGBA8, RenderingDevice::DATA_FORMAT_R8G8B8A8_UNORM },
		{ Image::FORMAT_RF, RenderingDevice::DATA_FORMAT_R32_SFLOAT },
		{ Image::FORMAT_RGF, RenderingDevice::DATA_FORMAT_R32G32_SFLOAT },
		{ Image::FORMAT_RGBAF, RenderingDevice::DATA_FORMAT_R32G32B32A32_SFLOAT },
		{ Image::FORMAT_RH, RenderingDevice::DATA_FORMAT_R16_SFLOAT },
		{ Image::FORMAT_RGH, RenderingDevice::DATA_FORMAT_R16G16_SFLOAT },
		{ Image::FORMAT_RGBAH, RenderingDevice::DATA_FORMAT_R16G16B16A16_SFLOAT },
	};
	if (p_image.is_null() || p_image->is_empty()) {
		r_format = RenderingDevice::DATA_FORMAT_R8G8B8A8_UNORM;
		return Image::create_empty(1, 1, false, Image::FORMAT_RGBA8);
	}
	Ref<Image> image = p_image;
	if (image->has_mipmaps() || image->is_compressed()) {
		image = image->duplicate();
		if (image->is_compressed()) {
			image->decompress();
		}
		image->clear_mipmaps();
	}
	for (const auto &d : direct) {
		if (d.first == image->get_format()) {
			r_format = d.second;
			return image;
		}
	}
	image = image == p_image ? Ref<Image>(p_image->duplicate()) : image;
	image->convert(Image::FORMAT_RGBAF);
	r_format = RenderingDevice::DATA_FORMAT_R32G32B32A32_SFLOAT;
	return image;
}

// Call is one call of a kernel. The generated function of a @gpu function makes one, passes it the arguments in
// order, and runs it with what the function returns. The arguments that aren't scalars bind as 1, 2 and so on, and
// a result buffer or texture after them, like the GLSL that GD++ generates. Scalars, the grid first, go into the
// uniform block, at binding 0, laid out like std140.
class Call {
public:
	Call(Kernel &p_kernel, Grid p_grid) :
			kernel(p_kernel), grid(p_grid) {
		switch (grid.dims) {
			case 1:
				put(int(grid.size[0]));
				break;
			case 2:
				put(ivec2(int(grid.size[0]), int(grid.size[1])));
				break;
			default:
				put(ivec3(int(grid.size[0]), int(grid.size[1]), int(grid.size[2])));
				break;
		}
		ERR_FAIL_COND_MSG(!grid.valid(), vformat("Kernel %s can't run on a grid of a negative size.", kernel.name));
	}

	// Scalars, in the uniform block.
	void uniform(int64_t p_value) { put(int(p_value)); }
	void uniform(double p_value) { put(float(p_value)); }
	void uniform(bool p_value) { put(uint(p_value)); }
	void uniform(const Vector2 &p_value) { put(vec2(p_value)); }
	void uniform(const Vector2i &p_value) { put(ivec2(p_value)); }
	void uniform(const Vector3 &p_value) { put(vec3(p_value)); }
	void uniform(const Vector3i &p_value) { put(ivec3(p_value)); }
	void uniform(const Vector4 &p_value) { put(vec4(p_value)); }
	void uniform(const Vector4i &p_value) { put(ivec4(p_value)); }
	void uniform(const Color &p_value) { put(vec4(p_value)); }
	void uniform(const Basis &p_value) { put(mat3(p_value)); }
	void uniform(const Transform3D &p_value) { put(mat4x3(p_value)); }
	void uniform(const Projection &p_value) { put(mat4(p_value)); }

	// A packed array, which the kernel reads.
	template <typename P>
	void input(const P &p_packed) {
		Elem e;
		Variant packed = p_packed;
		elem_of(packed, e);
		std::vector<uint8_t> cpu_bytes = to_cpu(e, packed);
		Binding b{ Binding::BUFFER };
		b.bytes = gpu_layout(e, cpu_bytes.data(), int64_t(cpu_bytes.size()) / info(e).cpu_stride);
		bindings.push_back(b);
	}
	// A GPU array, which the kernel reads and writes.
	template <typename G>
	void array(const GpuArray<G> &p_array) {
		Binding b{ Binding::BUFFER };
		if (p_array) {
			b.rid = p_array.ptr()->buffer;
			b.holder = p_array.ptr();
		}
		bindings.push_back(b);
	}
	// An image or texture, which the kernel samples.
	void sampler(const Ref<Image> &p_image) {
		Binding b{ Binding::SAMPLER };
		b.image = sampleable(p_image, b.format);
		bindings.push_back(b);
	}
	void sampler(const Ref<Texture2D> &p_texture) {
		Binding b{ Binding::SAMPLER };
		if (p_texture.is_valid()) {
			b.rid = RenderingServer::get_singleton()->texture_get_rd_texture(p_texture->get_rid());
			b.holder = p_texture;
		}
		if (!b.rid.is_valid()) {
			b.image = sampleable(Ref<Image>(), b.format);
		}
		bindings.push_back(b);
	}
	// A texture of p_format, which the kernel writes.
	void image(const Ref<Texture2D> &p_texture, GpuFormat p_format) {
		Binding b{ Binding::IMAGE };
		b.format = info(p_format).rd;
		b.holder = p_texture;
		if (Ref<Texture2DRD> rd = p_texture; rd.is_valid()) {
			b.rid = rd->get_texture_rd_rid();
		} else if (Ref<ImageTexture> it = p_texture; it.is_valid()) {
			// The CPU writes an ImageTexture as it is. The GPU copies it there and back, which only a shader without
			// @async can wait for: see gpu().
			image_texture = true;
			if (kernel.sync) {
				b.image = it->get_image()->duplicate();
				b.image->convert(info(p_format).image);
				b.write_back = it;
			}
		} else {
			ERR_PRINT(vformat("Kernel %s writes a texture, which must be a Texture2DRD or an ImageTexture.", kernel.name));
			failed = true;
		}
		bindings.push_back(b);
	}

	// Results. Each runs the kernel: on the GPU, unless it runs on the CPU, where it calls p_make to make the kernel's
	// C++ code with the arguments.

	// result_buffer returns the packed array P, with what the body returns for each cell.
	template <typename P, typename F>
	P result_buffer(F p_make) {
		using K = std::invoke_result_t<F>;
		Elem e;
		elem_of(Variant(P()), e);
		if (Device *d = gpu()) {
			int64_t count = grid.cells();
			Binding out{ Binding::BUFFER };
			out.bytes.resize(std::max<int64_t>(count * info(e).gpu_stride, 16));
			bindings.push_back(out);
			PackedByteArray result;
			dispatch(*d, true, [&](const std::vector<RID> &p_rids) { result = d->rd->buffer_get_data(p_rids.back()); });
			std::vector<uint8_t> bytes = cpu_layout(e, result, count);
			return P(from_cpu(e, bytes.data(), count));
		}
		using T = decltype(std::declval<K>().body(std::declval<typename K::Id>()));
		std::vector<T> values(size_t(std::max<int64_t>(grid.cells(), 0)));
		if (cpu_ready()) {
			K k = p_make();
			cpu_run(kernel, k, grid, [&](int64_t p_index, const T &p_value) { values[size_t(p_index)] = p_value; });
		}
		return P(from_cpu(e, reinterpret_cast<const uint8_t *>(values.data()), int64_t(values.size())));
	}

	// result_image returns an Image of p_format, with what the body returns for each cell as a pixel.
	template <typename F>
	Ref<Image> result_image(GpuFormat p_format, F p_make) {
		Vector2i size(int(grid.size[0]), int(grid.size[1]));
		if (Device *d = gpu()) {
			Binding out{ Binding::IMAGE };
			out.format = info(p_format).rd;
			out.image = Image::create_empty(std::max(size.x, 1), std::max(size.y, 1), false, info(p_format).image);
			bindings.push_back(out);
			PackedByteArray result;
			dispatch(*d, true, [&](const std::vector<RID> &p_rids) { result = d->rd->texture_get_data(p_rids.back(), 0); });
			Ref<Image> image = Image::create_from_data(std::max(size.x, 1), std::max(size.y, 1), false, info(p_format).image, result);
			if (image.is_valid() && info(p_format).final != info(p_format).image) {
				image->convert(info(p_format).final); // An RGB format, which the GPU wrote as RGBA.
			}
			return image;
		}
		return image_from_pixels(*cpu_pixels(p_make), p_format);
	}

	// result_array returns a new GPU array of T, with what the body returns for each cell.
	template <typename T, typename F>
	GpuArray<T> result_array(F p_make) {
		using K = std::invoke_result_t<F>;
		GpuArray<T> result(grid.cells());
		if (Device *d = gpu()) {
			array(result);
			dispatch(*d, kernel.sync, nullptr);
			return result;
		}
		using V = typename ElemOf<T>::Glsl;
		if (cpu_ready()) {
			K k = p_make();
			RwBuffer<V> out(result);
			cpu_run(kernel, k, grid, [&](int64_t p_index, const V &p_value) { out[int(p_index)] = p_value; });
		}
		return result;
	}

	// result_texture returns a new texture of p_format, with what the body returns for each cell as a pixel.
	template <typename F>
	Ref<Texture2D> result_texture(GpuFormat p_format, F p_make) {
		Vector2i size(int(grid.size[0]), int(grid.size[1]));
		if (Device *d = gpu()) {
			Ref<GDPP_GPU_TEXTURE_CLASS> texture;
			texture.instantiate();
			texture->format = p_format;
			GDPP_GPU_TEXTURE_CLASS *self = texture.ptr();
			d->run([d, self, size, p_format] {
				self->owned = create_texture(*d, size, info(p_format).rd, texture_usage, PackedByteArray());
				self->set_texture_rd_rid(self->owned);
			},
					false);
			Binding out{ Binding::IMAGE };
			out.format = info(p_format).rd;
			out.holder = texture;
			bindings.push_back(out);
			dispatch(*d, kernel.sync, nullptr, self);
			return texture;
		}
		return ImageTexture::create_from_image(image_from_pixels(*cpu_pixels(p_make), p_format));
	}

	// run runs a kernel that returns nothing: it writes its GPU arrays and textures. It waits for the GPU unless
	// @async.
	template <typename F>
	void run(F p_make) {
		using K = std::invoke_result_t<F>;
		if (Device *d = gpu()) {
			dispatch(*d, kernel.sync, nullptr);
			return;
		}
		if (cpu_ready()) {
			K k = p_make();
			cpu_run(kernel, k, grid, [](int64_t, const auto &) {});
		}
	}

private:
	Kernel &kernel;
	Grid grid;
	PackedByteArray block; // The uniform block.
	std::vector<Binding> bindings;
	bool failed = false;
	bool image_texture = false; // Whether it writes an ImageTexture.

	// put appends a scalar to the uniform block, aligned like std140: 4 bytes for scalars, 8 for 2 components, 16
	// for 3 or 4, and each column of a matrix like a vec4.
	template <typename V>
	void put(const V &p_value) {
		int64_t align = 4, size = 4;
		const void *bytes = &p_value;
		float columns[16] = {};
		if constexpr (is_vec<V>::value) {
			size = 4 * components<V>::value;
			align = components<V>::value == 2 ? 8 : 16;
		} else if constexpr (!std::is_arithmetic_v<V>) { // A matrix.
			constexpr int C = sizeof(V) / sizeof(p_value.cols[0]);
			constexpr int R = components<std::decay_t<decltype(p_value.cols[0])>>::value;
			for (int c = 0; c < C; c++) {
				for (int r = 0; r < R; r++) {
					columns[c * 4 + r] = p_value.cols[c].data[r];
				}
			}
			bytes = columns;
			align = 16;
			size = 16 * C;
		}
		int64_t offset = (block.size() + align - 1) / align * align;
		block.resize(offset + size);
		std::memcpy(block.ptrw() + offset, bytes, size_t(size));
	}

	// gpu returns the device to run on, or null to run on the CPU.
	Device *gpu() {
		if (failed || !grid.valid()) {
			return nullptr;
		}
		Device *d = kernel.device();
		if (d && image_texture && !kernel.sync) {
			// It writes an ImageTexture, which needs a copy back that the call can't wait for: the CPU writes it instead.
			if (!kernel.warned_image_texture.exchange(true)) {
				WARN_PRINT(vformat("Shader %s writes an ImageTexture, so it runs on the CPU: an @async shader returns before the GPU is done, "
								   "and can't copy it back. Pass a texture that a shader or gpu_texture() made, or remove @async.",
						kernel.name));
			}
			return nullptr;
		}
		return d;
	}

	// cpu_ready reports whether the kernel can run on the CPU.
	bool cpu_ready() {
		if (failed || !grid.valid()) {
			return false;
		}
		if (!kernel.cpu) {
			ERR_PRINT_ONCE(vformat("Kernel %s uses barrier() or shared variables, which have no CPU fallback, so it returns nothing.", kernel.name));
			return false;
		}
		return true;
	}

	// cpu_pixels runs the kernel on the CPU, and returns the pixels that it returns.
	template <typename F>
	std::shared_ptr<Pixels> cpu_pixels(F p_make) {
		using K = std::invoke_result_t<F>;
		std::shared_ptr<Pixels> pixels = std::make_shared<Pixels>();
		pixels->width = int(std::max<int64_t>(grid.size[0], 1));
		pixels->height = int(std::max<int64_t>(grid.size[1], 1));
		pixels->data.resize(size_t(pixels->width) * size_t(pixels->height), vec4(0.0f, 0.0f, 0.0f, 1.0f));
		if (cpu_ready()) {
			K k = p_make();
			cpu_run(kernel, k, grid, [&](int64_t p_index, const auto &p_value) {
				vec4 &px = pixels->data[size_t(p_index)];
				if constexpr (is_vec<std::decay_t<decltype(p_value)>>::value) {
					for (int i = 0; i < components<std::decay_t<decltype(p_value)>>::value; i++) {
						px.data[i] = float(p_value.data[i]);
					}
				} else {
					px.x = float(p_value);
				}
			});
		}
		return pixels;
	}

	// dispatch runs the kernel on p_device with the bindings, then p_after with their resources, before freeing
	// those it made. It waits for that if p_wait, and else returns right away. p_texture, if any, is a texture
	// result, which it binds last.
	void dispatch(Device &p_device, bool p_wait, std::function<void(const std::vector<RID> &)> p_after, GDPP_GPU_TEXTURE_CLASS *p_texture = nullptr) {
		Device *d = &p_device;
		Kernel *k = &kernel;
		uint32_t groups[3];
		for (int i = 0; i < 3; i++) {
			groups[i] = uint32_t(std::max<int64_t>((grid.size[i] + k->group_size[i] - 1) / k->group_size[i], 0));
		}
		PackedByteArray uniforms = block;
		uniforms.resize((uniforms.size() + 15) / 16 * 16);
		std::vector<Binding> bs = bindings;
		Ref<GDPP_GPU_TEXTURE_CLASS> texture = p_texture;
		auto work = [d, k, groups, uniforms, bs, texture, p_after] {
			RenderingDevice *rd = d->rd;
			std::vector<RID> rids, made;
			TypedArray<RDUniform> list;
			auto add = [&](int p_binding, RenderingDevice::UniformType p_type, RID p_rid, RID p_sampler = RID()) {
				Ref<RDUniform> u;
				u.instantiate();
				u->set_binding(p_binding);
				u->set_uniform_type(p_type);
				if (p_sampler.is_valid()) {
					u->add_id(p_sampler);
				}
				u->add_id(p_rid);
				list.push_back(u);
			};
			RID ubo = rd->uniform_buffer_create(uint32_t(uniforms.size()), uniforms);
			made.push_back(ubo);
			add(0, RenderingDevice::UNIFORM_TYPE_UNIFORM_BUFFER, ubo);
			for (size_t i = 0; i < bs.size(); i++) {
				const Binding &b = bs[i];
				RID rid = b.rid;
				if (texture.is_valid() && i + 1 == bs.size()) {
					rid = texture->owned;
				}
				switch (b.kind) {
					case Binding::BUFFER:
						if (!rid.is_valid()) {
							PackedByteArray bytes = b.bytes;
							if (bytes.size() < 16) {
								bytes.resize(16);
							}
							rid = rd->storage_buffer_create(uint32_t(bytes.size()), bytes);
							made.push_back(rid);
						}
						add(int(i) + 1, RenderingDevice::UNIFORM_TYPE_STORAGE_BUFFER, rid);
						break;
					case Binding::SAMPLER:
						if (!rid.is_valid()) {
							rid = create_texture(*d, b.image->get_size(), b.format, RenderingDevice::TEXTURE_USAGE_SAMPLING_BIT, b.image->get_data());
							made.push_back(rid);
						}
						add(int(i) + 1, RenderingDevice::UNIFORM_TYPE_SAMPLER_WITH_TEXTURE, rid, d->linear_sampler());
						break;
					case Binding::IMAGE:
						if (!rid.is_valid()) {
							rid = create_texture(*d, b.image->get_size(), b.format, texture_usage, b.image->get_data());
							made.push_back(rid);
						}
						add(int(i) + 1, RenderingDevice::UNIFORM_TYPE_IMAGE, rid);
						break;
				}
				rids.push_back(rid);
			}
			const Kernel::Compiled &c = k->compiled(*d);
			RID set = rd->uniform_set_create(list, c.shader, 0);
			int64_t compute = rd->compute_list_begin();
			rd->compute_list_bind_compute_pipeline(compute, c.pipeline);
			rd->compute_list_bind_uniform_set(compute, set, 0);
			if (groups[0] && groups[1] && groups[2]) {
				rd->compute_list_dispatch(compute, groups[0], groups[1], groups[2]);
			}
			rd->compute_list_end();
			if (!d->main) {
				rd->submit();
				rd->sync();
			} else if (k->sync && !p_after) {
				// Reading any buffer back makes the main device run its queued work, and wait for the GPU to finish it.
				rd->buffer_get_data(ubo, 0, 4);
			}
			for (size_t i = 0; i < bs.size(); i++) {
				if (bs[i].write_back.is_valid()) {
					PackedByteArray bytes = rd->texture_get_data(rids[i], 0);
					bs[i].write_back->update(Image::create_from_data(bs[i].image->get_width(), bs[i].image->get_height(), false, bs[i].image->get_format(), bytes));
				}
			}
			if (p_after) {
				p_after(rids);
			}
			rd->free_rid(set);
			for (RID rid : made) {
				rd->free_rid(rid);
			}
		};
		d->run(work, p_wait);
	}
};

} // namespace gpu

} // namespace gdpp

namespace godot {

// Bindings see a GpuArray as an object of the package's class of GPU arrays.

template <typename T>
struct GetTypeInfo<gdpp::GpuArray<T>> {
	static constexpr GDExtensionVariantType VARIANT_TYPE = GDEXTENSION_VARIANT_TYPE_OBJECT;
	static constexpr GDExtensionClassMethodArgumentMetadata METADATA = GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE;
	static inline PropertyInfo get_class_info() {
		return PropertyInfo(Variant::OBJECT, "", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT, gdpp::gpu_array_class);
	}
};

template <typename T>
struct PtrToArg<gdpp::GpuArray<T>> {
	_FORCE_INLINE_ static gdpp::GpuArray<T> convert(const void *p_ptr) {
		return gdpp::GpuArray<T>(Ref<gdpp::GDPP_GPU_ARRAY_CLASS>(PtrToArg<Ref<gdpp::GDPP_GPU_ARRAY_CLASS>>::convert(p_ptr)));
	}
	typedef Ref<gdpp::GDPP_GPU_ARRAY_CLASS> EncodeT;
	_FORCE_INLINE_ static void encode(const gdpp::GpuArray<T> &p_val, void *p_ptr) {
		PtrToArg<Ref<gdpp::GDPP_GPU_ARRAY_CLASS>>::encode(p_val.ptr(), p_ptr);
	}
};

template <typename T>
struct VariantCaster<gdpp::GpuArray<T>> {
	static _FORCE_INLINE_ gdpp::GpuArray<T> cast(const Variant &p_variant) {
		return gdpp::GpuArray<T>(p_variant);
	}
};

template <typename T>
struct GetTypeInfo<const gdpp::GpuArray<T> &> : GetTypeInfo<gdpp::GpuArray<T>> {};

template <typename T>
struct PtrToArg<const gdpp::GpuArray<T> &> : PtrToArg<gdpp::GpuArray<T>> {};

template <typename T>
struct VariantCaster<const gdpp::GpuArray<T> &> : VariantCaster<gdpp::GpuArray<T>> {};

} // namespace godot

// The GPU runtime's types and functions that user code uses, without the gdpp namespace.
using gdpp::GpuArray;
using gdpp::GpuFormat;
using gdpp::gpu_texture;

#endif // GDPP_SYNTAX_1_GPU_HPP
