package syntax_1

import (
	"fmt"
	"regexp"
	"slices"
	"strings"
)

// source returns the C++ source <name>.cpp of the unit's one class, named name: method definitions and bindings.
func (u *unit) source(name string) string {
	w := &writer{self: name + ".cpp", source: u.opts.SourceName}
	w.ln("// Generated by GD++ from %s, do not edit.", u.opts.SourceName)
	w.ln("")
	if u.debugging() {
		w.ln("#define GDPP_DEBUGGING")
	}
	w.ln("#include %q", name+".h")
	header := map[string]bool{}
	names, _ := u.headerNames()
	for _, name := range names {
		header[name] = true
	}
	if incs := u.includes(u.sourceNames(), header); len(incs) > 0 {
		w.ln("")
		for _, inc := range incs {
			w.ln("#include %s", inc)
		}
	}
	if slices.ContainsFunc(u.classes, func(c *classModel) bool {
		return slices.ContainsFunc(c.funcs, func(f *funcModel) bool { return f.coro != nil })
	}) {
		// GCC warns about the types without linkage in a coroutine's frame, e.g. of a lambda in a variable that lives
		// across an await, though the frame never leaves this file.
		w.ln("")
		w.ln("#if defined(__GNUC__) && !defined(__clang__)")
		w.ln("#pragma GCC diagnostic ignored \"-Wsubobject-linkage\"")
		w.ln("#endif")
	}
	u.globals(w, false)
	for _, c := range u.classes {
		u.shaderDefs(w, c)
	}
	w.ln("")
	w.ln("namespace godot {")
	for _, c := range u.classes {
		u.classDefs(w, c)
	}
	w.ln("")
	w.ln("} // namespace godot")
	return w.String()
}

func (u *unit) classDefs(w *writer, c *classModel) {
	w.signals = nil // A bare `await NAME` awaits the class's signal NAME.
	for _, s := range c.signals {
		w.signals = append(w.signals, s.s.Name)
	}
	defer func() { w.signals = nil }()
	w.ln("")
	w.ln("#define This %s", c.name)
	w.ln("")
	w.ln("void %s::_bind_methods() {", c.name)
	u.bindings(w, c)
	w.ln("}")
	if len(c.allTraits) > 0 {
		w.ln("")
		w.ln("void %s::_gdpp_traits(gdpp::TraitsOf<%s>) {", c.name, c.name)
		for _, t := range c.allTraits {
			w.ln("	gdpp::implement<%s, %s>();", t, c.name)
		}
		w.ln("}")
		if !c.refCounted {
			w.ln("")
			w.ln("void %s::_gdpp_destroy() {", c.name)
			w.ln("	gdpp::destroy(this);")
			w.ln("}")
		}
		if u.traitsNeedQueue(c) {
			w.ln("")
			w.ln("void %s::_gdpp_queue_destroy() {", c.name)
			w.ln("	gdpp::queue_destroy(this);")
			w.ln("}")
		}
	}
	if c.needsCtor() {
		w.ln("")
		w.ln("%s::%s() {", c.name, c.name)
		if c.pool != nil {
			// Whether the pool reserves this object, unused, so it skips its @recycle parts until the pool hands it out.
			w.ln("\tconst bool _gdpp_reserved = std::exchange(gdpp::reserving(), false);")
		}
		if c.trace {
			w.ln("\tgdpp::trace_lifetime(%q, this, true);", c.name)
		}
		for _, g := range c.groups {
			w.ln("\tadd_to_group(GDPP_STRING_NAME(%q));", g)
		}
		for _, f := range c.funcs {
			if r := f.rpc; r != nil {
				w.ln("\tgdpp::rpc_config<This>(this, %q, %s, %s, %t, %s);", f.f.Name, r.mode, r.transfer, r.callLocal, r.channel)
			}
			if setter := processing[f.f.Name]; f.override && setter != "" {
				w.ln("\t%s(true);", setter)
			}
		}
		for _, n := range c.notifs {
			if n.setter != "" {
				w.ln("\t%s(true);", n.setter)
			}
		}
		for _, v := range c.vars {
			switch {
			case v.v.Init == nil || v.onready:
			case v.recycle != nil:
				w.ln("\tif (!_gdpp_reserved) {")
				initializer(w, v, "\t\t")
				w.ln("\t}")
			default:
				initializer(w, v, "\t")
			}
		}
		// Initial values set up the objects in the editor too, so the inspector shows them.
		if c.ctor != nil || c.recycleCtor != nil && !c.recycleCtorOnly {
			guard(w, c.only, "")
		}
		if c.ctor != nil {
			w.block(c.ctor, "\t{", "}", assertVoid)
		}
		if c.recycleCtor != nil && !c.recycleCtorOnly {
			recycleBlock(w, c.recycleCtor, "\tif (!_gdpp_reserved) {")
		}
		w.ln("}")
	}
	if c.needsDtor() {
		w.ln("")
		w.ln("%s::~%s() {", c.name, c.name)
		guard(w, c.only, "")
		if c.trace {
			w.ln("\tgdpp::trace_lifetime(%q, this, false);", c.name)
		}
		// Unless the object rests in its pool, which already ran it.
		if c.recycleDtor != nil && !c.recycleDtorOnly {
			recycleBlock(w, c.recycleDtor, "\tif (!_gdpp_pool_slot.given) {")
		}
		if c.dtor != nil {
			w.block(c.dtor, "\t{", "}", assertVoid)
		}
		if c.pool != nil {
			w.ln("\t_gdpp_pool.forget(this);")
		}
		w.ln("}")
	}
	if c.pool != nil {
		recycler(w, c, "ctor", c.recycleCtor)
		recycler(w, c, "dtor", c.recycleDtor)
	}
	// The methods of @factory.
	for _, role := range factoryRoles {
		name, ok := c.factory[role]
		if !ok {
			continue
		}
		ret, params, guardRet := "void ", "", ""
		body := map[string]string{"create": fmt.Sprintf("return gdpp::create<%s>();", c.name), "destroy": "gdpp::destroy(this);",
			"queue_destroy": "gdpp::queue_destroy(this);", "pool_reserve": "_gdpp_pool.reserve(p_count, p_mode);",
			"pool_clear": "_gdpp_pool.clear(p_keep_in_use);", "scene_cache": fmt.Sprintf("gdpp::scene<%s>();", c.name),
			"scene_evict": fmt.Sprintf("gdpp::evict_scene<%s>();", c.name)}[role]
		switch role {
		case "create":
			ret, guardRet = withSpace(c.createType()), c.createType()
		case "pool_reserve":
			params = "int64_t p_count, const String &p_mode"
		case "pool_clear":
			params = "bool p_keep_in_use"
		}
		if strings.HasPrefix(role, "compile_shader") {
			if !strings.HasPrefix(role, "compile_shaders") {
				params = "const StringName &p_shader"
			}
			body = compileCall(c, role) + ";"
			task := fmt.Sprintf("(nullptr, %q, [=] { %s; });", c.name+"."+name, compileCall(c, role))
			switch {
			case strings.HasSuffix(role, "_async"):
				ret, guardRet, body = "gdpp::Async<void> ", "gdpp::Async<void>", "return gdpp::run_task"+task
			case strings.HasSuffix(role, "_detached"):
				body = "gdpp::run_detached" + task
			}
		}
		w.ln("")
		w.ln("%s%s::%s(%s) {", ret, c.name, name, params)
		guard(w, c.only, guardRet)
		w.ln("\t%s", body)
		w.ln("}")
	}
	if c.needsNotification() {
		w.ln("")
		w.ln("void %s::_notification(int WHAT) {", c.name)
		guard(w, c.only, "")
		// POST_ENTER_TREE comes right before each READY, once the children are ready, but also on each later entry.
		if c.hasOnready() {
			w.ln("\tif (WHAT == NOTIFICATION_POST_ENTER_TREE && !is_node_ready()) {")
			once := false // Whether the values are in a block that only runs the first time an object gets ready.
			for _, v := range c.vars {
				if v.v.Init == nil || !v.onready {
					continue
				}
				if o := c.pool != nil && v.recycle == nil; o != once {
					if once {
						w.ln("\t\t}")
					} else {
						w.ln("\t\tif (!_gdpp_pool_slot.readied) {")
					}
					once = o
				}
				if once {
					initializer(w, v, "\t\t\t")
				} else {
					initializer(w, v, "\t\t")
				}
			}
			if once {
				w.ln("\t\t}")
			}
			w.ln("\t}")
		}
		for _, n := range c.notifs {
			if n.cond == "true" {
				w.ln("\t%s;", n.call)
			} else {
				w.ln("\tif (%s) {", n.cond)
				w.ln("\t\t%s;", n.call)
				w.ln("\t}")
			}
		}
		// After the engine's READY, which runs an @override _ready.
		if c.readyOnce {
			w.ln("\tif (WHAT == NOTIFICATION_READY) {")
			w.ln("\t\t_gdpp_pool_slot.readied = true;")
			w.ln("\t}")
		}
		w.ln("}")
	}
	for _, f := range c.funcs {
		u.funcDef(w, c, f)
		defaultDefs(w, c, f)
		if f.rpc != nil {
			w.ln("")
			w.ln("Error %s::%s {", c.name, rpcDecl(f, params(nil, f.params, f.f.Params)))
			guard(w, f.only, "Error")
			w.ln("\treturn %s;", rpcCall(f))
			w.ln("}")
		}
	}
	for _, v := range c.vars {
		u.accessorDefs(w, c, v)
	}
	for _, s := range c.signals {
		w.ln("")
		w.ln("gdpp::Emitted %s::%s(%s) {", c.name, s.s.Name, params(nil, s.params, s.s.Params))
		guard(w, c.only, "gdpp::Emitted")
		if s.trace {
			w.ln("\tgdpp::trace_emit(this, %q%s);", s.s.Name, namedArgs(s.s.Params))
		}
		w.ln("\treturn gdpp::Emitted{ emit_signal(GDPP_STRING_NAME(%q)%s) };", s.s.Name, args(s.params, s.s.Params))
		w.ln("}")
	}
	for _, code := range c.codes {
		if code.Impl {
			w.ln("")
			w.block(code.Body, "", "", assertAny)
		}
	}
	w.ln("")
	w.ln("#undef This")
}

// generationRegexp matches the use of GENERATION, which on blocks and @recycle ctor, dtor and _ready can read.
var generationRegexp = regexp.MustCompile(`\bGENERATION\b`)

// initializer writes the assignment of var v's initial value, or of its type's default if it has none.
func initializer(w *writer, v *varModel, indent string) {
	switch init := v.v.Init; {
	case init == nil:
		w.ln("%s%s = {};", indent, v.v.Name)
	case init.Block != nil:
		w.block(init.Block, fmt.Sprintf("%s%s = [&]() -> %s {", indent, v.v.Name, v.t.cpp), "}();", assertValue)
	default:
		w.user(init.Pos, init.Origin, indent+v.v.Name+" = ", init.Expr, ";", assertValue)
	}
}

// recycler writes the method of @pool class c that its pool calls when it reuses an object, for the keyword ctor, or
// keeps one, for dtor: it runs body, the @recycle block, if any, after resetting the @recycle vars for ctor.
func recycler(w *writer, c *classModel, keyword string, body *Block) {
	w.ln("")
	w.ln("void %s::_gdpp_recycle_%s() {", c.name, keyword)
	guard(w, c.only, "")
	if c.trace {
		w.ln("\tgdpp::trace_recycle(%q, this, %t);", c.name, keyword == "ctor")
	}
	for _, v := range c.vars {
		if v.recycle != nil && !v.onready && keyword == "ctor" {
			initializer(w, v, "\t")
		}
	}
	if body != nil {
		recycleBlock(w, body, "\t{")
	}
	w.ln("}")
}

// recycleBlock writes body, a @recycle ctor or dtor block, after the line open, declaring GENERATION if it's used.
func recycleBlock(w *writer, body *Block, open string) {
	if generationRegexp.MatchString(body.Text) {
		w.ln("%s", open)
		w.ln("\t\tconst uint64_t GENERATION = _gdpp_pool_slot.generation;")
		open = ""
	}
	w.block(body, open, "}", assertVoid)
}

// guard writes the check of code that only runs on one side, only. For "game", @game_only code, it returns right
// away, with a default value, when the editor calls it. The editor only loads debug builds, so release builds skip
// the check. For "editor", @editor_only code, it returns when the game calls it. Nothing if only is empty. ret is the
// C++ return type, empty for constructors and destructors.
func guard(w *writer, only string, ret string) {
	if ret == "" || ret == "void" {
		guardWith(w, only, "return;")
	} else {
		guardWith(w, only, "return {};")
	}
}

// guardWith is guard with its own lines of code to run on the other side.
func guardWith(w *writer, only string, lines ...string) {
	switch only {
	case "game":
		w.ln("#ifdef DEBUG_ENABLED")
		w.ln("\tif (Engine::get_singleton()->is_editor_hint()) {")
	case "editor":
		w.ln("\tif (!Engine::get_singleton()->is_editor_hint()) {")
	default:
		return
	}
	for _, line := range lines {
		w.ln("\t\t%s", line)
	}
	w.ln("\t}")
	if only == "game" {
		w.ln("#endif")
	}
}

// debugging reports whether the unit's source uses the runtime's code for @trace and @profile.
func (u *unit) debugging() bool {
	return slices.ContainsFunc(u.classes, func(c *classModel) bool {
		return c.trace || slices.ContainsFunc(c.funcs, func(f *funcModel) bool { return f.trace || f.profile }) ||
			slices.ContainsFunc(c.vars, func(v *varModel) bool { return v.trace || v.profile }) ||
			slices.ContainsFunc(c.signals, func(s *signalModel) bool { return s.trace })
	})
}

// namedArgs returns ", " followed by the names and values of the parameters, alternating, as the runtime's
// debugging code takes them, or "" if there are none.
func namedArgs(list []*Param) string {
	s := ""
	for _, p := range list {
		s += fmt.Sprintf(", %q, %s", p.Name, p.Name)
	}
	return s
}

// debugHooks writes the code of the @profile and @trace annotations that are on for f, a function of c, and of the
// class's @trace vars, which f watches unless it can't change them.
func (u *unit) debugHooks(w *writer, c *classModel, f *funcModel) {
	name := strings.TrimPrefix(f.f.Name, "_gdpp_body_")
	if f.profile {
		u.profile(w, c.name+"."+name)
	}
	self := "this"
	if f.static {
		self = "nullptr"
	}
	switch {
	case f.trace && f.coro != nil: // A Trace or Watch would outlive the call, in the coroutine's frame.
		w.ln("\tgdpp::trace_coroutine(%q, %s, %q%s);", c.name, self, name, namedArgs(f.f.Params))
		return
	case f.trace:
		w.ln("\tgdpp::Trace _gdpp_trace(%q, %s, %q%s);", c.name, self, name, namedArgs(f.f.Params))
	}
	if !f.static && !f.isConst && f.deferral == "" && f.coro == nil {
		watch(w, c, name)
	}
}

// profile writes the Profile of the function that the tables and monitors call label, e.g. "Player.take_damage".
func (u *unit) profile(w *writer, label string) {
	print := ""
	if u.opts.ProfilePeriod > 0 {
		print = fmt.Sprintf(", %d", u.opts.ProfilePeriod)
	}
	if u.opts.ProfilePeriod > 0 && u.opts.ProfileFPS > 0 {
		print += fmt.Sprintf(", %d", u.opts.ProfileFPS)
	}
	w.ln("\tstatic gdpp::ProfileStats _gdpp_stats(%q%s);", label, print)
	w.ln("\tgdpp::Profile _gdpp_profile(_gdpp_stats);")
}

// watch writes the Watch of c's @trace vars, if any, in its function named name.
func watch(w *writer, c *classModel, name string) {
	vars := ""
	for _, v := range c.vars {
		switch {
		case !v.trace:
		case v.v.Property == nil:
			vars += fmt.Sprintf(", %q, [&] { return %s; }", v.v.Name, v.v.Name)
		default:
			vars += fmt.Sprintf(", %q, [&] { return %s(); }", v.v.Name, v.getter)
		}
	}
	if vars != "" {
		w.ln("\tgdpp::Watch _gdpp_watch(this, %q%s);", name, vars)
	}
}

// qualified returns the out-of-class declarator of a method of c, e.g. "int64_t MyNode::f(int64_t a) const".
func qualified(c *classModel, ret, name, params string, isConst bool) string {
	s := fmt.Sprintf("%s%s::%s(%s)", withSpace(ret), c.name, name, params)
	if isConst {
		s += " const"
	}
	return s
}

// castList converts arguments between enums and the class's tags: toTag converts enums to tags, else tags to enums.
func castList(c *classModel, types []*gtype, list []*Param, toTag bool) string {
	var as []string
	for i, t := range types {
		as = append(as, cast(c, t, list[i].Name, toTag))
	}
	return strings.Join(as, ", ")
}

func cast(c *classModel, t *gtype, expr string, toTag bool) string {
	switch {
	case t.enum == nil:
		return expr
	case toTag:
		return fmt.Sprintf("static_cast<%s>(%s)", tagName(c, t.enum), expr)
	}
	return fmt.Sprintf("static_cast<%s>(%s)", t.cpp, expr)
}

func (u *unit) funcDef(w *writer, c *classModel, f *funcModel) {
	w.ln("")
	w.ln("%s {", qualified(c, f.ret.cpp, f.f.Name, params(nil, f.params, f.f.Params), f.isConst))
	switch {
	case f.coro == nil:
		guard(w, f.only, f.ret.cpp)
	case f.hidden == "notif": // Else the func that starts the coroutine guards it.
		guardWith(w, f.only, "co_return;")
	}
	if f.once && f.override {
		w.ln("\tif (_gdpp_pool_slot.readied) {")
		w.ln("\t\treturn;")
		w.ln("\t}")
	}
	u.debugHooks(w, c, f)
	if (f.recycle != nil || f.hidden == "notif") && f.f.Body != nil && generationRegexp.MatchString(f.f.Body.Text) {
		if c.pool != nil {
			w.ln("\tconst uint64_t GENERATION = _gdpp_pool_slot.generation;")
		} else {
			w.ln("\tconstexpr uint64_t GENERATION = 0;")
		}
	}
	// A traced function that returns a value runs as a lambda, so the trace gets the value. A coroutine can't.
	wrap := f.trace && !f.ret.void && f.coro == nil
	if wrap {
		w.ln("\treturn _gdpp_trace.ret([&]() -> %s {", f.ret.cpp)
	}
	if f.virtualOf != "" {
		owner := &classModel{name: f.virtualOf} // Its GDVIRTUAL uses its enum tags.
		callArgs := castList(owner, f.params, f.f.Params, true)
		switch {
		case f.ret.void:
			w.ln("\tif (GDVIRTUAL_CALL(%s)) {", strings.Join(slices.DeleteFunc([]string{f.f.Name, callArgs}, func(s string) bool { return s == "" }), ", "))
			w.ln("\t\treturn;")
		case f.deferral == "async":
			// A script's override returns its result, its task, or, if it awaits, its function's state.
			w.ln("\tVariant _gdpp_ret;")
			w.ln("\tif (GDVIRTUAL_CALL(%s)) {", strings.Join(slices.DeleteFunc([]string{f.f.Name, callArgs, "_gdpp_ret"}, func(s string) bool { return s == "" }), ", "))
			w.ln("\t\treturn gdpp::async_of<%s>(_gdpp_ret);", f.ret.async.cpp)
		default:
			w.ln("\t%s _gdpp_ret;", tagged(owner, f.ret))
			w.ln("\tif (GDVIRTUAL_CALL(%s)) {", strings.Join(slices.DeleteFunc([]string{f.f.Name, callArgs, "_gdpp_ret"}, func(s string) bool { return s == "" }), ", "))
			w.ln("\t\treturn %s;", cast(owner, f.ret, "_gdpp_ret", false))
		}
		w.ln("\t}")
	}
	switch {
	case f.calls != nil && f.ret.void:
		w.ln("\t%s(%s);", f.calls.f.Name, strings.Join(paramNames(f.f.Params), ", "))
	case f.calls != nil:
		w.ln("\treturn %s(%s);", f.calls.f.Name, strings.Join(paramNames(f.f.Params), ", "))
	case f.deferral == "async":
		self := "this"
		if f.static {
			self = "nullptr"
		}
		run := "return gdpp::run_coroutine"
		if f.detached {
			run = "gdpp::run_detached_coroutine"
		}
		w.ln("\t%s(%s, %s(%s));", run, self, bodyName(f), strings.Join(paramNames(f.f.Params), ", "))
	case f.deferral == "onthread":
		self, capture := "this", "=, this"
		if f.static {
			self, capture = "nullptr", "="
		}
		run := "return gdpp::run_task"
		if f.detached {
			run = "gdpp::run_detached"
		}
		w.ln("\t%s(%s, %q, [%s] { return %s(%s); });", run, self, c.name+"."+f.f.Name, capture,
			bodyName(f), strings.Join(paramNames(f.f.Params), ", "))
	case f.deferral != "" && f.isConst:
		w.ln("\t%s;", deferredCall(f.deferral, fmt.Sprintf("const_cast<%s *>(this)", c.name), bodyName(f), f.params, f.f.Params))
	case f.deferral != "":
		w.ln("\t%s;", deferredCall(f.deferral, "this", bodyName(f), f.params, f.f.Params))
	case f.gpu != nil:
		u.shaderCall(w, c, f)
	case f.f.Body != nil && f.coro != nil:
		w.block(f.f.Body, "", "", assertCoFor(f.coro.void))
	case f.f.Body != nil:
		w.block(f.f.Body, "", "", assertFor(f.ret.void))
	case !f.ret.void:
		w.ln("\treturn {};")
	}
	if wrap {
		w.ln("\t}());")
	}
	w.ln("}")
	if f.scripted() || f.override || !f.trampolined() {
		return
	}
	w.ln("")
	w.ln("%s {", qualified(c, tagged(c, f.ret), "_gdpp_"+f.f.Name, params(c, f.params, f.f.Params), f.isConst))
	guard(w, f.only, f.ret.cpp)
	call := fmt.Sprintf("%s(%s)", f.f.Name, castList(c, f.params, f.f.Params, false))
	if f.ret.void {
		w.ln("\t%s;", call)
	} else {
		w.ln("\treturn %s;", cast(c, f.ret, call, true))
	}
	w.ln("}")
}

// defaultDefs defines the static methods that return the default values of f's parameters.
func defaultDefs(w *writer, c *classModel, f *funcModel) {
	for i, p := range f.f.Params {
		d := p.Default
		if d == nil {
			continue
		}
		w.ln("")
		w.ln("%s {", qualified(c, f.params[i].cpp, defaultName(f, p), "", false))
		guard(w, f.only, f.params[i].cpp)
		if d.Block != nil {
			w.block(d.Block, "", "", assertValue)
		} else {
			w.user(d.Pos, d.Origin, "\treturn ", d.Expr, ";", assertValue)
		}
		w.ln("}")
	}
}

// accessorDefs defines the getter and setter of v, and their trampolines.
func (u *unit) accessorDefs(w *writer, c *classModel, v *varModel) {
	if v.getter != "" {
		w.ln("")
		w.ln("%s {", qualified(c, v.t.cpp, v.getter, "", true))
		if field := v.guardField(); field != "" {
			if v.get != nil || v.profile { // Else the getter is trivial already.
				guardWith(w, v.only, "return "+field+";")
			}
		} else {
			guard(w, v.only, v.t.cpp)
		}
		if v.profile {
			u.profile(w, c.name+"."+v.getter)
		}
		if v.get != nil {
			w.block(v.get, "", "", assertValue)
		} else {
			w.ln("\treturn %s;", v.v.Name)
		}
		w.ln("}")
	}
	if v.setter != "" {
		w.ln("")
		w.ln("%s {", qualified(c, "void", v.setter, withSpace(v.t.param())+v.setterParam(), false))
		if field := v.guardField(); field != "" {
			guardWith(w, v.only, field+" = "+v.setterParam()+";", "return;")
		} else {
			guard(w, v.only, "void")
		}
		if v.deferral == "" { // Else the set block's method, which the call runs, profiles and watches.
			if v.profile {
				u.profile(w, c.name+"."+v.setter)
			}
			watch(w, c, v.setter)
		}
		switch {
		case v.deferral != "":
			w.ln("\t%s;", deferredCall(v.deferral, "this", "_gdpp_body_"+v.setter, []*gtype{v.t}, []*Param{v.set.Param}))
		case v.set != nil:
			w.block(v.set.Body, "", "", assertVoid)
		default:
			w.ln("\t%s = p_value;", v.v.Name)
		}
		w.ln("}")
	}
	if !v.trampolined() {
		return
	}
	tag := tagName(c, v.t.enum)
	if v.getter != "" {
		w.ln("")
		w.ln("%s {", qualified(c, tag, "_gdpp_"+v.getter, "", true))
		w.ln("\treturn static_cast<%s>(%s());", tag, v.getter)
		w.ln("}")
	}
	if v.setter != "" {
		w.ln("")
		w.ln("%s {", qualified(c, "void", "_gdpp_"+v.setter, tag+" p_value", false))
		w.ln("\t%s(static_cast<%s>(p_value));", v.setter, v.t.cpp)
		w.ln("}")
	}
}

// method returns the D_METHOD expression for a method named name with the given parameters.
func method(name string, list ...string) string {
	quoted := []string{fmt.Sprintf("%q", name)}
	for _, p := range list {
		quoted = append(quoted, fmt.Sprintf("%q", p))
	}
	return "D_METHOD(" + strings.Join(quoted, ", ") + ")"
}

func paramNames(list []*Param) []string {
	var names []string
	for _, p := range list {
		names = append(names, p.Name)
	}
	return names
}

// info returns the gdpp::info expression for a value of type t named name, as class c binds it.
func info(c *classModel, t *gtype, name, usage, hint, hintString string) string {
	s := fmt.Sprintf("gdpp::info<%s>(%q", tagged(c, t), name)
	if usage != "" {
		s += ", " + usage
	}
	if hint != "" && hint != "PROPERTY_HINT_NONE" {
		s += fmt.Sprintf(", %s, %q", hint, hintString)
	}
	return s + ")"
}

// bindings writes the body of _bind_methods.
func (u *unit) bindings(w *writer, c *classModel) {
	for _, f := range c.funcs {
		if f.hidden == "onthread" || f.hidden == "async" || f.hidden == "notif" || f.isPrivate {
			continue // Its func, or _notification, calls it directly. Or it's @private.
		}
		// The method, followed by the default values of its parameters.
		ref := fmt.Sprintf("&%s::%s", c.name, f.f.Name)
		if f.trampolined() {
			ref = fmt.Sprintf("&%s::_gdpp_%s", c.name, f.f.Name)
		}
		names := paramNames(f.f.Params)
		for i, p := range f.f.Params {
			if p.Default == nil {
				continue
			}
			value := defaultName(f, p) + "()"
			if f.params[i].enum != nil {
				value = "static_cast<int64_t>(" + value + ")"
			}
			ref += ", DEFVAL(" + value + ")"
		}
		switch {
		case f.override:
		case f.scripted():
			quoted := []string{f.f.Name}
			for _, n := range names {
				quoted = append(quoted, fmt.Sprintf("%q", n))
			}
			w.ln("\tGDVIRTUAL_BIND(%s);", strings.Join(quoted, ", "))
		case f.static:
			w.ln("\tClassDB::bind_static_method(get_class_static(), %s, %s);", method(f.f.Name, names...), ref)
		default:
			w.ln("\tClassDB::bind_method(%s, %s);", method(f.f.Name, names...), ref)
		}
	}
	for _, role := range factoryRoles {
		name, ok := c.factory[role]
		if !ok {
			continue
		}
		switch role {
		case "destroy", "queue_destroy":
			w.ln("\tClassDB::bind_method(%s, &%s::%s);", method(name), c.name, name)
		case "pool_reserve":
			// The count defaults to the pool's size, if it has one.
			defaults := "DEFVAL(String())"
			if c.pool.size != "0" {
				defaults = "DEFVAL(" + c.pool.size + "), " + defaults
			}
			w.ln("\tClassDB::bind_static_method(get_class_static(), %s, &%s::%s, %s);", method(name, "count", "mode"), c.name, name, defaults)
		case "pool_clear":
			w.ln("\tClassDB::bind_static_method(get_class_static(), %s, &%s::%s, DEFVAL(false));", method(name, "keep_in_use"), c.name, name)
		case "compile_shader", "compile_shader_async", "compile_shader_detached":
			w.ln("\tClassDB::bind_static_method(get_class_static(), %s, &%s::%s);", method(name, "shader"), c.name, name)
		default:
			w.ln("\tClassDB::bind_static_method(get_class_static(), %s, &%s::%s);", method(name), c.name, name)
		}
	}
	for _, v := range c.vars {
		for _, s := range v.sections {
			if s.ann.Name == "export_category" {
				w.ln("\tgdpp::add_property_category(get_class_static(), %q);", s.name)
			} else {
				w.ln("\tClassDB::add_property_%s(get_class_static(), %q, %q);", strings.TrimPrefix(s.ann.Name, "export_"), s.name, s.prefix)
			}
		}
		prefix := "&" + c.name + "::"
		if v.trampolined() {
			prefix += "_gdpp_"
		}
		if v.getter != "" {
			w.ln("\tClassDB::bind_method(%s, %s%s);", method(v.getter), prefix, v.getter)
		}
		if v.setter != "" {
			w.ln("\tClassDB::bind_method(%s, %s%s);", method(v.setter, "value"), prefix, v.setter)
		}
		w.ln("\tClassDB::add_property(get_class_static(), %s, %q, %q);",
			info(c, v.t, v.v.Name, v.usage, v.hint, v.hintString), v.setter, v.getter)
	}
	for _, s := range c.signals {
		infos := []string{fmt.Sprintf("%q", s.s.Name)}
		for i, t := range s.params {
			infos = append(infos, info(c, t, s.s.Params[i].Name, "", "", ""))
		}
		w.ln("\tClassDB::add_signal(get_class_static(), MethodInfo(%s));", strings.Join(infos, ", "))
	}
	for _, k := range c.consts {
		w.ln("\tClassDB::bind_integer_constant(get_class_static(), \"\", %q, %s);", k.Name, k.Name)
	}
	for _, e := range c.enums {
		bitfield := ""
		if e.bitfield {
			bitfield = ", true"
		}
		for _, v := range e.values {
			w.ln("\tClassDB::bind_integer_constant(get_class_static(), %q, %q, static_cast<int64_t>(%s::%s)%s);",
				e.name, upperSnake(e.name)+"_"+v.Name, e.name, v.Name, bitfield)
		}
	}
}

// typeNames returns the names used in t, including its type arguments.
func typeNames(t *Type) []string {
	if t == nil {
		return nil
	}
	names := []string{t.Name}
	for _, a := range t.Args {
		names = append(names, typeNames(a)...)
	}
	return names
}

// headerNames returns the names used in the header: bases, API types, imports and decl code. complete lists
// those that need a complete type: bases, the types of virtual functions (GDVIRTUAL needs them), and names in decl
// code, which may use any member.
func (u *unit) headerNames() (names, complete []string) {
	add := func(ts ...*Type) {
		for _, t := range ts {
			names = append(names, typeNames(t)...)
		}
	}
	code := func(b *Block) { complete = append(complete, identifiers(b.Text)...) }
	addFuncs := func(funcs []*funcModel, vars []*varModel, signals []*signalModel) {
		for _, f := range funcs {
			add(f.f.Return)
			for _, p := range f.f.Params {
				add(p.Type)
			}
		}
		for _, v := range vars {
			add(v.v.Type)
			for _, d := range v.decls {
				code(d)
			}
		}
		for _, s := range signals {
			for _, p := range s.s.Params {
				add(p.Type)
			}
		}
	}
	for _, e := range u.externs {
		complete = append(complete, e.base)
		addFuncs(e.funcs, e.vars, e.signals)
	}
	for _, t := range u.traits {
		complete = append(complete, t.base)
		addFuncs(t.funcs, nil, nil)
	}
	for _, c := range u.classes {
		complete = append(append(complete, c.base), c.traits...)
		add(c.imports...)
		addFuncs(c.funcs, c.vars, c.signals)
		for _, f := range c.funcs {
			if f.scripted() {
				complete = append(complete, typeNames(f.f.Return)...)
				for _, p := range f.f.Params {
					complete = append(complete, typeNames(p.Type)...)
				}
			}
		}
		for _, code := range slices.Concat(c.codes, c.globals) {
			if code.Decl {
				complete = append(complete, identifiers(code.Body.Text)...)
			}
		}
	}
	return append(names, complete...), complete
}

// sourceNames returns the names used in the source: function bodies, initial values, impl code, and the enums
// that _bind_methods binds.
func (u *unit) sourceNames() []string {
	var names []string
	code := func(b *Block) {
		if b != nil {
			names = append(names, identifiers(b.Text)...)
		}
	}
	for _, c := range u.classes {
		for _, e := range c.enums {
			names = append(names, e.name)
		}
		code(c.ctor)
		code(c.dtor)
		code(c.recycleCtor)
		code(c.recycleDtor)
		for _, f := range c.funcs {
			code(f.f.Body)
			for _, p := range f.f.Params {
				if d := p.Default; d != nil {
					code(d.Block)
					names = append(names, identifiers(d.Expr)...)
				}
			}
			if f.rpc != nil {
				names = append(names, "MultiplayerAPI", "MultiplayerPeer")
			}
		}
		for _, v := range c.vars {
			code(v.get)
			if v.set != nil {
				code(v.set.Body)
			}
			if init := v.v.Init; init != nil {
				code(init.Block)
				names = append(names, identifiers(init.Expr)...)
			}
		}
		for _, cd := range slices.Concat(c.codes, c.globals) {
			if cd.Impl {
				code(cd.Body)
			}
		}
	}
	return names
}

// includes returns the sorted includes of the dependencies named in names, except those in exclude and those
// that a noimport suppresses.
func (u *unit) includes(names []string, exclude map[string]bool) []string {
	noimport := map[string]bool{}
	for _, c := range u.classes {
		for _, t := range c.noimports {
			noimport[t.Name] = true
		}
	}
	var incs []string
	for _, name := range names {
		if s := u.symbols[name]; s != nil && s.include != "" && !exclude[name] && !noimport[name] && !slices.Contains(incs, s.include) {
			incs = append(incs, s.include)
		}
	}
	slices.Sort(incs)
	return incs
}
